/**
 * Substance database — a curated subset of peak-tracker.html's full library.
 *
 * Each entry's pharmacokinetics (onset / peak / halfLife / amp) are direct
 * ports from peak-tracker.html so the math stays consistent for users who
 * cross over between the standalone and Vitality. When adding new entries,
 * mirror the same shape and keep amp scaled to "focus score points at peak,
 * assuming standard dose at tolerance 5 / 75kg bodyweight".
 */

import type { SubstanceDef } from './types'

export const SUBSTANCES: Record<string, SubstanceDef> = {
  // ─── Caffeine ──────────────────────────────────────────────────
  coffee: {
    key: 'coffee',
    name: 'Coffee',
    category: 'caffeine',
    icon: '☕',
    defaultDose: 95,
    unit: 'mg',
    amplitude: 16,
    onsetHours: 0.25,
    peakHours: 0.75,
    halfLifeHours: 5.0,
    mechanism: 'Adenosine antagonist. Blocks fatigue signals.',
  },
  espresso: {
    key: 'espresso',
    name: 'Espresso',
    category: 'caffeine',
    icon: '☕',
    defaultDose: 75,
    unit: 'mg',
    amplitude: 14,
    onsetHours: 0.2,
    peakHours: 0.5,
    halfLifeHours: 5.0,
    mechanism: 'Concentrated caffeine with fast onset.',
  },
  energy_drink: {
    key: 'energy_drink',
    name: 'Energy drink',
    category: 'caffeine',
    icon: '⚡',
    defaultDose: 160,
    unit: 'mg',
    amplitude: 22,
    onsetHours: 0.2,
    peakHours: 0.5,
    halfLifeHours: 5.0,
    mechanism: 'Caffeine + taurine + sugar.',
  },
  matcha: {
    key: 'matcha',
    name: 'Matcha',
    category: 'caffeine',
    icon: '🍵',
    defaultDose: 70,
    unit: 'mg',
    amplitude: 12,
    onsetHours: 0.5,
    peakHours: 1.5,
    halfLifeHours: 5.0,
    mechanism: 'Slow-release caffeine + L-theanine.',
  },

  // ─── Hydration ─────────────────────────────────────────────────
  water: {
    key: 'water',
    name: 'Water',
    category: 'hydration',
    icon: '💧',
    defaultDose: 8,
    unit: 'oz',
    amplitude: 6,
    onsetHours: 0.1,
    peakHours: 0.5,
    halfLifeHours: 1.5,
    mechanism: 'Restores plasma volume for a small focus boost.',
  },
  electrolytes: {
    key: 'electrolytes',
    name: 'Electrolytes',
    category: 'hydration',
    icon: '🧂',
    defaultDose: 1,
    unit: 'pkt',
    amplitude: 8,
    onsetHours: 0.15,
    peakHours: 0.5,
    halfLifeHours: 2.0,
    mechanism: 'Sodium and potassium. Supports nerve and muscle function.',
  },

  // ─── Supplements ───────────────────────────────────────────────
  l_theanine: {
    key: 'l_theanine',
    name: 'L-theanine',
    category: 'supplement',
    icon: '🟢',
    defaultDose: 200,
    unit: 'mg',
    amplitude: 6,
    onsetHours: 0.5,
    peakHours: 1.0,
    halfLifeHours: 3.0,
    mechanism: 'Boosts alpha brain waves for calm focus.',
  },
  magnesium: {
    key: 'magnesium',
    name: 'Magnesium',
    category: 'supplement',
    icon: '🟣',
    defaultDose: 400,
    unit: 'mg',
    amplitude: 4,
    onsetHours: 1.0,
    peakHours: 2.0,
    halfLifeHours: 6.0,
    mechanism: 'GABA modulation. Relaxes without sedation.',
  },
  melatonin: {
    key: 'melatonin',
    name: 'Melatonin',
    category: 'supplement',
    icon: '🌙',
    defaultDose: 3,
    unit: 'mg',
    amplitude: -8,
    onsetHours: 0.5,
    peakHours: 1.0,
    halfLifeHours: 1.0,
    mechanism: 'Pineal hormone. Drops alertness and induces sleep.',
  },
  b_complex: {
    key: 'b_complex',
    name: 'B-complex',
    category: 'supplement',
    icon: '💊',
    defaultDose: 1,
    unit: 'pill',
    amplitude: 4,
    onsetHours: 0.5,
    peakHours: 1.5,
    halfLifeHours: 4.0,
    mechanism: 'Cofactors for energy metabolism.',
  },

  // ─── Workout (active exercise window) ─────────────────────────
  workout: {
    key: 'workout',
    name: 'Workout',
    category: 'workout',
    icon: '🏋️',
    defaultDose: 1,
    unit: 'session',
    amplitude: 22,
    onsetHours: 0.0,
    peakHours: 0.5,
    halfLifeHours: 1.5,
    mechanism: 'Acute exercise → BDNF + dopamine + NE spike.',
  },

  // ─── Depressants ──────────────────────────────────────────────
  alcohol: {
    key: 'alcohol',
    name: 'Alcohol (drink)',
    category: 'depressant',
    icon: '🍺',
    defaultDose: 1,
    unit: 'drink',
    amplitude: -10,
    onsetHours: 0.2,
    peakHours: 0.75,
    halfLifeHours: 1.0,
    mechanism: 'GABA agonist and glutamate antagonist. Sedates.',
  },

  // ─── Stimulants: ADHD meds (Peak Stack port) ──────────────────
  // amplitude ≈ focus-score points at peak for a standard dose at tolerance 5 /
  // 75 kg, ported from peak-stack.html's pharmacokinetics so the standalone and
  // the hosted curve stay calibrated. onset/peak/halfLife in hours.
  vyvanse: {
    key: 'vyvanse',
    name: 'Vyvanse',
    category: 'adhd',
    icon: '⚡',
    defaultDose: 40,
    unit: 'mg',
    amplitude: 23,
    onsetHours: 1.5,
    peakHours: 3.5,
    halfLifeHours: 11,
    mechanism: 'Lisdexamfetamine prodrug. Smooth ramp, lasts 10–14 h.',
  },
  adderall_ir: {
    key: 'adderall_ir',
    name: 'Adderall IR',
    category: 'adhd',
    icon: '⚡',
    defaultDose: 20,
    unit: 'mg',
    amplitude: 24,
    onsetHours: 0.5,
    peakHours: 3,
    halfLifeHours: 10,
    mechanism: 'Amphetamine salts, immediate-release. Fades 4–6 h.',
  },
  adderall_xr: {
    key: 'adderall_xr',
    name: 'Adderall XR',
    category: 'adhd',
    icon: '⚡',
    defaultDose: 20,
    unit: 'mg',
    amplitude: 23,
    onsetHours: 1,
    peakHours: 7,
    halfLifeHours: 11,
    mechanism: 'Extended-release amphetamine. 10–12 h coverage.',
  },
  ritalin_ir: {
    key: 'ritalin_ir',
    name: 'Ritalin IR',
    category: 'adhd',
    icon: '⚡',
    defaultDose: 10,
    unit: 'mg',
    amplitude: 19,
    onsetHours: 0.5,
    peakHours: 2,
    halfLifeHours: 3,
    mechanism: 'Methylphenidate IR. Sharp and short — 3–4 h.',
  },
  concerta: {
    key: 'concerta',
    name: 'Concerta',
    category: 'adhd',
    icon: '⚡',
    defaultDose: 36,
    unit: 'mg',
    amplitude: 19,
    onsetHours: 1,
    peakHours: 8,
    halfLifeHours: 3.5,
    mechanism: 'Methylphenidate ER (osmotic). Slow ramp, 10–12 h.',
  },
  modafinil: {
    key: 'modafinil',
    name: 'Modafinil',
    category: 'adhd',
    icon: '🧠',
    defaultDose: 150,
    unit: 'mg',
    amplitude: 20,
    onsetHours: 0.75,
    peakHours: 2.5,
    halfLifeHours: 13,
    mechanism: 'Wakefulness promoter. Long and flat — t½ ~13 h.',
  },

  // ─── Stimulants: caffeine blend + nicotine ────────────────────
  pre_workout: {
    key: 'pre_workout',
    name: 'Pre-workout',
    category: 'caffeine',
    icon: '🥤',
    defaultDose: 250,
    unit: 'mg',
    amplitude: 21,
    onsetHours: 0.25,
    peakHours: 1,
    halfLifeHours: 5,
    mechanism: 'Caffeine + beta-alanine blend. Big spike, big crash.',
  },
  nicotine: {
    key: 'nicotine',
    name: 'Nicotine (pouch/vape)',
    category: 'nicotine',
    icon: '🚬',
    defaultDose: 4,
    unit: 'mg',
    amplitude: 10,
    onsetHours: 0.05,
    peakHours: 0.25,
    halfLifeHours: 2,
    mechanism: 'Pouch, gum, vape. Fast, sharp, short — and addictive.',
  },
}

/**
 * Quick-log shortlist for the substance picker. Order matters — these
 * render as the default chips. Everything else is searchable.
 */
export const QUICK_LOG_KEYS = ['coffee', 'water', 'workout', 'l_theanine']

export function getSubstance(key: string): SubstanceDef | undefined {
  return SUBSTANCES[key]
}
