/**
 * Preset training rotations the user can pick from in the setup wizard.
 *
 * Each preset defines a default day list. Once picked, the user can rename
 * days, mark heavy/volume/rest, add or remove days. The customized result
 * is persisted to training_settings.rotation_days.
 *
 * Curation reflects the 2026-05-25 research synthesis: 4 evidence-backed
 * v1 splits drawn from Schoenfeld 2016 meta-analysis (twice-weekly
 * frequency), Helms Pyramid (adherence-first), and real-world adherence
 * data (Conti et al. 522k-user SportRxiv 709). v1.1 will add PHUL,
 * 5/3/1 BBB, and Bro Split; v1.2 will gate PHAT + Arnold behind an
 * Advanced toggle.
 */

import type { DayType, Category, DayExercise } from '../log/splitData'
import type { GoalPreferences } from '@/lib/preferences'

export interface PresetDay {
  name: string
  type: DayType
  category: Category
  exercises: DayExercise[]
  /** Active-rest metadata. Present only on rest days that the
   *  recommendation engine has upgraded based on the user's intake quiz
   *  (cardio appetite, sport, recovery). The day is still a recovery
   *  day from a fatigue standpoint — the activity is what they do on it.
   *  Persisted via the same rotation_days JSON path as the rest of the
   *  day, but always regenerable from intake so a missing field is OK. */
  activeRest?: ActiveRest
}

/**
 * The activity slotted into an upgraded rest day. Generated by the
 * recommendation engine from intake answers; users can swap or revert
 * to full rest via the day-row change chip in step 2.
 */
export interface ActiveRest {
  activity: ActiveRestActivity
  /** Duration in minutes. The engine picks a sensible default per
   *  activity, but users can override in the activity-picker sheet
   *  (we can't guess every individual's session length). */
  durationMin: number
  /** Short engine-generated copy explaining why this slot got this
   *  activity — surfaces in the row + change-activity sheet so the
   *  user understands the matching, not just the suggestion. */
  notes?: string
  /** User-typed label, only set when activity === 'custom'.
   *  Lets users define anything outside our preset list
   *  (e.g. "Breathwork", "Pickleball", "Sauna"). */
  customLabel?: string
}

export type ActiveRestActivity =
  | 'cardio_zone2'      // steady-state aerobic — base building
  | 'cardio_intervals'  // intervals — for cardio "primary" users
  | 'sport'             // user's existing sport, kept as-is
  | 'yoga'              // structured yoga practice — distinct from generic mobility
  | 'mobility'          // mobility + soft tissue work — stressed-recovery default
  | 'walk'              // lightest option — for rough-recovery weeks
  | 'custom'            // user-defined — uses customLabel for the display name

/**
 * Beginner-friendliness rating — drives the green/yellow/red dot on the
 * split picker card. "beginner" = recommended for first-timers, simplest
 * schedule. "advanced" = high volume, demanding programming.
 */
export type SplitLevel = 'beginner' | 'intermediate' | 'advanced'

export interface Preset {
  id:
    | 'full_body_2'  // minimalist 2-day — busy / returning lifter
    | 'full_body_3'  // classic 3-day novice template (Stronglifts-style)
    | 'upper_lower_4' // research-validated intermediate default
    | 'ppl_3'         // standard Mon/Wed/Fri PPL — what most casuals actually run
    | 'bro_5'         // chest / back / shoulders / arms / legs — aesthetic-focused intermediate
    | 'ppl_6'         // advanced hypertrophy specialist (PPL ×2)
    | 'blank'
  name: string
  meta: string
  /** One-line plain-English description of what the split is for. */
  lede?: string
  /** Beginner-friendliness rating (driven by gym-floor reality, not
   *  programming geek-out). Affects the colored dot on the card. */
  level?: SplitLevel
  /** When true, the days array is a rotating cycle that drifts through
   *  the calendar week (e.g. classic PPL — push/pull/legs/rest repeat).
   *  Drives the card's day-strip rendering: session-letter labels
   *  (P · P · L · R · ...) instead of weekday letters, plus a ↻ glyph
   *  in the meta line. Default false = fixed weekly schedule. */
  rotating?: boolean
  /** Plain-English explanation shown in the per-card info popover when
   *  the user taps the (i). 2–3 sentences max — who it's for, what it
   *  hits, why someone would pick it. Skip jargon. */
  info?: string
  /** 3 short scannable highlights rendered as mint-checkmark bullets at
   *  the top of the info popover, ABOVE the full paragraph. Each one
   *  ≤8 words. Lets a user judge "is this for me?" without reading prose. */
  infoHighlights?: string[]
  days: PresetDay[]
}

// ────────────────────────────────────────────────────────────────────────────
// Reusable exercise templates
// ────────────────────────────────────────────────────────────────────────────
// Heavy day templates emphasize T1 compounds at low reps (4–6, ~RPE 8).
// Volume day templates lead with T2 secondary compounds at higher reps
// (8–12, ~RPE 8–9) and isolate the back half.
// Numbers tracked against the Schoenfeld 2017 dose-response → ~10
// sets/muscle/week as the soft floor for near-maximal hypertrophy.

const pushHeavy: DayExercise[] = [
  { id: 'bench_bb',        sets: 4, reps: 5  },
  { id: 'standing_ohp',    sets: 4, reps: 6  },
  { id: 'incl_db_press',   sets: 3, reps: 8  },
  { id: 'cable_lat_raise', sets: 4, reps: 12 },
  { id: 'tri_pushdown',    sets: 3, reps: 12 },
  { id: 'oh_tri_ext',      sets: 3, reps: 12 },
]

const pushVolume: DayExercise[] = [
  { id: 'incl_bb_bench',   sets: 4, reps: 8  },
  { id: 'seated_db_ohp',   sets: 4, reps: 10 },
  { id: 'flat_db_press',   sets: 3, reps: 10 },
  { id: 'cable_fly',       sets: 3, reps: 15 },
  { id: 'db_lat_raise',    sets: 4, reps: 15 },
  { id: 'tri_pushdown',    sets: 4, reps: 12 },
]

const pullHeavy: DayExercise[] = [
  { id: 'conv_dl',         sets: 4, reps: 5  },
  { id: 'pullup_weighted', sets: 4, reps: 6  },
  { id: 'bb_row',          sets: 3, reps: 8  },
  { id: 'face_pull',       sets: 4, reps: 15 },
  { id: 'bb_curl',         sets: 3, reps: 10 },
  { id: 'hammer_curl',     sets: 3, reps: 10 },
]

const pullVolume: DayExercise[] = [
  { id: 'pendlay_row',      sets: 4, reps: 8  },
  { id: 'lat_pulldown',     sets: 4, reps: 10 },
  { id: 'seated_cable_row', sets: 3, reps: 10 },
  { id: 'reverse_pec',      sets: 3, reps: 15 },
  { id: 'incl_db_curl',     sets: 3, reps: 12 },
  { id: 'cable_curl',       sets: 3, reps: 15 },
]

const legsHeavy: DayExercise[] = [
  { id: 'back_squat',      sets: 4, reps: 5  },
  { id: 'rdl',             sets: 3, reps: 6  },
  { id: 'leg_press',       sets: 3, reps: 10 },
  { id: 'lying_leg_curl',  sets: 3, reps: 12 },
  { id: 'calf_raise',      sets: 4, reps: 10 },
  { id: 'hang_leg_raise',  sets: 3, reps: 12 },
]

const legsVolume: DayExercise[] = [
  { id: 'front_squat',     sets: 4, reps: 8  },
  { id: 'hip_thrust',      sets: 4, reps: 10 },
  { id: 'bulgarian_ss',    sets: 3, reps: 10 },
  { id: 'leg_ext',         sets: 3, reps: 15 },
  { id: 'seated_leg_curl', sets: 3, reps: 15 },
  { id: 'calf_raise',      sets: 4, reps: 15 },
]

// 4-Day Upper/Lower templates — the research-validated intermediate
// default. Hits each muscle 2×/week (Schoenfeld 2016 sweet spot).

const upperHeavy: DayExercise[] = [
  { id: 'bench_bb',         sets: 4, reps: 5  },
  { id: 'pullup_weighted',  sets: 4, reps: 6  },
  { id: 'standing_ohp',     sets: 3, reps: 8  },
  { id: 'chest_supp_row',   sets: 3, reps: 8  },
  { id: 'cable_lat_raise',  sets: 3, reps: 12 },
  { id: 'bb_curl',          sets: 3, reps: 10 },
  { id: 'tri_pushdown',     sets: 3, reps: 12 },
]

const upperVolume: DayExercise[] = [
  { id: 'incl_db_press',    sets: 4, reps: 8  },
  { id: 'bb_row',           sets: 4, reps: 8  },
  { id: 'seated_db_ohp',    sets: 3, reps: 10 },
  { id: 'lat_pulldown',     sets: 3, reps: 10 },
  { id: 'cable_fly',        sets: 3, reps: 12 },
  { id: 'face_pull',        sets: 3, reps: 15 },
  { id: 'hammer_curl',      sets: 3, reps: 12 },
  { id: 'oh_tri_ext',       sets: 3, reps: 12 },
]

const lowerHeavy: DayExercise[] = [
  { id: 'back_squat',       sets: 4, reps: 5  },
  { id: 'rdl',              sets: 3, reps: 6  },
  { id: 'bulgarian_ss',     sets: 3, reps: 8  },
  { id: 'lying_leg_curl',   sets: 3, reps: 12 },
  { id: 'calf_raise',       sets: 4, reps: 12 },
  { id: 'hang_leg_raise',   sets: 3, reps: 12 },
]

const lowerVolume: DayExercise[] = [
  { id: 'front_squat',      sets: 4, reps: 8  },
  { id: 'hip_thrust',       sets: 4, reps: 8  },
  { id: 'leg_press',        sets: 3, reps: 10 },
  { id: 'leg_ext',          sets: 3, reps: 12 },
  { id: 'seated_leg_curl',  sets: 3, reps: 12 },
  { id: 'calf_raise',       sets: 4, reps: 15 },
  { id: 'cable_crunch',     sets: 3, reps: 15 },
]

// Full Body templates — A leads with squat/bench, B leads with deadlift/OHP.
// 2-Day FB uses one of each; 3-Day FB alternates A/B/A.

const fullBodyA: DayExercise[] = [
  { id: 'back_squat',  sets: 3, reps: 5  },
  { id: 'bench_bb',    sets: 3, reps: 5  },
  { id: 'bb_row',      sets: 3, reps: 6  },
  { id: 'standing_ohp', sets: 2, reps: 8  },
  { id: 'rdl',         sets: 2, reps: 8  },
  { id: 'plank',       sets: 2, reps: 45 }, // reps = seconds for time-based
]

const fullBodyB: DayExercise[] = [
  { id: 'conv_dl',         sets: 3, reps: 5  },
  { id: 'standing_ohp',    sets: 3, reps: 6  },
  { id: 'pullup_weighted', sets: 3, reps: 6  },
  { id: 'walking_lunge',   sets: 2, reps: 10 },
  { id: 'incl_db_press',   sets: 3, reps: 10 },
  { id: 'hang_leg_raise',  sets: 2, reps: 12 },
]

// Classic PPL templates — Push, Pull, Legs, Rest, repeat. The real
// PPL rotation that hits each muscle twice a week (Schoenfeld 2016
// frequency sweet spot) without the heavy/volume split that the
// advanced ppl_6 variant adds. All sessions run at HEAVY-style volume —
// no V days, no doubling up. The rest day every 4th day is what makes
// it sustainable at this frequency without burning out.

const pushPPLClassic: DayExercise[] = [
  { id: 'bench_bb',        sets: 4, reps: 6  },
  { id: 'standing_ohp',    sets: 3, reps: 8  },
  { id: 'incl_db_press',   sets: 3, reps: 10 },
  { id: 'cable_fly',       sets: 3, reps: 12 },
  { id: 'cable_lat_raise', sets: 4, reps: 12 },
  { id: 'tri_pushdown',    sets: 3, reps: 12 },
  { id: 'oh_tri_ext',      sets: 3, reps: 12 },
]

const pullPPLClassic: DayExercise[] = [
  { id: 'conv_dl',         sets: 3, reps: 5  },
  { id: 'pullup_weighted', sets: 4, reps: 8  },
  { id: 'bb_row',          sets: 3, reps: 8  },
  { id: 'lat_pulldown',    sets: 3, reps: 10 },
  { id: 'face_pull',       sets: 3, reps: 15 },
  { id: 'bb_curl',         sets: 3, reps: 10 },
  { id: 'hammer_curl',     sets: 3, reps: 12 },
]

const legsPPLClassic: DayExercise[] = [
  { id: 'back_squat',      sets: 4, reps: 6  },
  { id: 'rdl',             sets: 3, reps: 8  },
  { id: 'leg_press',       sets: 3, reps: 10 },
  { id: 'lying_leg_curl',  sets: 3, reps: 12 },
  { id: 'leg_ext',         sets: 3, reps: 12 },
  { id: 'calf_raise',      sets: 4, reps: 12 },
  { id: 'hang_leg_raise',  sets: 3, reps: 12 },
]

// 5-Day Bro Split templates — chest, back, shoulders, arms, legs.
// Once-per-week frequency, highest per-session volume. Adherence value
// is real: aesthetic-focused YouTube audience (Sulek, Lee, the lot) all
// run or have run this — gym-floor reality > frequency theory.

const broChest: DayExercise[] = [
  { id: 'bench_bb',        sets: 4, reps: 6  },
  { id: 'incl_bb_bench',   sets: 3, reps: 8  },
  { id: 'flat_db_press',   sets: 3, reps: 10 },
  { id: 'cable_fly',       sets: 3, reps: 12 },
  { id: 'dips_weighted',   sets: 3, reps: 10 },
  { id: 'pec_deck',        sets: 3, reps: 15 },
]

const broBack: DayExercise[] = [
  { id: 'pullup_weighted',  sets: 4, reps: 6  },
  { id: 'bb_row',           sets: 4, reps: 8  },
  { id: 'lat_pulldown',     sets: 3, reps: 10 },
  { id: 'seated_cable_row', sets: 3, reps: 10 },
  { id: 'chest_supp_row',   sets: 3, reps: 12 },
  { id: 'face_pull',        sets: 3, reps: 15 },
]

const broShoulders: DayExercise[] = [
  { id: 'standing_ohp',    sets: 4, reps: 6  },
  { id: 'seated_db_ohp',   sets: 3, reps: 8  },
  { id: 'db_lat_raise',    sets: 4, reps: 12 },
  { id: 'cable_lat_raise', sets: 3, reps: 15 },
  { id: 'rear_delt_fly',   sets: 3, reps: 15 },
  { id: 'reverse_pec',     sets: 3, reps: 15 },
]

const broArms: DayExercise[] = [
  { id: 'bb_curl',         sets: 4, reps: 8  },
  { id: 'close_grip',      sets: 4, reps: 8  },
  { id: 'incl_db_curl',    sets: 3, reps: 10 },
  { id: 'skullcrushers',   sets: 3, reps: 10 },
  { id: 'hammer_curl',     sets: 3, reps: 12 },
  { id: 'tri_pushdown',    sets: 3, reps: 12 },
  { id: 'cable_curl',      sets: 3, reps: 15 },
]

const broLegs: DayExercise[] = [
  { id: 'back_squat',      sets: 4, reps: 6  },
  { id: 'rdl',             sets: 3, reps: 8  },
  { id: 'leg_press',       sets: 3, reps: 10 },
  { id: 'lying_leg_curl',  sets: 3, reps: 12 },
  { id: 'leg_ext',         sets: 3, reps: 12 },
  { id: 'calf_raise',      sets: 4, reps: 15 },
]

// ────────────────────────────────────────────────────────────────────────────
// Curated split library — v1.1 (6 splits)
// Ordered beginner-friendly first. The two intermediate-mid additions
// (ppl_3, bro_5) close the gaps the v1 lineup had: a casual 3-day PPL
// option and the culturally-required Bro Split for aesthetic-focused
// lifters.
// ────────────────────────────────────────────────────────────────────────────

export const PRESETS: Preset[] = [
  {
    id: 'full_body_2',
    name: 'Full Body · 2 days',
    meta: '2 days a week',
    lede: 'Minimalist. Highest stick-rate. ~80% of full-program gains for 40% of the time.',
    level: 'beginner',
    info: 'Two sessions a week, every major lift in each. Best for busy schedules, returning lifters, or anyone who wants the most adherence-friendly program. Hits chest, back, legs, and shoulders every session, so nothing is missed even if you only show up twice.',
    infoHighlights: [
      'Highest stick-rate program ever measured',
      'Two sessions cover every major muscle',
      '~80% of full-program gains for 40% the time',
    ],
    days: [
      { name: 'Full body A', type: 'HEAVY',    category: 'push', exercises: fullBodyA },
      { name: 'Rest',        type: 'RECOVERY', category: 'rest', exercises: [] },
      { name: 'Rest',        type: 'RECOVERY', category: 'rest', exercises: [] },
      { name: 'Full body B', type: 'VOLUME',   category: 'legs', exercises: fullBodyB },
      { name: 'Rest',        type: 'RECOVERY', category: 'rest', exercises: [] },
      { name: 'Rest',        type: 'RECOVERY', category: 'rest', exercises: [] },
      { name: 'Rest',        type: 'RECOVERY', category: 'rest', exercises: [] },
    ],
  },
  {
    id: 'full_body_3',
    name: 'Full Body · 3 days',
    meta: '3 days a week',
    lede: 'Every session hits everything. The novice classic, best for technique acquisition.',
    level: 'beginner',
    info: 'Three full-body sessions per week. Best for brand-new lifters learning the basics, or anyone who wants every muscle to recover and grow three times a week. Squat, bench, row, overhead press, and deadlift cycle through every session. Fast technique acquisition, simplest schedule to stick with.',
    infoHighlights: [
      'Every muscle trained 3× a week',
      'Squat, bench, row in every session',
      'Fastest technique acquisition for new lifters',
    ],
    days: [
      { name: 'Full body A', type: 'HEAVY',    category: 'push', exercises: fullBodyA },
      { name: 'Rest',        type: 'RECOVERY', category: 'rest', exercises: [] },
      { name: 'Full body B', type: 'VOLUME',   category: 'legs', exercises: fullBodyB },
      { name: 'Rest',        type: 'RECOVERY', category: 'rest', exercises: [] },
      { name: 'Full body A', type: 'HEAVY',    category: 'pull', exercises: fullBodyA },
      { name: 'Rest',        type: 'RECOVERY', category: 'rest', exercises: [] },
      { name: 'Rest',        type: 'RECOVERY', category: 'rest', exercises: [] },
    ],
  },
  {
    id: 'upper_lower_4',
    name: 'Upper / Lower',
    meta: '4 days a week',
    lede: 'The intermediate workhorse. Hits every muscle twice a week, the meta-analysis sweet spot.',
    level: 'intermediate',
    info: 'Two upper-body days plus two lower-body days. Best for intermediate lifters chasing both strength and size. Every muscle gets hit twice a week without the recovery cost of a 6-day split. The split most strength research is based on, and the safest "next step up" from full body.',
    infoHighlights: [
      'Every muscle trained 2× a week',
      'The Schoenfeld 2016 frequency sweet spot',
      'Strength + size in manageable sessions',
    ],
    days: [
      { name: 'Upper', type: 'HEAVY',    category: 'push', exercises: upperHeavy },
      { name: 'Lower', type: 'HEAVY',    category: 'legs', exercises: lowerHeavy },
      { name: 'Rest',  type: 'RECOVERY', category: 'rest', exercises: [] },
      { name: 'Upper', type: 'VOLUME',   category: 'push', exercises: upperVolume },
      { name: 'Lower', type: 'VOLUME',   category: 'legs', exercises: lowerVolume },
      { name: 'Rest',  type: 'RECOVERY', category: 'rest', exercises: [] },
      { name: 'Rest',  type: 'RECOVERY', category: 'rest', exercises: [] },
    ],
  },
  {
    id: 'ppl_3',
    name: 'Push Pull Legs · Classic',
    meta: '3 workouts on rotation · push, pull, legs, rest, repeat',
    lede: 'The classic PPL rotation. Push, pull, legs, rest, then repeat. Twice a week per muscle, no heavy/volume split.',
    level: 'intermediate',
    rotating: true,
    info: 'Push (chest, shoulders, triceps), Pull (back, biceps), Legs, then a rest day, and the 4-day cycle repeats. Best for lifters who want focused, single-purpose sessions and twice-weekly frequency per muscle. Lift three, rest one, on a loop — no calendar week. Your next session lands wherever the rotation puts you.',
    infoHighlights: [
      'Push, pull, legs, rest, then repeat',
      'Twice-weekly frequency per muscle',
      'Focused single-purpose sessions',
    ],
    // Three unique workout templates (Push / Pull / Legs) on a rotating
    // 4-day cycle: lift 3 days, rest 1, repeat. Lands ~6 lifting days per
    // calendar week, twice-weekly frequency per muscle. Every session at
    // HEAVY-style volume. No heavy/volume split (that is ppl_6's job).
    // The actual 4-day rotating cycle — push, pull, legs, rest — NOT a 7-day
    // expansion. Storing the week-padded 7 (P P L R P P L) was a bug: it made
    // the rotation repeat every 7 instead of every 4, drifting wrong, and the
    // customize screen showed 7 days when the card (and the whole point) is 4.
    days: [
      { name: 'Push',  type: 'HEAVY',    category: 'push', exercises: pushPPLClassic },
      { name: 'Pull',  type: 'HEAVY',    category: 'pull', exercises: pullPPLClassic },
      { name: 'Legs',  type: 'HEAVY',    category: 'legs', exercises: legsPPLClassic },
      { name: 'Rest',  type: 'RECOVERY', category: 'rest', exercises: [] },
    ],
  },
  {
    id: 'bro_5',
    name: 'Bro Split',
    meta: '5 days a week · chest / back / shoulders / arms / legs',
    lede: 'A body part a day. Highest per-session volume per muscle. The aesthetic-focused classic.',
    level: 'intermediate',
    info: 'One body part per day: chest Monday, back Tuesday, shoulders Wednesday, arms Thursday, legs Friday. Best for aesthetic-focused lifters who want the highest possible volume per muscle and the mental clarity of one job per session. Each muscle is trained once a week with high effort, and recovery is fully baked in.',
    infoHighlights: [
      'One body part per day, one focus per session',
      'Highest possible volume per muscle',
      'The classic aesthetic-focused split',
    ],
    days: [
      { name: 'Chest',     type: 'HEAVY',    category: 'push', exercises: broChest     },
      { name: 'Back',      type: 'HEAVY',    category: 'pull', exercises: broBack      },
      { name: 'Shoulders', type: 'HEAVY',    category: 'push', exercises: broShoulders },
      { name: 'Arms',      type: 'HEAVY',    category: 'pull', exercises: broArms      },
      { name: 'Legs',      type: 'HEAVY',    category: 'legs', exercises: broLegs      },
      { name: 'Rest',      type: 'RECOVERY', category: 'rest', exercises: []           },
      { name: 'Rest',      type: 'RECOVERY', category: 'rest', exercises: []           },
    ],
  },
  {
    id: 'ppl_6',
    name: 'Push Pull Legs · Heavy + Volume',
    meta: '6 days a week · heavy + volume rotation',
    lede: 'PPL with a heavy day and a volume day per movement. The advanced specialist version. Demanding, fastest size gains if you can recover.',
    level: 'advanced',
    info: 'Same PPL pattern as the classic, but each muscle gets a Heavy day (low reps, big compound lifts) and a Volume day (higher reps, more accessories) every week. Best for experienced lifters with the recovery capacity to handle six demanding sessions per week. High frequency, high volume, fastest size gains if you can sleep, eat, and train hard.',
    infoHighlights: [
      'Heavy day + Volume day per muscle',
      'Highest weekly volume of any preset',
      'Demands real recovery capacity',
    ],
    days: [
      { name: 'Push',  type: 'HEAVY',    category: 'push', exercises: pushHeavy },
      { name: 'Pull',  type: 'HEAVY',    category: 'pull', exercises: pullHeavy },
      { name: 'Legs',  type: 'HEAVY',    category: 'legs', exercises: legsHeavy },
      { name: 'Push',  type: 'VOLUME',   category: 'push', exercises: pushVolume },
      { name: 'Pull',  type: 'VOLUME',   category: 'pull', exercises: pullVolume },
      { name: 'Legs',  type: 'VOLUME',   category: 'legs', exercises: legsVolume },
      { name: 'Rest',  type: 'RECOVERY', category: 'rest', exercises: [] },
    ],
  },
  {
    id: 'blank',
    name: 'Start blank',
    meta: 'Build from scratch',
    days: [],
  },
]

// ────────────────────────────────────────────────────────────────────────────
// Recommendation engine
// ────────────────────────────────────────────────────────────────────────────
//
// 13 typed inputs across 4 chapters drive split selection + exercise
// selection + per-set RIR targets + a per-user diagnostic. Designed so
// reasoningBuilder() can be swapped to a Mentor LLM call later without
// changing the call site.
//
// v2 (2026-05-29): + formConfidence, movementPreference, failureTolerance.
// Sharpened experience (returning → back_recent / back_long).
// Merged outsideTraining + cardio → cardioAndOutside with modality.

/** Sharpened in v2: `returning` split into `back_recent` (off < 6mo, week-1
 *  deload only) and `back_long` (off 6+ mo, treated as `new` with a 2-week
 *  re-acclimate). Old `returning` saved drafts hydrate to `back_long`. */
export type Experience       = 'new' | 'some' | 'experienced' | 'back_recent' | 'back_long'

/** NEW v2 — confidence on the big barbell lifts. Drives whether the engine
 *  defaults primary slots to BB squat/bench/dead vs machine/DB equivalents. */
export type FormConfidence   = 'rock_solid' | 'getting_there' | 'still_learning' | 'skip_them'

/** NEW v2 — gym-floor preference for the implement family. Drives which
 *  variant gets picked when multiple candidates fill the same slot.
 *  Composes with formConfidence (a rock-solid + dumbbell user still gets
 *  heavy DB work, not forced BB) and equipment (gates the candidate pool). */
export type MovementPref     = 'barbell' | 'dumbbell' | 'machine' | 'cable' | 'mix'

/** NEW v2 — how hard the user wants to push each set. Drives the per-set
 *  RIR target stamped onto SetPill in the logger. `split` is the lifter
 *  who pushes isolations to failure but stays controlled on compounds. */
export type FailureTolerance = 'failure' | 'one_two' | 'three_plus' | 'split'

/** Goal options trimmed from 8 → 5 in BUILD20: `aesthetics` folded into
 *  `muscle` (same training implications), `bulk` and `athletic` removed
 *  as low-signal/rare (bulk is a diet question, athletic is its own product
 *  shape we don't serve yet). */
export type Goal             = 'strength' | 'muscle' | 'fat_loss' | 'recomp' | 'health'

/** v2 — merged outsideTraining + cardio. Modality matters: running and
 *  cycling overlap with leg day very differently. */
export type CardioAndOutside = 'desk' | 'walks' | 'sport' | 'running' | 'cycling' | 'cardio_first'

// Half-steps (2.5 = "2-3", 4.5 = "4-5", …) let someone who trains a variable
// number of days a week land honestly between two counts on the setup slider.
// They are a UX affordance only: recommendIntake() floors to a concrete
// integer count before choosing a split (the library is built on whole days).
export type Days             = 2 | 2.5 | 3 | 3.5 | 4 | 4.5 | 5 | 5.5 | 6 | 6.5 | 7
export type Session          = 'under_45' | '45_60' | '60_75' | '75_plus'
export type Equipment        = 'commercial' | 'home_full' | 'dumbbells' | 'bodyweight' | 'mix'
export type Restriction      = 'heavy_squat' | 'heavy_dl' | 'ohp' | 'heavy_pull' | 'explosive' | 'bench' | 'lower_back'
export type Recovery         = 'great' | 'okay' | 'stressed' | 'rough'

/** Body-part bias — multi-select (max 2). `balanced` is mutually exclusive
 *  with the rest. Drives reasoning + future exercise-emphasis logic. */
export type Priority         = 'chest' | 'back' | 'shoulders' | 'arms' | 'legs' | 'balanced'

/** How the user actually likes to train — the gym-floor preference signal.
 *  When set, overrides the research-optimal default in `recommendIntake()`
 *  (within day-count compatibility). `surprise_me` falls back to defaults. */
export type TrainingStyle    = 'one_body_part' | 'ppl' | 'upper_lower' | 'full_body' | 'surprise_me'

/** @deprecated v1 — replaced by Experience.back_recent / back_long. Old
 *  saved drafts still hydrate. */
export type ExperienceLegacy = 'returning'
/** @deprecated v1 — folded into CardioAndOutside. */
export type OutsideTraining  = 'none' | 'light' | 'sport' | 'cardio_primary'
/** @deprecated v1 — folded into CardioAndOutside. */
export type Cardio           = 'none' | 'a_little' | 'a_lot' | 'primary'
/** @deprecated — collected pre-BUILD20, no longer asked. Kept as optional
 *  so old saved drafts still type-check. */
export type CurrentProgram   = 'brand_new' | 'on_off' | 'doing_split' | 'structured'
/** @deprecated — collected pre-BUILD20, redundant with `goal`. */
export type BodyComp         = 'lose' | 'recomp' | 'lean_bulk' | 'neutral'

export interface IntakeAnswers {
  // Chapter 1 — where you are
  experience: Experience
  formConfidence: FormConfidence
  recovery: Recovery
  // Chapter 2 — what you want
  goal: Goal
  /** Body parts the user wants to bias toward. Empty array = no
   *  preference; `['balanced']` = explicitly even. Up to 2 specific
   *  parts otherwise. */
  priorities: Priority[]
  // Chapter 3 — how you train
  /** Training preference — single dominant signal for split selection. */
  style: TrainingStyle
  movementPreference: MovementPref
  failureTolerance: FailureTolerance
  days: Days
  session: Session
  equipment: Equipment
  // Chapter 4 — your body + life
  restrictions: Restriction[]
  cardioAndOutside: CardioAndOutside
  /** @deprecated kept for backward-compat with pre-BUILD20 saved drafts */
  currentProgram?: CurrentProgram
  /** @deprecated kept for backward-compat with pre-BUILD20 saved drafts */
  bodyComp?: BodyComp
}

/**
 * Backfill v1 saved intake answers (Supabase jsonb) into the v2 shape.
 *
 * Returning users who took the quiz before 2026-05-29 have records with
 * `outsideTraining`, `cardio`, `experience: 'returning'`, and no
 * formConfidence / movementPreference / failureTolerance fields. This
 * helper normalizes the shape at the page-server boundary so the rest of
 * the engine + UI only ever sees the v2 shape.
 *
 * Defaults match research-default behavior so the recommendation a
 * returning user sees stays stable until they re-take the quiz.
 */
export function hydrateIntakeAnswers(raw: unknown): IntakeAnswers | null {
  if (!raw || typeof raw !== 'object') return null
  const r = raw as Record<string, unknown>

  // experience — 'returning' → 'back_long' (conservative re-acclimate).
  const rawExp = r.experience as string | undefined
  const experience: Experience =
    rawExp === 'returning'   ? 'back_long'
    : rawExp === 'new'         ? 'new'
    : rawExp === 'some'        ? 'some'
    : rawExp === 'experienced' ? 'experienced'
    : rawExp === 'back_recent' ? 'back_recent'
    : rawExp === 'back_long'   ? 'back_long'
    : 'some'

  // cardioAndOutside — merge old cardio + outsideTraining. Order: if the
  // saved record already has cardioAndOutside (v2 user), use it. Else
  // derive from the v1 fields. `cardio: 'primary'` always wins → cardio_first.
  const rawCAO = r.cardioAndOutside as string | undefined
  const rawOT  = r.outsideTraining   as string | undefined
  const rawCar = r.cardio            as string | undefined
  const cardioAndOutside: CardioAndOutside =
    isCardioAndOutside(rawCAO)
      ? rawCAO
      : rawCar === 'primary' || rawOT === 'cardio_primary'
        ? 'cardio_first'
        : rawOT === 'sport'  ? 'sport'
        : rawOT === 'light'  ? 'walks'
        : rawOT === 'none'   ? 'desk'
        : 'desk'

  // formConfidence — default from experience. New users default to the
  // protective "still_learning"; experienced default to "rock_solid". Old
  // returners default to "getting_there" since muscle memory is real but
  // form may have rusted.
  const rawFC = r.formConfidence as string | undefined
  const formConfidence: FormConfidence =
    isFormConfidence(rawFC)
      ? rawFC
      : experience === 'new'         ? 'still_learning'
      : experience === 'some'        ? 'getting_there'
      : experience === 'experienced' ? 'rock_solid'
      : 'getting_there'

  // movementPreference — default to 'mix' (current engine behavior — no bias).
  const rawMP = r.movementPreference as string | undefined
  const movementPreference: MovementPref =
    isMovementPref(rawMP) ? rawMP : 'mix'

  // failureTolerance — default to 'one_two' (research default for hypertrophy,
  // matches the engine's pre-v2 implicit RIR 1-2 prescription).
  const rawFT = r.failureTolerance as string | undefined
  const failureTolerance: FailureTolerance =
    isFailureTolerance(rawFT) ? rawFT : 'one_two'

  // Remaining fields — straight pass-through with sane fallbacks.
  return {
    experience,
    formConfidence,
    recovery: (r.recovery as Recovery) ?? 'okay',
    goal: (r.goal as Goal) ?? 'muscle',
    priorities: Array.isArray(r.priorities) ? (r.priorities as Priority[]) : [],
    style: (r.style as TrainingStyle) ?? 'surprise_me',
    movementPreference,
    failureTolerance,
    days: (r.days as Days) ?? 4,
    session: (r.session as Session) ?? '45_60',
    equipment: (r.equipment as Equipment) ?? 'commercial',
    restrictions: Array.isArray(r.restrictions) ? (r.restrictions as Restriction[]) : [],
    cardioAndOutside,
    currentProgram: r.currentProgram as CurrentProgram | undefined,
    bodyComp:       r.bodyComp       as BodyComp       | undefined,
  }
}

function isCardioAndOutside(v: unknown): v is CardioAndOutside {
  return v === 'desk' || v === 'walks' || v === 'sport' || v === 'running' || v === 'cycling' || v === 'cardio_first'
}
function isFormConfidence(v: unknown): v is FormConfidence {
  return v === 'rock_solid' || v === 'getting_there' || v === 'still_learning' || v === 'skip_them'
}
function isMovementPref(v: unknown): v is MovementPref {
  return v === 'barbell' || v === 'dumbbell' || v === 'machine' || v === 'cable' || v === 'mix'
}
function isFailureTolerance(v: unknown): v is FailureTolerance {
  return v === 'failure' || v === 'one_two' || v === 'three_plus' || v === 'split'
}

export interface IntakeRecommendation {
  presetId: Preset['id']
  /** Full concatenated coach opener — kept for back-compat and as a
   *  fallback for any consumer that doesn't know about the structured
   *  parts below. The hero UI uses the parts so the headline / research
   *  backing / personal close can each get distinct visual treatment. */
  diagnostic: string
  /** Split name + frequency, the headline call ("Four days, Upper /
   *  Lower."). Renders as the big mint-serif headline on the hero. */
  diagnosticHeadline?: string
  /** Research backing for the split, plain prose. Renders under the
   *  headline as a muted caption. */
  diagnosticReason?: string
  /** The most-specific personal tie picked from intake answers (recovery,
   *  cardio, goal, override). Renders in the "★ FOR YOU" callout block
   *  under a divider so the personalization moment stands apart. */
  diagnosticPersonal?: string
  /** 3–6 short bulleted reasons, each mapping a specific answer to a
   *  programming choice. Kept for back-compat; the visual hero now uses
   *  `factors` for the per-answer card layout. */
  reasoning: string[]
  /** Structured "you said X → so we did Y" factor pairs, surfaced on
   *  the matched-split hero. Each factor is a category-coded chip
   *  showing the user's answer next to the engine's decision so the
   *  recommendation reads as actively tailored, not generic. Optional
   *  so older saved recommendations (pre-factors) still render — the
   *  UI falls back to `reasoning` bullets in that case. */
  factors?: RecommendationFactor[]
  /** When we steered the user away from what they asked for — e.g.
   *  they said 6 days but recovery is rough, so we recommend 4. The
   *  modal surfaces this prominently so the user can override. */
  daysOverride?: { requested: Days; recommended: Days; why: string }
}

/** Which question/signal a factor traces back to. Drives the small
 *  uppercase category tag in the UI. */
export type FactorCategory =
  | 'frequency'
  | 'goal'
  | 'style'
  | 'recovery'
  | 'priorities'
  | 'equipment'
  | 'restrictions'
  | 'cardio'
  | 'experience'
  | 'form_confidence'
  | 'movement_preference'
  | 'failure_tolerance'

export interface RecommendationFactor {
  category: FactorCategory
  /** Short label of the user's answer (≤ ~22 chars) — renders in the
   *  highlighted chip on the left side of the factor row. */
  answer: string
  /** Conversational sentence about what the engine did with that
   *  answer. Renders to the right of the arrow. */
  decision: string
}

/**
 * Recommend a split + diagnostic from the 11-question intake.
 *
 * Pipeline:
 *  1. Compute effective lifting days (start from `days`, subtract for
 *     outside-training fatigue + rough recovery).
 *  2. Pick a base split from (effective days × experience).
 *  3. Goal nudges the split at edges (strength keeps it on U/L over PPL).
 *  4. Goal-preferences correction layer — when the user has set their
 *     Vitality Goal (`outcome` + `window` + `constraint`), apply
 *     strategic overrides on top of the tactical intake decisions. Goal
 *     is the north star; intake is the logistics. See applyGoalCorrection.
 *  5. Build diagnostic + reasoning from the full answer set (including
 *     any Goal-driven overrides so the user sees why we steered them).
 */
export function recommendIntake(
  raw: IntakeAnswers,
  goal?: GoalPreferences | null,
): IntakeRecommendation {
  // A flexible pick like "4-5" resolves to its sustainable integer floor for
  // programming: the split library is built on concrete day counts, and a plan
  // you can always complete beats one you sometimes miss. The slider's
  // half-steps are purely a UX affordance, so everything below reasons over the
  // floored count (4.5 → 4) rather than the raw slider value.
  const a: IntakeAnswers = { ...raw, days: Math.floor(raw.days) as Days }

  // ── Effective lifting days ────────────────────────────────────────
  // A rough-recovery stretch, a sport, regular running, or cardio-as-the-
  // main-focus all spend the same weekly recovery budget lifting draws on, so
  // we cap the *effective* lifting days to a level that still recovers and
  // hand the user the honest reason (a HEADS UP note) rather than pretend
  // every requested day is free. Softer than v1: cardio-primary now lands on
  // a real 4-day split (Upper/Lower) instead of collapsing to a 3-day full
  // body, which is the case that read as "the quiz ignored me".
  let effective: Days = a.days
  let override: IntakeRecommendation['daysOverride'] | undefined

  const fatigueCap: Days | null =
    a.recovery === 'rough'                                               ? 4 :
    a.cardioAndOutside === 'cardio_first'                                ? 4 :
    (a.cardioAndOutside === 'sport' || a.cardioAndOutside === 'running') ? 5 :
    null
  if (fatigueCap !== null && a.days > fatigueCap) {
    effective = fatigueCap
    const why =
      a.recovery === 'rough'
        ? `recovery is rough right now, and ${a.days} days a week reliably under-recovers and stalls everything. ${fatigueCap} hard days protect your gains far better than ${a.days} half-recovered ones.`
      : a.cardioAndOutside === 'cardio_first'
        ? `cardio is your main focus, so we kept lifting to ${fatigueCap} days that complement it instead of competing for the same recovery.`
      : `${a.cardioAndOutside === 'running' ? 'regular running' : 'a sport that demands recovery'} already taxes your legs and recovery, so we capped lifting at ${fatigueCap} days to leave room for it.`
    override = { requested: a.days, recommended: fatigueCap, why }
  }

  // Note: `a.recovery === 'rough' && a.days <= 2` deliberately gets no
  // override. Two days a week is already conservative — overriding it
  // downward would mean recommending 1 day or 0, which isn't a program.
  // The reasoning bullet still flags the fatigue picture.

  // ── Base split — experience tier × effective days, shaped by goal and the
  //    user's explicit style pick. Rebuilt so every split is reachable for the
  //    lifter it actually suits (Upper/Lower for the 4-day intermediate, the
  //    bro split for the 5-day bodybuilder, heavy/volume PPL for the 6-day
  //    advanced specialist) instead of collapsing most inputs onto full body.
  //    Novices and an explicit full-body pick are the only paths that force
  //    full body; everyone else is differentiated by days, goal, and style.
  const buildForBeginner = a.experience === 'new' || a.experience === 'back_long'
  const advanced = a.experience === 'experienced'
  // The style the user actually chose (surprise_me = "you pick for me").
  const style = a.style && a.style !== 'surprise_me' ? a.style : null
  let presetId: Preset['id']

  if (buildForBeginner || style === 'full_body') {
    // Novices build the base on full-body frequency + technique reps no
    // matter how many days they can give — three quality full-body days beat
    // five sloppy specialized ones at this stage. Anyone who explicitly wants
    // full body gets it too. Day count only decides 2× vs 3×.
    presetId = effective <= 2 ? 'full_body_2' : 'full_body_3'
  } else if (effective <= 2) {
    // Two days can't feed a split — full body twice a week is the whole game.
    presetId = 'full_body_2'
  } else if (effective === 3) {
    // Three days: full body 3× hits every muscle at the top of Schoenfeld's
    // frequency curve. A 3-day PPL/U-L would drop most muscles to 1×/week.
    presetId = 'full_body_3'
  } else if (effective === 4) {
    // Four days: Upper/Lower is the research workhorse — every muscle twice a
    // week with a genuine recovery day between, and it serves size + strength.
    presetId = 'upper_lower_4'
  } else if (effective === 5) {
    // The bro split trains each muscle only ~1x/week; a 2x/week split beats it
    // for growth whenever one fits. So bro_5 is reserved for the lifter who
    // explicitly wants body-part-per-day (a chosen adherence tradeoff), and
    // the default 5-day hypertrophy plan is the PPL rotation (each muscle 2x).
    presetId =
      a.goal === 'strength'     ? 'upper_lower_4' : // heavy compounds want recovery; the 5th day is optional accessory work
      style === 'one_body_part' ? 'bro_5'         : // explicit body-part-split preference — 1x/week is a chosen tradeoff
      style === 'upper_lower'   ? 'upper_lower_4' : // honor the Upper/Lower preference
                                  'ppl_3'            // default: PPL rotation, ~2x/week per muscle
  } else {
    // Six or seven days — the top of the frequency range. (No distinct 7-day
    // preset: a 7th lifting day is just another turn of the rotation.)
    presetId =
      a.goal === 'strength'     ? 'upper_lower_4' : // strength still lives on U/L; extra days are optional
      style === 'upper_lower'   ? 'upper_lower_4' : // honor the Upper/Lower preference
      style === 'one_body_part' ? 'bro_5'         : // honor the body-part-split preference
      advanced                  ? 'ppl_6'         : // experienced + high frequency → heavy/volume PPL
                                  'ppl_3'            // intermediate hypertrophy → classic PPL rotation
  }

  // ── Session length veto ──────────────────────────────────────────
  // Under 45 min can't sustain the high-volume specialized splits —
  // downgrade to U/L (lower per-session volume, twice-a-week frequency).
  // Classic PPL (ppl_3, 6 sessions on rotation, no H/V split) still demands meaningful
  // per-session volume so it's vetoed too.
  if (a.session === 'under_45' && (presetId === 'ppl_6' || presetId === 'bro_5' || presetId === 'ppl_3')) {
    presetId = 'upper_lower_4'
  }

  // ── Restriction veto ─────────────────────────────────────────────
  // A user flagging `lower_back` can't sustain six lifting days of
  // posterior-chain work (ppl_6's pull days lead with heavy deadlift).
  // Even with the substitution pass in exerciseSelection.ts, the
  // frequency is rough on a restricted lower back. Downgrade to U/L
  // (one heavy lower day per week, easy to swap squats/DL for leg
  // press + lying-leg-curl). bro_5's leg day is similarly avoidable.
  if (a.restrictions.includes('lower_back') && (presetId === 'ppl_6' || presetId === 'bro_5')) {
    presetId = 'upper_lower_4'
  }

  // ── Goal correction layer ────────────────────────────────────────
  // The user's Vitality Goal is the north star; the intake handles the
  // tactical "how does this fit my life" details. When Goal disagrees
  // with the intake's choice on intent (cut vs bulk, longevity vs peak
  // volume), Goal wins and we collect a reasoning bullet so the user
  // sees why we steered. When they disagree on capacity (days, gear),
  // intake wins.
  const goalBullets: string[] = []
  if (goal) {
    const corrected = applyGoalCorrection(presetId, effective, a, goal)
    presetId = corrected.presetId
    goalBullets.push(...corrected.bullets)
    if (corrected.daysOverride) {
      // Goal-driven days override stacks on top of any earlier one. If
      // both exist, the later (Goal) note is more strategic — keep it.
      override = corrected.daysOverride
    }
  }

  const diagnosticHeadline = splitHeadline(presetId, a)
  const diagnosticReason   = splitReason(presetId, a)
  const diagnosticPersonal = personalClose(a, override, goal)
  // Combined string kept for back-compat with any consumer that doesn't
  // know about the structured parts. The hero UI now renders the parts
  // individually so each gets distinct visual weight.
  const diagnostic = `${diagnosticHeadline} ${diagnosticReason} ${diagnosticPersonal}`
  const reasoning  = buildReasoning(a, presetId, override, goalBullets)
  const factors    = buildFactors(a, presetId, override)

  return {
    presetId,
    diagnostic,
    diagnosticHeadline,
    diagnosticReason,
    diagnosticPersonal,
    reasoning,
    factors,
    daysOverride: override,
  }
}

/**
 * Goal-preferences correction layer. Runs after the intake decision tree
 * has picked a `presetId` and applied its own vetoes. Returns the
 * possibly-corrected split, plus any reasoning bullets explaining the
 * Goal-driven overrides (which `buildReasoning` weaves into the diagnostic
 * card so the user knows Goal is what changed things).
 *
 * Design intent — see brainstorm 2026-05-28: Goal owns *intent*
 * (cut/bulk/longevity), intake owns *capacity* (days, equipment,
 * restrictions). Goal corrections cap or shift the intake choice but
 * never override hard intake-stated capacity.
 */
function applyGoalCorrection(
  presetId: Preset['id'],
  effective: Days,
  a: IntakeAnswers,
  goal: GoalPreferences,
): {
  presetId: Preset['id']
  bullets: string[]
  daysOverride?: IntakeRecommendation['daysOverride']
} {
  const bullets: string[] = []
  let next = presetId
  let daysOverride: IntakeRecommendation['daysOverride'] | undefined

  const beginnerOrReturning = a.experience === 'new' || a.experience === 'back_long'

  // Rule 1 — cut + short window → cap to a recoverable 3-4 day split.
  // A calorie deficit eats recovery; high-frequency / high-volume splits
  // stall fast or actively cost muscle. We cap aggressively and tell the
  // user why.
  if (goal.outcome === 'cut' && (goal.window === '30' || goal.window === '60')) {
    if (next === 'ppl_6' || next === 'bro_5' || next === 'ppl_3') {
      const requestedDays = a.days
      const cappedDays: Days = effective >= 4 ? 4 : 3
      next = cappedDays === 4 ? 'upper_lower_4' : 'full_body_3'
      bullets.push(`You're cutting on a ${goal.window}-day window, and a deficit eats recovery. We capped this at ${cappedDays} days so you keep the muscle you're trying to lean out.`)
      if (cappedDays < requestedDays) {
        daysOverride = {
          requested: requestedDays,
          recommended: cappedDays,
          why: `you're cutting on a ${goal.window}-day window. Eating in a deficit means recovery is the scarce resource. ${cappedDays} hard lifting days protects the muscle you're trying to lean out far better than ${requestedDays} half-recovered ones.`,
        }
      }
    }
  }

  // Rule 2 — longevity outcome → joint-friendly, sustainable. Cap to
  // full body 2-3 day unless the user *explicitly* picked more days
  // through `style` (then we respect the agency).
  if (goal.outcome === 'longevity' && a.style !== 'one_body_part' && a.style !== 'ppl') {
    if (next === 'ppl_6' || next === 'bro_5' || next === 'ppl_3' || next === 'upper_lower_4') {
      const cappedDays: Days = effective >= 3 ? 3 : 2
      next = cappedDays === 3 ? 'full_body_3' : 'full_body_2'
      bullets.push(`Longevity-first goal means joint preservation and consistency over peak volume. We put you on a sustainable ${cappedDays}-day full-body rhythm you can run for decades.`)
      if (cappedDays < a.days) {
        daysOverride = {
          requested: a.days,
          recommended: cappedDays,
          why: `longevity-first training is about consistency over decades. ${cappedDays} sustainable days a week protect your joints and stick rate far better than ${a.days} aggressive ones.`,
        }
      }
    }
  }

  // Rule 3 — bulk + long window + no time pressure + intermediate+ → push
  // toward higher-frequency splits when days allow. Hypertrophy needs
  // frequency × volume; a long window earns the right to ramp.
  if (
    goal.outcome === 'bulk'
    && (goal.window === '90' || goal.window === '180' || goal.window === 'open')
    && goal.constraint !== 'time'
    && !beginnerOrReturning
    && effective >= 5
    && (next === 'upper_lower_4' || next === 'full_body_3')
  ) {
    next = a.experience === 'experienced' && effective >= 6 ? 'ppl_6' : 'ppl_3'
    bullets.push(`Building muscle on a ${goal.window === 'open' ? 'no-deadline' : `${goal.window}-day`} window means earning higher frequency. We moved you up to a PPL rotation so each muscle gets the volume it needs to grow.`)
  }

  // Rule 4 — constraint=injury → veto the two highest-volume / risk
  // splits regardless of what intake said.
  if (goal.constraint === 'injury' && (next === 'ppl_6' || next === 'bro_5')) {
    next = 'upper_lower_4'
    bullets.push('You flagged injury as the thing most likely to get in the way. We dropped you off the highest-volume splits so you have room to manage flare-ups.')
  }

  // Rule 5 — constraint=time → hard cap at a 4-day split. A user who said
  // "time is the constraint" can't sustain bro_5/ppl_6/ppl_3 long-term.
  if (goal.constraint === 'time' && (next === 'ppl_6' || next === 'bro_5' || next === 'ppl_3')) {
    next = 'upper_lower_4'
    bullets.push("Time is your constraint, so we kept this at four days max. Adherence to a split that fits beats the optimal split you skip.")
  }

  return { presetId: next, bullets, daysOverride }
}

// ────────────────────────────────────────────────────────────────────────────
// Diagnostic + reasoning generators
// ────────────────────────────────────────────────────────────────────────────
// Template-based for v1. The shape is intentionally simple so a future
// Mentor LLM call (passing the IntakeAnswers + chosen presetId) can drop
// in here without changing the call site.

function buildDiagnostic(
  a: IntakeAnswers,
  presetId: Preset['id'],
  override: IntakeRecommendation['daysOverride'],
  goal?: GoalPreferences | null,
): string {
  // Combined string form, kept here for any consumer that still wants
  // the concatenated diagnostic. The hero UI uses the three parts
  // (splitHeadline / splitReason / personalClose) directly.
  return `${splitHeadline(presetId, a)} ${splitReason(presetId, a)} ${personalClose(a, override, goal)}`
}

/** The split name as a confident one-line headline. No em dashes.
 *  This is what renders as the large mint-serif headline on the hero. */
function splitHeadline(presetId: Preset['id'], _a: IntakeAnswers): string {
  switch (presetId) {
    case 'full_body_2':   return `Two days, Full Body.`
    case 'full_body_3':   return `Three days, Full Body.`
    case 'upper_lower_4': return `Four days, Upper / Lower.`
    case 'ppl_3':         return `Push / Pull / Legs on rotation.`
    case 'bro_5':         return `Five days, one body part each.`
    case 'ppl_6':         return `Six days, PPL with heavy and volume rotation.`
    case 'blank':
    default:              return `Your custom split.`
  }
}

/** The research backing for the split, plain prose under the headline.
 *  Cites Schoenfeld landmarks where they earn their keep so the user
 *  reads the recommendation as evidence-backed. */
function splitReason(presetId: Preset['id'], a: IntakeAnswers): string {
  switch (presetId) {
    case 'full_body_2':
      return `The highest stick-rate program. Around 80% of full-program gains for 40% of the time.`
    case 'full_body_3':
      if (a.experience === 'new' || a.experience === 'back_long') {
        return `Every lift, three times a week. Fastest technique build at your level.`
      }
      return `Every muscle hit 3 times a week. Top of Schoenfeld's frequency curve.`
    case 'upper_lower_4':
      return `Every muscle hit twice a week. Schoenfeld 2016's sweet spot for hypertrophy.`
    case 'ppl_3':
      return `Twice-weekly per muscle on the calendar. No heavy or volume split.`
    case 'bro_5':
      return `Highest per-session volume per muscle. Focused, adherent, satisfying.`
    case 'ppl_6':
      return `Each muscle gets a heavy day and a volume day. The advanced specialist build.`
    case 'blank':
    default:
      return `Built around your own structure.`
  }
}

/** The personal tie. First matching rule wins so each user reads a
 *  sentence the engine actually authored for them. No em dashes. */
function personalClose(
  a: IntakeAnswers,
  override: IntakeRecommendation['daysOverride'],
  goal?: GoalPreferences | null,
): string {
  if (override) {
    return `You asked for ${override.requested}. We recommend ${override.recommended} so ${override.why}`
  }
  if (a.recovery === 'rough') {
    return `Recovery is rough, so volume is pulled back. Stay in the program. Don't dig a hole.`
  }
  if (a.recovery === 'stressed') {
    return `Recovery is running thin. Weekly volume capped under the textbook so stress doesn't compound.`
  }
  if (a.recovery === 'great' && (a.goal === 'muscle' || a.goal === 'recomp' || a.goal === 'strength')) {
    return `Sleep is solid. Volume climbs week over week as you adapt.`
  }
  if (a.cardioAndOutside === 'cardio_first' && a.goal === 'strength') {
    return `Cardio is your priority, so lifting days stay low. Heavy compounds keep fresh legs.`
  }
  // Goal — only when intake goal is meaningful and the goal-prefs
  // outcome didn't already speak (goalPrefs takes priority if set).
  if (goal) {
    return `Goal: ${goalOutcomeDescriptor(goal.outcome)}.`
  }
  switch (a.goal) {
    case 'strength':
      return `Heavy compounds lead. You build strength first.`
    case 'fat_loss':
      return `Volume stays high to protect muscle through the deficit.`
    case 'health':
      return `Light, recoverable, built to outlast burnout.`
    case 'recomp':
      return `Moderate volume and heavy compounds. Enough to grow, light enough to recover at maintenance.`
    case 'muscle':
      return `Compounds first, isolation in the back half. Hypertrophy rep ranges throughout.`
  }
}

function goalOutcomeDescriptor(o: GoalPreferences['outcome']): string {
  switch (o) {
    case 'cut':       return 'to lose fat while keeping muscle'
    case 'recomp':    return 'to lose fat and add muscle at once'
    case 'bulk':      return 'to build muscle and scale up'
    case 'maintain':  return 'to hold where you are and train consistently'
    case 'longevity': return 'to train for the long arc'
  }
}

function buildReasoning(
  a: IntakeAnswers,
  presetId: Preset['id'],
  override: IntakeRecommendation['daysOverride'],
  goalBullets: string[],
): string[] {
  const bullets: string[] = []

  // Days reasoning
  switch (presetId) {
    case 'full_body_2':
      bullets.push('Two sessions is the highest-stick-rate program, around 80% of full-program gains for 40% of the time')
      break
    case 'full_body_3':
      if (a.experience === 'new' || a.experience === 'back_long') {
        bullets.push('Three full-body sessions builds technique fastest at your experience level, every lift, three times a week')
      } else {
        bullets.push('Three full-body sessions hit each muscle 3× a week, top of Schoenfeld\'s frequency curve')
      }
      break
    case 'upper_lower_4':
      bullets.push('Four upper/lower sessions hit every muscle twice a week, the meta-analysis sweet spot for hypertrophy')
      break
    case 'ppl_3':
      bullets.push('Classic PPL: push, pull, legs, rest, then repeat. Three workouts on rotation, twice-weekly per muscle, no heavy/volume split')
      break
    case 'bro_5':
      bullets.push('Bro Split: one body part a day, highest per-session volume per muscle. Frequency once-a-week, but adherence + focus pay it back')
      break
    case 'ppl_6':
      bullets.push('PPL with heavy + volume rotation: each muscle gets a heavy day and a volume day. The advanced specialist version for years-experienced lifters chasing size')
      break
  }

  // Goal reasoning
  if (a.goal === 'muscle') {
    bullets.push('Muscle-first goal puts isolation work in the back half of every session, pumps after the compound work')
  } else if (a.goal === 'strength') {
    bullets.push('Strength goal means heavy compounds lead each day at 4 to 6 reps, accessories trail')
  } else if (a.goal === 'fat_loss') {
    bullets.push('Fat loss goal keeps volume high to protect muscle while you eat in a deficit')
  } else if (a.goal === 'recomp') {
    bullets.push('Recomp means moderate volume + heavy compounds: enough stimulus to grow, not so much you can\'t recover at maintenance calories')
  } else if (a.goal === 'health') {
    bullets.push('Health-first goal keeps the program light and recoverable so you don\'t burn out')
  }

  // Priority-driven reasoning — note when user picked specific body parts
  if (a.priorities && a.priorities.length > 0 && !a.priorities.includes('balanced')) {
    const names = a.priorities.map(prioritySingular).join(' + ')
    bullets.push(`You want to bias toward ${names}, so we add an extra accessory slot for those on every day they're hit`)
  }

  // Style-driven reasoning — only when user took an explicit preference
  if (a.style && a.style !== 'surprise_me') {
    bullets.push(stylePreferenceBullet(a.style))
  }

  // Restriction adjustments
  for (const r of a.restrictions) {
    bullets.push(restrictionBullet(r))
  }

  // Equipment-driven swap notes
  if (a.equipment === 'dumbbells') {
    bullets.push('Dumbbells only: we swap barbell compounds for DB equivalents (DB bench, DB row, RDL)')
  } else if (a.equipment === 'bodyweight') {
    bullets.push('Bodyweight only: your program leads with pull-ups, dips, push-ups, single-leg squat progressions')
  } else if (a.equipment === 'home_full') {
    bullets.push('Home gym with barbell + rack: full programming, no machine accessories')
  }

  // Recovery reasoning
  if (a.recovery === 'great') {
    bullets.push('Solid sleep + low stress means we can add volume week over week')
  } else if (a.recovery === 'rough' && override) {
    bullets.push(`Recovery override: ${override.why}`)
  } else if (a.recovery === 'stressed') {
    bullets.push('Stressed recovery means we cap weekly volume below the textbook prescription')
  }

  // Cardio + outside-training interaction
  if (a.cardioAndOutside === 'cardio_first' && a.goal === 'strength') {
    // Genuine conflict: cardio-first fatigues CNS + legs, strength demands
    // fresh heavy compounds. The engine already capped lifting days lower
    // (via the cardioAndOutside override path) — call it out so the user
    // knows we saw the trade-off.
    bullets.push('Cardio-first + strength goal is a trade-off. Heavy compounds want fresh legs, so we kept lifting days low so you can run them hard without the cardio stealing recovery')
  } else if (a.cardioAndOutside === 'cardio_first') {
    bullets.push('Cardio is primary, so lifting is structured to support it, not compete for recovery')
  } else if (a.cardioAndOutside === 'running' && (presetId === 'ppl_6' || presetId === 'bro_5' || presetId === 'upper_lower_4' || presetId === 'ppl_3')) {
    bullets.push('Regular runs share recovery with leg work, so we trimmed leg-day volume to keep both honest')
  } else if (a.cardioAndOutside === 'sport' && (presetId === 'ppl_6' || presetId === 'bro_5')) {
    bullets.push('A sport already eats into the weekly fatigue budget, so we kept lifting volume manageable so you can show up for both')
  }

  // Goal-correction bullets last so they read as the "and on top of that,
  // here's how your north star changed the call" punchline. Empty when
  // Goal wasn't set or none of its rules fired.
  bullets.push(...goalBullets)

  return bullets
}

// ────────────────────────────────────────────────────────────────────────────
// Helpers
// ────────────────────────────────────────────────────────────────────────────

function experiencePhrase(e: Experience): string {
  switch (e) {
    case 'new':          return 'New to lifting'
    case 'some':         return 'A year or two in'
    case 'experienced':  return 'Years of consistent training'
    case 'back_recent':  return 'Back at it after a short break'
    case 'back_long':    return 'Coming back after a long layoff'
  }
}

function goalDescriptor(g: Goal): string {
  switch (g) {
    case 'strength':    return 'to get stronger'
    case 'muscle':      return 'to build muscle'
    case 'fat_loss':    return 'to lose fat'
    case 'recomp':      return 'to recomp, both at once'
    case 'health':      return 'to stay healthy and active'
  }
}

function prioritySingular(p: Priority): string {
  switch (p) {
    case 'chest':     return 'chest'
    case 'back':      return 'back'
    case 'shoulders': return 'shoulders'
    case 'arms':      return 'arms'
    case 'legs':      return 'legs'
    case 'balanced':  return 'balanced development'
  }
}

function stylePreferenceBullet(s: TrainingStyle): string {
  switch (s) {
    case 'one_body_part': return 'You like body-part-per-day training, so we built around that even though the research favors twice-weekly frequency. Adherence to a split you actually like beats the optimal split you skip'
    case 'ppl':           return 'You like Push/Pull/Legs, so we honored the preference. Movement-pattern days keep the gym sessions clean and recoverable'
    case 'upper_lower':   return 'You like upper / lower, the meta-analysis sweet spot. Every muscle hit twice a week with manageable per-session volume'
    case 'full_body':     return 'You like full-body sessions: highest frequency per muscle, simplest schedule, hardest to skip without missing everything'
    case 'surprise_me':   return ''
  }
}

function splitDisplayName(p: Preset['id']): string {
  switch (p) {
    case 'full_body_2':   return 'Full Body 2-day'
    case 'full_body_3':   return 'Full Body 3-day'
    case 'upper_lower_4': return 'Upper/Lower 4-day'
    case 'ppl_3':         return 'Push/Pull/Legs Classic'
    case 'bro_5':         return 'Bro Split 5-day'
    case 'ppl_6':         return 'Push/Pull/Legs Heavy + Volume'
    case 'blank':         return 'a blank split'
  }
}

function restrictionsToPhrase(rs: Restriction[]): string {
  const labels = rs.map(restrictionShort)
  if (labels.length === 1) return labels[0]
  if (labels.length === 2) return `${labels[0]} or ${labels[1]}`
  return `${labels.slice(0, -1).join(', ')}, or ${labels[labels.length - 1]}`
}

function restrictionShort(r: Restriction): string {
  switch (r) {
    case 'heavy_squat':  return 'go heavy on squats'
    case 'heavy_dl':     return 'pull heavy off the floor'
    case 'ohp':          return 'press overhead'
    case 'heavy_pull':   return 'go heavy on pulls'
    case 'explosive':    return 'jump or train explosively'
    case 'bench':        return 'bench press'
    case 'lower_back':   return 'load the lower back'
  }
}

/** Compact noun form for the consolidated "what you're avoiding" factor card. */
function restrictionNoun(r: Restriction): string {
  switch (r) {
    case 'heavy_squat':  return 'heavy squats'
    case 'heavy_dl':     return 'deadlifts'
    case 'ohp':          return 'overhead press'
    case 'heavy_pull':   return 'heavy pulls'
    case 'explosive':    return 'explosive work'
    case 'bench':        return 'bench'
    case 'lower_back':   return 'lower-back load'
  }
}

function restrictionAdjustmentPhrase(rs: Restriction[]): string {
  if (rs.length === 0) return ''
  const swaps: string[] = []
  if (rs.includes('ohp'))         swaps.push('landmine press for OHP')
  if (rs.includes('heavy_squat')) swaps.push('leg press for back squat')
  if (rs.includes('heavy_dl'))    swaps.push('RDL for conventional deadlift')
  if (rs.includes('bench'))       swaps.push('DB floor press for bench')
  if (rs.includes('lower_back'))  swaps.push('chest-supported rows for bent-over')
  if (rs.includes('heavy_pull'))  swaps.push('lat pulldowns for pull-ups')
  if (rs.includes('explosive'))   swaps.push('controlled tempo for plyometric')
  if (swaps.length === 0) return ''
  return `, swapping in ${swaps.slice(0, 2).join(' and ')}${swaps.length > 2 ? ', and a few more' : ''} where they belong`
}

function restrictionBullet(r: Restriction): string {
  switch (r) {
    case 'heavy_squat':  return 'No heavy squatting. We substitute leg press and lunges for your quad work'
    case 'heavy_dl':     return 'No heavy deadlifts. RDL and hip thrust take the posterior-chain load'
    case 'ohp':          return 'No overhead pressing. Landmine press fills the role on your shoulder days'
    case 'heavy_pull':   return 'No heavy pulls. Lat pulldown and chest-supported row stay in'
    case 'explosive':    return 'No explosive work. Every lift is controlled-tempo'
    case 'bench':        return 'No bench pressing. DB floor press and machine chest take its place'
    case 'lower_back':   return 'No lower-back loading. RDLs become single-leg, deadlifts become trap-bar or off'
  }
}

// ────────────────────────────────────────────────────────────────────────
// Structured factor pairs — the visual "you said X → so we did Y" cards
// rendered on the matched-split hero. Built from the same signals
// buildReasoning inspects, but each factor stays a single answer/decision
// pair so the UI can render them as chip rows with a category tag.
// ────────────────────────────────────────────────────────────────────────

function buildFactors(
  a: IntakeAnswers,
  presetId: Preset['id'],
  override: IntakeRecommendation['daysOverride'],
): RecommendationFactor[] {
  const out: RecommendationFactor[] = []

  // Frequency / split-shape — always first; it's the structural decision.
  out.push(frequencyFactor(presetId, a, override))

  // Goal owns the intent layer.
  out.push(goalFactor(a))

  // Style preference — only when user took an explicit stance.
  if (a.style && a.style !== 'surprise_me') {
    out.push(styleFactor(a.style, presetId))
  }

  // Restrictions — the user's hard "do not", surfaced as ONE prominent card
  // right here near the top. A lifter who flagged lifts to avoid is trusting
  // us to honor that and wants to SEE it reflected; the old one-card-per-
  // restriction approach pushed them past the factor cap below, so someone who
  // hated five lifts saw none of them mentioned. (Empty = "Nothing" = no card.)
  if (a.restrictions.length > 0) {
    const nouns = a.restrictions.map(restrictionNoun)
    const summary = nouns.length <= 2
      ? `No ${nouns.join(' or ')}`
      : `No ${nouns.slice(0, 2).join(', ')} +${nouns.length - 2} more`
    out.push({
      category: 'restrictions',
      answer: summary,
      decision: `You told us to avoid ${nouns.join(', ')}. Every one is stripped from your plan and swapped for a joint-friendly lift that hits the same muscle. Not one of them shows up in a single day.`,
    })
  }

  // Priority bias — extra accessory slots on flagged body parts.
  if (a.priorities && a.priorities.length > 0 && !a.priorities.includes('balanced')) {
    const names = a.priorities.map(prioritySingular).join(' + ')
    out.push({
      category: 'priorities',
      answer: capitalizeWords(names),
      decision: `Extra accessory on flagged days. More volume where you asked.`,
    })
  }

  // Recovery — surfaces only when it actually shifted the program.
  if (a.recovery === 'great') {
    out.push({
      category: 'recovery',
      answer: 'Sleep solid',
      decision: `Volume climbs week over week. You've got the headroom.`,
    })
  } else if (a.recovery === 'stressed') {
    out.push({
      category: 'recovery',
      answer: 'Recovery stressed',
      decision: `Volume capped under the textbook. So you don't dig a hole.`,
    })
  } else if (a.recovery === 'rough') {
    out.push({
      category: 'recovery',
      answer: 'Recovery rough',
      decision: override?.why
        ?? `Volume pulled back. Program > burnout.`,
    })
  }

  // Cardio + outside training — note only when meaningful.
  if (a.cardioAndOutside === 'cardio_first') {
    out.push({
      category: 'cardio',
      answer: 'Cardio is primary',
      decision: a.goal === 'strength'
        ? `Lifting days kept low. Fresh legs for the cardio.`
        : `Lifting supports cardio. No recovery tug-of-war.`,
    })
  } else if (a.cardioAndOutside === 'running') {
    out.push({
      category: 'cardio',
      answer: 'Regular runs',
      decision: `Leg-day volume trimmed so running and lifting both stay honest.`,
    })
  } else if (a.cardioAndOutside === 'sport') {
    out.push({
      category: 'cardio',
      answer: 'A sport in the mix',
      decision: `Lifting volume left room for the sport's recovery cost.`,
    })
  }

  // Form confidence — surface when it actually changed the lift selection.
  if (a.formConfidence === 'skip_them') {
    out.push({
      category: 'form_confidence',
      answer: 'Skip the barbell lifts',
      decision: `Machines and dumbbells lead. No barbell squat, bench, or deadlift in primary slots.`,
    })
  } else if (a.formConfidence === 'still_learning') {
    out.push({
      category: 'form_confidence',
      answer: 'Still learning barbell',
      decision: `Machine and DB primaries with barbells as light skill work. Form before load.`,
    })
  } else if (a.formConfidence === 'rock_solid' && a.experience === 'experienced') {
    out.push({
      category: 'form_confidence',
      answer: 'Barbell rock solid',
      decision: `Advanced variations unlocked. Front squats, paused work, deficit pulls in rotation.`,
    })
  }

  // Movement preference — surface when the user actually leaned somewhere.
  if (a.movementPreference === 'barbell') {
    out.push({
      category: 'movement_preference',
      answer: 'Barbell first',
      decision: `Barbell variants picked first wherever they're on the menu.`,
    })
  } else if (a.movementPreference === 'dumbbell') {
    out.push({
      category: 'movement_preference',
      answer: 'Dumbbells feel best',
      decision: `DB press over BB bench, DB row over BB row. Dumbbell defaults across the board.`,
    })
  } else if (a.movementPreference === 'machine') {
    out.push({
      category: 'movement_preference',
      answer: 'Machines, dialed in',
      decision: `Hack squat, chest press, machine row lead. Locked-in patterns, less form tax.`,
    })
  } else if (a.movementPreference === 'cable') {
    out.push({
      category: 'movement_preference',
      answer: 'Cables and isolation',
      decision: `Cable row, cable fly, cable lateral, cable curl get the slot ahead of BB/DB peers.`,
    })
  }

  // Failure tolerance — drives the per-set RIR target the logger shows.
  if (a.failureTolerance === 'failure') {
    out.push({
      category: 'failure_tolerance',
      answer: 'Every set to failure',
      decision: `Per-set target lands at RIR 0–1. Every set counted.`,
    })
  } else if (a.failureTolerance === 'three_plus') {
    out.push({
      category: 'failure_tolerance',
      answer: 'Three reps in reserve',
      decision: `Per-set target lands at RIR 2–3. Quality reps, joint-friendly.`,
    })
  } else if (a.failureTolerance === 'split') {
    out.push({
      category: 'failure_tolerance',
      answer: 'Hard isolations, controlled compounds',
      decision: `Compounds at RIR 2–3, isolations at RIR 0–1. Smart fatigue management.`,
    })
  }

  // (Restrictions are surfaced as a single high-priority card up top — see
  //  above — so they never get truncated by the factor cap.)

  // Equipment — only when meaningfully constrained.
  if (a.equipment === 'dumbbells') {
    out.push({
      category: 'equipment',
      answer: 'Dumbbells only',
      decision: `DB bench, DB row, DB RDL. No barbell required.`,
    })
  } else if (a.equipment === 'bodyweight') {
    out.push({
      category: 'equipment',
      answer: 'Bodyweight only',
      decision: `Pull-ups, dips, single-leg progressions lead the program.`,
    })
  } else if (a.equipment === 'home_full') {
    out.push({
      category: 'equipment',
      answer: 'Home gym, barbell + rack',
      decision: `Full barbell programming. No machines needed.`,
    })
  }

  // Experience surfaces only for the edge cases that drove a different
  // split-pick (new + heavier preset, or experienced + advanced preset).
  if (a.experience === 'new' && presetId === 'full_body_3') {
    out.push({
      category: 'experience',
      answer: 'New to lifting',
      decision: `Full-body × 3. Fastest technique build at your level.`,
    })
  } else if (a.experience === 'back_long' && presetId === 'full_body_3') {
    out.push({
      category: 'experience',
      answer: 'Coming back after a long break',
      decision: `Full-body × 3 with a two-week re-acclimate. Muscle memory does the rest.`,
    })
  } else if (a.experience === 'back_recent') {
    out.push({
      category: 'experience',
      answer: 'Back after a short break',
      decision: `Same program you'd run at full strength, with week one deloaded 25%.`,
    })
  } else if (a.experience === 'experienced' && presetId === 'ppl_6') {
    out.push({
      category: 'experience',
      answer: 'Years in the gym',
      decision: `Heavy + volume rotation. Each muscle gets two intensities.`,
    })
  }

  // Cap so the hero doesn't get noisy. v2 raised this from 6 → 8 because
  // formConfidence + movementPreference + failureTolerance each earn a card
  // and we want them above the fold next to the structural decisions.
  // Deeper edge cases (rare experience flips, equipment caveats) still
  // live in the prose diagnostic / collapsible reasoning bullets.
  return out.slice(0, 8)
}

function frequencyFactor(
  presetId: Preset['id'],
  a: IntakeAnswers,
  override: IntakeRecommendation['daysOverride'],
): RecommendationFactor {
  const sessionsPerWeek = {
    full_body_2: 2, full_body_3: 3, upper_lower_4: 4,
    ppl_3: 3, bro_5: 5, ppl_6: 6, blank: 0,
  }[presetId]
  const askedTail = override ? ` (you asked for ${override.requested})` : ''
  switch (presetId) {
    case 'full_body_2':
      return {
        category: 'frequency',
        answer: `${sessionsPerWeek} days/week${askedTail}`,
        decision: `Highest stick-rate program. ~80% of full-program gains for 40% of the time.`,
      }
    case 'full_body_3':
      return {
        category: 'frequency',
        answer: `${sessionsPerWeek} days/week${askedTail}`,
        decision: a.experience === 'new' || a.experience === 'back_long'
          ? `Every lift, 3× a week. Fastest technique build at your level.`
          : `Every muscle 3× a week. Top of the Schoenfeld frequency curve.`,
      }
    case 'upper_lower_4':
      return {
        category: 'frequency',
        answer: `${sessionsPerWeek} days/week${askedTail}`,
        decision: `Twice-weekly per muscle. Schoenfeld 2016 sweet spot for hypertrophy.`,
      }
    case 'ppl_3':
      return {
        category: 'frequency',
        answer: `${sessionsPerWeek}-day PPL rotation${askedTail}`,
        decision: `Push / pull / legs / rest cycle. Twice-weekly per muscle on the calendar, no H/V split.`,
      }
    case 'bro_5':
      return {
        category: 'frequency',
        answer: `${sessionsPerWeek} days/week${askedTail}`,
        decision: `One body part per day. Highest per-session volume. Adherence + focus pay back the lower frequency.`,
      }
    case 'ppl_6':
      return {
        category: 'frequency',
        answer: `${sessionsPerWeek} days/week${askedTail}`,
        decision: `PPL with H/V rotation. Each muscle gets a heavy day and a volume day.`,
      }
    default:
      return {
        category: 'frequency',
        answer: `${sessionsPerWeek} days/week`,
        decision: `Custom split.`,
      }
  }
}

function goalFactor(a: IntakeAnswers): RecommendationFactor {
  switch (a.goal) {
    case 'muscle':
      return {
        category: 'goal',
        answer: 'Build muscle',
        decision: `Compounds first, isolation in the back half. Hypertrophy rep ranges throughout.`,
      }
    case 'strength':
      return {
        category: 'goal',
        answer: 'Get stronger',
        decision: `Heavy compounds lead. 4–6 reps, accessories trail.`,
      }
    case 'fat_loss':
      return {
        category: 'goal',
        answer: 'Lose fat',
        decision: `Volume stays high to protect muscle through the deficit.`,
      }
    case 'recomp':
      return {
        category: 'goal',
        answer: 'Recomp',
        decision: `Moderate volume + heavy compounds. Enough to grow, light enough to recover at maintenance.`,
      }
    case 'health':
      return {
        category: 'goal',
        answer: 'Stay healthy',
        decision: `Light, recoverable. Built to outlast burnout.`,
      }
  }
}

function styleFactor(s: TrainingStyle, presetId: Preset['id']): RecommendationFactor {
  const label: Record<TrainingStyle, string> = {
    one_body_part: 'Body-part-per-day',
    ppl: 'Push / Pull / Legs',
    upper_lower: 'Upper / Lower',
    full_body: 'Full-body sessions',
    surprise_me: 'Surprise me',
  }
  if (s === 'surprise_me') {
    return {
      category: 'style',
      answer: label.surprise_me,
      decision: `You left the split to us. We picked the research-optimal fit for your days and goal.`,
    }
  }
  // Which splits actually satisfy each stated style. If the chosen split is in
  // the list, we honored the pick; otherwise the science steered elsewhere and
  // we say so plainly — a factor that claimed "we held to your style" while
  // showing a different split is exactly what makes an engine feel dishonest.
  const honoredBy: Record<Exclude<TrainingStyle, 'surprise_me'>, Preset['id'][]> = {
    one_body_part: ['bro_5'],
    ppl:           ['ppl_3', 'ppl_6'],
    upper_lower:   ['upper_lower_4'],
    full_body:     ['full_body_2', 'full_body_3'],
  }
  if (honoredBy[s].includes(presetId)) {
    const affirm: Record<Exclude<TrainingStyle, 'surprise_me'>, string> = {
      one_body_part: `Your pick. We held to what you'll actually run, and adherence beats optimal.`,
      ppl:           `Your pick. Movement-pattern days: clean, recoverable, easy to plan.`,
      upper_lower:   `Your pick, and Schoenfeld's sweet spot. Twice-weekly per muscle, manageable per session.`,
      full_body:     `Your pick. Highest frequency, simplest schedule, hardest to skip.`,
    }
    return { category: 'style', answer: label[s], decision: affirm[s] }
  }
  const steered: Record<Exclude<TrainingStyle, 'surprise_me'>, string> = {
    one_body_part: `You lean body-part-per-day, but that needs 5+ days to cover everything. At your day count we started you on a higher-frequency split you can reshape toward one-part days in the next step.`,
    ppl:           `You lean PPL, but a true rotation needs 5-6 days to hit each muscle twice. At your day count we chose the closest fit that still holds the frequency. Reshape it in the next step.`,
    upper_lower:   `You lean Upper/Lower, but it needs 4 days to run right. At your day count we picked the split with better per-muscle frequency. Reshape it in the next step.`,
    full_body:     `You lean full-body sessions, and that's exactly what you're on.`,
  }
  return { category: 'style', answer: label[s], decision: steered[s] }
}

function restrictionLabel(r: Restriction): string {
  switch (r) {
    case 'heavy_squat':  return 'No heavy squats'
    case 'heavy_dl':     return 'No heavy deadlifts'
    case 'ohp':          return 'No overhead press'
    case 'heavy_pull':   return 'No heavy pulls'
    case 'explosive':    return 'No explosive work'
    case 'bench':        return 'No bench press'
    case 'lower_back':   return 'No lower-back load'
  }
}

function restrictionDecision(r: Restriction): string {
  switch (r) {
    case 'heavy_squat':  return 'Leg press and lunges take the quad work.'
    case 'heavy_dl':     return 'RDL and hip thrust take the posterior-chain load.'
    case 'ohp':          return 'Landmine press fills the role on shoulder days.'
    case 'heavy_pull':   return 'Lat pulldown and chest-supported row stay in.'
    case 'explosive':    return 'Every lift runs on controlled tempo.'
    case 'bench':        return 'DB floor press and machine chest take its place.'
    case 'lower_back':   return 'RDLs become single-leg, deadlifts become trap-bar or off.'
  }
}

function capitalizeWords(s: string): string {
  return s.replace(/\b\w/g, c => c.toUpperCase())
}

