// AUTO-GENERATED by scripts/build-exercise-references.mjs — do not hand-edit.
// Re-run the script when EX changes in app/app/fitness/log/splitData.ts.
// Distilled gist/steps/cues come from scripts/distill-exercise-references.mjs.
// Source: Free Exercise DB (https://github.com/yuhonas/free-exercise-db, public domain).

export interface ExerciseReference {
  freeDbId: string
  confidence: 'high' | 'medium' | 'low'
  images: string[]
  instructions: string[]
  primaryMuscles: string[]
  equipment: string
  // Build-time distilled summary — short, phone-readable. Optional so any
  // un-distilled entry still type-checks; the card falls back to instructions.
  gist?: string
  steps?: string[]
  cues?: string[]
}

export const exerciseReferences: Record<string, ExerciseReference> = {
  "ab_wheel": {
    "freeDbId": "Barbell_Ab_Rollout",
    "confidence": "medium",
    "images": [
      "/exercise-refs/ab_wheel/0.jpg",
      "/exercise-refs/ab_wheel/1.jpg"
    ],
    "instructions": [
      "For this exercise you will need to get into a pushup position, but instead of having your hands of the floor, you will be grabbing on to an Olympic barbell (loaded with 5-10 lbs on each side) instead. This will be your starting position.",
      "While keeping a slight arch on your back, lift your hips and roll the barbell towards your feet as you exhale. Tip: As you perform the movement, your glutes should be coming up, you should be keeping the abs tight and should maintain your back posture at all times. Also your arms should be staying perpendicular to the floor throughout the movement. If you don't, you will work out your shoulders and back more than the abs.",
      "After a second contraction at the top, start to roll the barbell back forward to the starting position slowly as you inhale.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "abdominals"
    ],
    "equipment": "barbell",
    "gist": "Barbell core rollout.",
    "steps": [
      "Pushup position on a light bar",
      "Roll the bar toward your feet",
      "Pause, then roll back out"
    ],
    "cues": [
      "Keep abs tight, back set",
      "Arms perpendicular to the floor"
    ]
  },
  "back_squat": {
    "freeDbId": "Barbell_Squat",
    "confidence": "high",
    "images": [
      "/exercise-refs/back_squat/0.jpg",
      "/exercise-refs/back_squat/1.jpg"
    ],
    "instructions": [
      "This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack to just below shoulder level. Once the correct height is chosen and the bar is loaded, step under the bar and place the back of your shoulders (slightly below the neck) across it.",
      "Hold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso.",
      "Step away from the rack and position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head up at all times and also maintain a straight back. This will be your starting position. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances discussed in the foot stances section).",
      "Begin to slowly lower the bar by bending the knees and hips as you maintain a straight posture with the head up. Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees. Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly.",
      "Begin to raise the bar as you exhale by pushing the floor with the heel of your foot as you straighten the legs again and go back to the starting position.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "quadriceps"
    ],
    "equipment": "barbell",
    "gist": "The barbell leg builder.",
    "steps": [
      "Bar on your upper back",
      "Sit down and back, chest up",
      "Drive through your heels"
    ],
    "cues": [
      "Knees track over your toes",
      "Chest up, back flat"
    ]
  },
  "bb_curl": {
    "freeDbId": "Barbell_Curl",
    "confidence": "high",
    "images": [
      "/exercise-refs/bb_curl/0.jpg",
      "/exercise-refs/bb_curl/1.jpg"
    ],
    "instructions": [
      "Stand up with your torso upright while holding a barbell at a shoulder-width grip. The palm of your hands should be facing forward and the elbows should be close to the torso. This will be your starting position.",
      "While holding the upper arms stationary, curl the weights forward while contracting the biceps as you breathe out. Tip: Only the forearms should move.",
      "Continue the movement until your biceps are fully contracted and the bar is at shoulder level. Hold the contracted position for a second and squeeze the biceps hard.",
      "Slowly begin to bring the bar back to starting position as your breathe in.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "biceps"
    ],
    "equipment": "barbell",
    "gist": "The barbell biceps builder.",
    "steps": [
      "Bar at shoulder width, palms up",
      "Curl up, elbows pinned",
      "Lower slow to the start"
    ],
    "cues": [
      "Upper arms stay still",
      "Only the forearms move"
    ]
  },
  "bb_row": {
    "freeDbId": "Bent_Over_Barbell_Row",
    "confidence": "medium",
    "images": [],
    "instructions": [
      "Hold a barbell with an overhand, roughly shoulder-width grip. Hinge at the hips until your torso is close to 45 degrees, back flat, knees soft, and let the bar hang at arm's length. This is your starting position.",
      "Pull the bar to your lower ribs by driving your elbows back and up, squeezing your shoulder blades together. Keep the bar close to your body and your torso still.",
      "Lower the bar under control back to arm's length. Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "middle back"
    ],
    "equipment": "barbell",
    "gist": "The barbell back builder.",
    "steps": [
      "Hinge over, flat back",
      "Pull the bar to your lower ribs",
      "Lower slow to arm's length"
    ],
    "cues": [
      "Drive your elbows back",
      "Squeeze your shoulder blades"
    ]
  },
  "bench_bb": {
    "freeDbId": "Barbell_Guillotine_Bench_Press",
    "confidence": "high",
    "images": [
      "/exercise-refs/bench_bb/0.jpg",
      "/exercise-refs/bench_bb/1.jpg"
    ],
    "instructions": [
      "Using a medium width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over your neck with your arms locked. This will be your starting position.",
      "As you breathe in, bring the bar down slowly until it is about 1 inch from your neck.",
      "After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your chest muscles. Lock your arms and squeeze your chest in the contracted position, hold for a second and then start coming down slowly again. It should take at least twice as long to go down than to come up.",
      "Repeat the movement for the prescribed amount of repetitions.",
      "When you are done, place the bar back in the rack."
    ],
    "primaryMuscles": [
      "chest"
    ],
    "equipment": "barbell",
    "gist": "The barbell chest builder.",
    "steps": [
      "Unrack over your chest",
      "Lower slow to your neck",
      "Press up and squeeze"
    ],
    "cues": [
      "Lower slower than you press",
      "Squeeze chest at lockout"
    ]
  },
  "bulgarian_ss": {
    "freeDbId": "Suspended_Split_Squat",
    "confidence": "medium",
    "images": [
      "/exercise-refs/bulgarian_ss/0.jpg",
      "/exercise-refs/bulgarian_ss/1.jpg"
    ],
    "instructions": [
      "Suspend your straps so the handles are 18-30 inches from the floor.",
      "Facing away from the setup, place your rear foot into the handle behind you. Keep your head looking forward and your chest up, with your knee slightly bent. This will be your starting position.",
      "Descend by flexing the knee and hips, lowering yourself to the ground. Keep your weight on the heel of your foot and maintain your posture throughout the exercise.",
      "At the bottom of the movement, reverse the motion, extending through the hip and knee to return to the starting position."
    ],
    "primaryMuscles": [
      "quadriceps"
    ],
    "equipment": "other",
    "gist": "Rear-foot-up quad builder.",
    "steps": [
      "Rear foot in the strap",
      "Drop into the front knee",
      "Drive back up"
    ],
    "cues": [
      "Weight on your front heel",
      "Chest up throughout"
    ]
  },
  "cable_crunch": {
    "freeDbId": "Cable_Crunch",
    "confidence": "high",
    "images": [
      "/exercise-refs/cable_crunch/0.jpg",
      "/exercise-refs/cable_crunch/1.jpg"
    ],
    "instructions": [
      "Kneel below a high pulley that contains a rope attachment.",
      "Grasp cable rope attachment and lower the rope until your hands are placed next to your face.",
      "Flex your hips slightly and allow the weight to hyperextend the lower back. This will be your starting position.",
      "With the hips stationary, flex the waist as you contract the abs so that the elbows travel towards the middle of the thighs. Exhale as you perform this portion of the movement and hold the contraction for a second.",
      "Slowly return to the starting position as you inhale. Tip: Make sure that you keep constant tension on the abs throughout the movement. Also, do not choose a weight so heavy that the lower back handles the brunt of the work.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "abdominals"
    ],
    "equipment": "cable",
    "gist": "Kneeling cable ab work.",
    "steps": [
      "Kneel, rope by your face",
      "Crunch elbows to thighs",
      "Return slow"
    ],
    "cues": [
      "Constant tension on abs",
      "Don't pull with low back"
    ]
  },
  "cable_curl": {
    "freeDbId": "Cable_Preacher_Curl",
    "confidence": "high",
    "images": [
      "/exercise-refs/cable_curl/0.jpg",
      "/exercise-refs/cable_curl/1.jpg"
    ],
    "instructions": [
      "Place a preacher bench about 2 feet in front of a pulley machine.",
      "Attach a straight bar to the low pulley.",
      "Sit at the preacher bench with your elbow and upper arms firmly on top of the bench pad and have someone hand you the bar from the low pulley.",
      "Grab the bar and fully extend your arms on top of the preacher bench pad. This will be your starting position.",
      "Now start pilling the weight up towards your shoulders and squeeze the biceps hard at the top of the movement. Exhale as you perform this motion. Also, hold for a second at the top.",
      "Now slowly lower the weight to the starting position.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "biceps"
    ],
    "equipment": "cable",
    "gist": "Cable preacher biceps curl.",
    "steps": [
      "Arms on the pad, bar extended",
      "Curl up to your shoulders",
      "Lower slow"
    ],
    "cues": [
      "Squeeze at the top",
      "Upper arms stay on pad"
    ]
  },
  "cable_fly": {
    "freeDbId": "Cable_Crossover",
    "confidence": "medium",
    "images": [],
    "instructions": [
      "Set both pulleys above head height and select the weight. Grasp a handle in each hand, step forward into a split stance, and open your arms out to the sides with a soft bend in the elbows, chest up. This is your starting position.",
      "Keeping the elbow bend fixed, bring both handles together in a wide arc in front of your chest, squeezing your chest at the middle.",
      "Slowly let your arms open back out to the starting stretch under control. Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "chest"
    ],
    "equipment": "cable",
    "gist": "The cable chest fly.",
    "steps": [
      "Pulleys high, soft elbow bend",
      "Sweep the handles together out front",
      "Open back out with control"
    ],
    "cues": [
      "Lead with your elbows, not hands",
      "Squeeze your chest at the middle"
    ]
  },
  "cable_lat_raise": {
    "freeDbId": "Cable_Seated_Lateral_Raise",
    "confidence": "high",
    "images": [
      "/exercise-refs/cable_lat_raise/0.jpg",
      "/exercise-refs/cable_lat_raise/1.jpg"
    ],
    "instructions": [
      "Stand in the middle of two low pulleys that are opposite to each other and place a flat bench right behind you (in perpendicular fashion to you; the narrow edge of the bench should be the one behind you). Select the weight to be used on each pulley.",
      "Now sit at the edge of the flat bench behind you with your feet placed in front of your knees.",
      "Bend forward while keeping your back flat and rest your torso on the thighs.",
      "Have someone give you the single handles attached to the pulleys. Grasp the left pulley with the right hand and the right pulley with the left after you select your weight. The pulleys should run under your knees and your arms will be extended with palms facing each other and a slight bend at the elbows. This will be the starting position.",
      "While keeping the arms stationary, raise the upper arms to the sides until they are parallel to the floor and at shoulder height. Exhale during the execution of this movement and hold the contraction for a second.",
      "Slowly lower your arms to the starting position as you inhale.",
      "Repeat for the recommended amount of repetitions. Tip: Maintain upper arms perpendicular to torso and a fixed elbow position (10 degree to 30 degree angle) throughout exercise."
    ],
    "primaryMuscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "gist": "Seated cable side-delt raise.",
    "steps": [
      "Sit between pulleys, cross grip",
      "Bend forward over thighs",
      "Raise arms out to sides"
    ],
    "cues": [
      "Arms perpendicular to torso",
      "Fixed slight elbow bend"
    ]
  },
  "calf_raise": {
    "freeDbId": "Seated_Calf_Raise",
    "confidence": "high",
    "images": [
      "/exercise-refs/calf_raise/0.jpg",
      "/exercise-refs/calf_raise/1.jpg"
    ],
    "instructions": [
      "Sit on the machine and place your toes on the lower portion of the platform provided with the heels extending off. Choose the toe positioning of your choice (forward, in, or out) as per the beginning of this chapter.",
      "Place your lower thighs under the lever pad, which will need to be adjusted according to the height of your thighs. Now place your hands on top of the lever pad in order to prevent it from slipping forward.",
      "Lift the lever slightly by pushing your heels up and release the safety bar. This will be your starting position.",
      "Slowly lower your heels by bending at the ankles until the calves are fully stretched. Inhale as you perform this movement.",
      "Raise the heels by extending the ankles as high as possible as you contract the calves and breathe out. Hold the top contraction for a second.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "calves"
    ],
    "equipment": "machine",
    "gist": "Seated machine calf builder.",
    "steps": [
      "Toes on platform, pad on thighs",
      "Lower heels for a stretch",
      "Press up high"
    ],
    "cues": [
      "Hold the top a second",
      "Full stretch at the bottom"
    ]
  },
  "chest_supp_row": {
    "freeDbId": "Dumbbell_Incline_Row",
    "confidence": "medium",
    "images": [
      "/exercise-refs/chest_supp_row/0.jpg",
      "/exercise-refs/chest_supp_row/1.jpg"
    ],
    "instructions": [
      "Using a neutral grip, lean into an incline bench.",
      "Take a dumbbell in each hand with a neutral grip, beginning with the arms straight. This will be your starting position.",
      "Retract the shoulder blades and flex the elbows to row the dumbbells to your side.",
      "Pause at the top of the motion, and then return to the starting position."
    ],
    "primaryMuscles": [
      "middle back"
    ],
    "equipment": "dumbbell",
    "gist": "Chest-supported upper-back row.",
    "steps": [
      "Lean into an incline bench",
      "Row dumbbells to your sides",
      "Pause, then lower"
    ],
    "cues": [
      "Neutral grip",
      "Squeeze blades at the top"
    ]
  },
  "close_grip": {
    "freeDbId": "Close-Grip_Barbell_Bench_Press",
    "confidence": "high",
    "images": [
      "/exercise-refs/close_grip/0.jpg",
      "/exercise-refs/close_grip/1.jpg"
    ],
    "instructions": [
      "Lie back on a flat bench. Using a close grip (around shoulder width), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.",
      "As you breathe in, come down slowly until you feel the bar on your middle chest. Tip: Make sure that - as opposed to a regular bench press - you keep the elbows close to the torso at all times in order to maximize triceps involvement.",
      "After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your triceps muscles. Lock your arms in the contracted position, hold for a second and then start coming down slowly again. Tip: It should take at least twice as long to go down than to come up.",
      "Repeat the movement for the prescribed amount of repetitions.",
      "When you are done, place the bar back in the rack."
    ],
    "primaryMuscles": [
      "triceps"
    ],
    "equipment": "barbell",
    "gist": "Close-grip triceps bench.",
    "steps": [
      "Unrack, shoulder-width grip",
      "Lower slow to mid chest",
      "Press up with triceps"
    ],
    "cues": [
      "Elbows close to your torso",
      "Lower slower than you press"
    ]
  },
  "conv_dl": {
    "freeDbId": "Barbell_Deadlift",
    "confidence": "high",
    "images": [
      "/exercise-refs/conv_dl/0.jpg",
      "/exercise-refs/conv_dl/1.jpg"
    ],
    "instructions": [
      "Stand in front of a loaded barbell.",
      "While keeping the back as straight as possible, bend your knees, bend forward and grasp the bar using a medium (shoulder width) overhand grip. This will be the starting position of the exercise. Tip: If it is difficult to hold on to the bar with this grip, alternate your grip or use wrist straps.",
      "While holding the bar, start the lift by pushing with your legs while simultaneously getting your torso to the upright position as you breathe out. In the upright position, stick your chest out and contract the back by bringing the shoulder blades back. Think of how the soldiers in the military look when they are in standing in attention.",
      "Go back to the starting position by bending at the knees while simultaneously leaning the torso forward at the waist while keeping the back straight. When the weights on the bar touch the floor you are back at the starting position and ready to perform another repetition.",
      "Perform the amount of repetitions prescribed in the program."
    ],
    "primaryMuscles": [
      "lower back"
    ],
    "equipment": "barbell",
    "gist": "The barbell pull builder.",
    "steps": [
      "Grip the bar, back flat",
      "Drive up and stand tall",
      "Hinge it back down"
    ],
    "cues": [
      "Back straight throughout",
      "Push the floor away"
    ]
  },
  "db_lat_raise": {
    "freeDbId": "Side_Lateral_Raise",
    "confidence": "medium",
    "images": [],
    "instructions": [
      "Stand tall with a dumbbell in each hand at your sides, palms facing in and a slight bend in the elbows. This is your starting position.",
      "Keeping your torso still, raise the dumbbells out to the sides until your arms are roughly parallel to the floor at shoulder height. Lead with your elbows and exhale as you lift.",
      "Lower the dumbbells slowly back to your sides. Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "shoulders"
    ],
    "equipment": "dumbbell",
    "gist": "The side-delt builder.",
    "steps": [
      "Dumbbells at your sides",
      "Raise out to shoulder height",
      "Lower slow, no swing"
    ],
    "cues": [
      "Lead with your elbows",
      "Keep your torso still"
    ]
  },
  "db_split_squat": {
    "freeDbId": "Dumbbell_Split_Squat",
    "confidence": "medium",
    "images": [],
    "instructions": [
      "Hold a dumbbell in each hand at your sides and stand in a split stance, one foot forward and one foot back, weight balanced between them, torso tall. This is your starting position.",
      "Lower straight down by bending both knees until your front thigh is about parallel to the floor and your back knee drops toward the ground. Keep your front knee tracking over your foot.",
      "Drive up through your front heel back to the start. Finish all reps, then switch legs. Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "quadriceps"
    ],
    "equipment": "dumbbell",
    "gist": "The single-leg quad builder.",
    "steps": [
      "Split stance, dumbbells at your sides",
      "Drop straight down, front thigh parallel",
      "Drive up through the front heel"
    ],
    "cues": [
      "Weight through your front heel",
      "Torso tall, front knee over foot"
    ]
  },
  "decline_situp": {
    "freeDbId": "Sit-Up",
    "confidence": "medium",
    "images": [
      "/exercise-refs/decline_situp/0.jpg",
      "/exercise-refs/decline_situp/1.jpg"
    ],
    "instructions": [
      "Lie down on the floor placing your feet either under something that will not move or by having a partner hold them. Your legs should be bent at the knees.",
      "Place your hands behind your head and lock them together by clasping your fingers. This is the starting position.",
      "Elevate your upper body so that it creates an imaginary V-shape with your thighs. Breathe out when performing this part of the exercise.",
      "Once you feel the contraction for a second, lower your upper body back down to the starting position while inhaling.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "abdominals"
    ],
    "equipment": "body only",
    "gist": "Bodyweight sit-up.",
    "steps": [
      "Feet anchored, knees bent",
      "Curl up toward thighs",
      "Lower slow"
    ],
    "cues": [
      "Hold the contraction a beat",
      "Control the way down"
    ]
  },
  "dips_weighted": {
    "freeDbId": "Dips_-_Triceps_Version",
    "confidence": "high",
    "images": [
      "/exercise-refs/dips_weighted/0.jpg",
      "/exercise-refs/dips_weighted/1.jpg"
    ],
    "instructions": [
      "To get into the starting position, hold your body at arm's length with your arms nearly locked above the bars.",
      "Now, inhale and slowly lower yourself downward. Your torso should remain upright and your elbows should stay close to your body. This helps to better focus on tricep involvement. Lower yourself until there is a 90 degree angle formed between the upper arm and forearm.",
      "Then, exhale and push your torso back up using your triceps to bring your body back to the starting position.",
      "Repeat the movement for the prescribed amount of repetitions."
    ],
    "primaryMuscles": [
      "triceps"
    ],
    "equipment": "body only",
    "gist": "Weighted triceps dip.",
    "steps": [
      "Hang at arm's length",
      "Lower to 90 degrees",
      "Press back up"
    ],
    "cues": [
      "Torso upright",
      "Elbows close to body"
    ]
  },
  "face_pull": {
    "freeDbId": "Face_Pull",
    "confidence": "high",
    "images": [
      "/exercise-refs/face_pull/0.jpg",
      "/exercise-refs/face_pull/1.jpg"
    ],
    "instructions": [
      "Facing a high pulley with a rope or dual handles attached, pull the weight directly towards your face, separating your hands as you do so. Keep your upper arms parallel to the ground."
    ],
    "primaryMuscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "gist": "Cable rear-delt pull.",
    "steps": [
      "Face a high pulley",
      "Pull to your face, hands apart",
      "Return slow"
    ],
    "cues": [
      "Upper arms parallel to floor"
    ]
  },
  "flat_db_press": {
    "freeDbId": "Dumbbell_Bench_Press",
    "confidence": "medium",
    "images": [],
    "instructions": [
      "Lie back on a flat bench with a dumbbell in each hand resting on your thighs, palms facing in. Kick the weights up and press them to arm's length above your chest, palms facing forward. This is your starting position.",
      "Lower the dumbbells slowly out to the sides of your chest until they are level with your ribs, elbows at roughly 45 degrees. Inhale as you lower.",
      "Press the dumbbells back up and together over your chest, exhaling. Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "chest"
    ],
    "equipment": "dumbbell",
    "gist": "The dumbbell chest builder.",
    "steps": [
      "Dumbbells pressed over your chest",
      "Lower slow to your ribs",
      "Press up and together"
    ],
    "cues": [
      "Lower slower than you press",
      "Elbows around 45 degrees"
    ]
  },
  "front_squat": {
    "freeDbId": "Front_Barbell_Squat",
    "confidence": "high",
    "images": [
      "/exercise-refs/front_squat/0.jpg",
      "/exercise-refs/front_squat/1.jpg"
    ],
    "instructions": [
      "This exercise is best performed inside a squat rack for safety purposes. To begin, first set the bar on a rack that best matches your height. Once the correct height is chosen and the bar is loaded, bring your arms up under the bar while keeping the elbows high and the upper arm slightly above parallel to the floor. Rest the bar on top of the deltoids and cross your arms while grasping the bar for total control.",
      "Lift the bar off the rack by first pushing with your legs and at the same time straightening your torso.",
      "Step away from the rack and position your legs using a shoulder width medium stance with the toes slightly pointed out. Keep your head up at all times as looking down will get you off balance and also maintain a straight back. This will be your starting position. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section).",
      "Begin to slowly lower the bar by bending the knees as you maintain a straight posture with the head up. Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees (which is the point in which the upper legs are below parallel to the floor). Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly.",
      "Begin to raise the bar as you exhale by pushing the floor mainly with the middle of your foot as you straighten the legs again and go back to the starting position.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "quadriceps"
    ],
    "equipment": "barbell",
    "gist": "Front-loaded quad squat.",
    "steps": [
      "Bar on front delts, elbows high",
      "Drop below parallel",
      "Drive up through midfoot"
    ],
    "cues": [
      "Elbows high, chest up",
      "Knees track over toes"
    ]
  },
  "hack_squat": {
    "freeDbId": "Hack_Squat",
    "confidence": "high",
    "images": [
      "/exercise-refs/hack_squat/0.jpg",
      "/exercise-refs/hack_squat/1.jpg"
    ],
    "instructions": [
      "Place the back of your torso against the back pad of the machine and hook your shoulders under the shoulder pads provided.",
      "Position your legs in the platform using a shoulder width medium stance with the toes slightly pointed out. Tip: Keep your head up at all times and also maintain the back on the pad at all times.",
      "Place your arms on the side handles of the machine and disengage the safety bars (which on most designs is done by moving the side handles from a facing front position to a diagonal position).",
      "Now straighten your legs without locking the knees. This will be your starting position. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section).",
      "Begin to slowly lower the unit by bending the knees as you maintain a straight posture with the head up (back on the pad at all times). Continue down until the angle between the upper leg and the calves becomes slightly less than 90-degrees (which is the point in which the upper legs are below parallel to the floor). Inhale as you perform this portion of the movement. Tip: If you performed the exercise correctly, the front of the knees should make an imaginary straight line with the toes that is perpendicular to the front. If your knees are past that imaginary line (if they are past your toes) then you are placing undue stress on the knee and the exercise has been performed incorrectly.",
      "Begin to raise the unit as you exhale by pushing the floor with mainly with the heel of your foot as you straighten the legs again and go back to the starting position.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "quadriceps"
    ],
    "equipment": "machine",
    "gist": "Machine quad squat.",
    "steps": [
      "Back on pad, feet on platform",
      "Drop below parallel",
      "Push through your heels"
    ],
    "cues": [
      "Head up, back on pad",
      "Knees track over toes"
    ]
  },
  "hammer_curl": {
    "freeDbId": "Alternate_Hammer_Curl",
    "confidence": "high",
    "images": [
      "/exercise-refs/hammer_curl/0.jpg",
      "/exercise-refs/hammer_curl/1.jpg"
    ],
    "instructions": [
      "Stand up with your torso upright and a dumbbell in each hand being held at arms length. The elbows should be close to the torso.",
      "The palms of the hands should be facing your torso. This will be your starting position.",
      "While holding the upper arm stationary, curl the right weight forward while contracting the biceps as you breathe out. Continue the movement until your biceps is fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second as you squeeze the biceps. Tip: Only the forearms should move.",
      "Slowly begin to bring the dumbbells back to starting position as your breathe in.",
      "Repeat the movement with the left hand. This equals one repetition.",
      "Continue alternating in this manner for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "gist": "Neutral-grip arm builder.",
    "steps": [
      "Dumbbells at sides, palms in",
      "Curl one up and squeeze",
      "Lower, then switch arms"
    ],
    "cues": [
      "Upper arms stay still",
      "Only the forearms move"
    ]
  },
  "hang_leg_raise": {
    "freeDbId": "Hanging_Leg_Raise",
    "confidence": "high",
    "images": [
      "/exercise-refs/hang_leg_raise/0.jpg",
      "/exercise-refs/hang_leg_raise/1.jpg"
    ],
    "instructions": [
      "Hang from a chin-up bar with both arms extended at arms length in top of you using either a wide grip or a medium grip. The legs should be straight down with the pelvis rolled slightly backwards. This will be your starting position.",
      "Raise your legs until the torso makes a 90-degree angle with the legs. Exhale as you perform this movement and hold the contraction for a second or so.",
      "Go back slowly to the starting position as you breathe in.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "abdominals"
    ],
    "equipment": "body only",
    "gist": "Hanging ab raise.",
    "steps": [
      "Hang, legs straight",
      "Raise legs to 90 degrees",
      "Lower slow"
    ],
    "cues": [
      "No swinging",
      "Control the descent"
    ]
  },
  "hip_thrust": {
    "freeDbId": "Barbell_Hip_Thrust",
    "confidence": "high",
    "images": [
      "/exercise-refs/hip_thrust/0.jpg",
      "/exercise-refs/hip_thrust/1.jpg"
    ],
    "instructions": [
      "Begin seated on the ground with a bench directly behind you. Have a loaded barbell over your legs. Using a fat bar or having a pad on the bar can greatly reduce the discomfort caused by this exercise.",
      "Roll the bar so that it is directly above your hips, and lean back against the bench so that your shoulder blades are near the top of it.",
      "Begin the movement by driving through your feet, extending your hips vertically through the bar. Your weight should be supported by your shoulder blades and your feet. Extend as far as possible, then reverse the motion to return to the starting position."
    ],
    "primaryMuscles": [
      "glutes"
    ],
    "equipment": "barbell",
    "gist": "Barbell glute builder.",
    "steps": [
      "Upper back on bench, bar on hips",
      "Drive hips up through the bar",
      "Lower to the start"
    ],
    "cues": [
      "Squeeze glutes at the top",
      "Weight on blades and feet"
    ]
  },
  "incl_bb_bench": {
    "freeDbId": "Barbell_Incline_Bench_Press_-_Medium_Grip",
    "confidence": "high",
    "images": [
      "/exercise-refs/incl_bb_bench/0.jpg",
      "/exercise-refs/incl_bb_bench/1.jpg"
    ],
    "instructions": [
      "Lie back on an incline bench. Using a medium-width grip (a grip that creates a 90-degree angle in the middle of the movement between the forearms and the upper arms), lift the bar from the rack and hold it straight over you with your arms locked. This will be your starting position.",
      "As you breathe in, come down slowly until you feel the bar on you upper chest.",
      "After a second pause, bring the bar back to the starting position as you breathe out and push the bar using your chest muscles. Lock your arms in the contracted position, squeeze your chest, hold for a second and then start coming down slowly again. Tip: it should take at least twice as long to go down than to come up.",
      "Repeat the movement for the prescribed amount of repetitions.",
      "When you are done, place the bar back in the rack."
    ],
    "primaryMuscles": [
      "chest"
    ],
    "equipment": "barbell",
    "gist": "Incline barbell upper-chest press.",
    "steps": [
      "Unrack over upper chest",
      "Lower slow to upper chest",
      "Press up and squeeze"
    ],
    "cues": [
      "Lower slower than you press",
      "Squeeze chest at lockout"
    ]
  },
  "incl_db_curl": {
    "freeDbId": "Incline_Dumbbell_Curl",
    "confidence": "high",
    "images": [
      "/exercise-refs/incl_db_curl/0.jpg",
      "/exercise-refs/incl_db_curl/1.jpg"
    ],
    "instructions": [
      "Sit back on an incline bench with a dumbbell in each hand held at arms length. Keep your elbows close to your torso and rotate the palms of your hands until they are facing forward. This will be your starting position.",
      "While holding the upper arm stationary, curl the weights forward while contracting the biceps as you breathe out. Only the forearms should move. Continue the movement until your biceps are fully contracted and the dumbbells are at shoulder level. Hold the contracted position for a second.",
      "Slowly begin to bring the dumbbells back to starting position as your breathe in.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "biceps"
    ],
    "equipment": "dumbbell",
    "gist": "Incline dumbbell biceps curl.",
    "steps": [
      "Lie back, arms hanging, palms forward",
      "Curl up to shoulders",
      "Lower slow"
    ],
    "cues": [
      "Upper arms stay still",
      "Only the forearms move"
    ]
  },
  "incl_db_press": {
    "freeDbId": "Incline_Dumbbell_Press",
    "confidence": "high",
    "images": [
      "/exercise-refs/incl_db_press/0.jpg",
      "/exercise-refs/incl_db_press/1.jpg"
    ],
    "instructions": [
      "Lie back on an incline bench with a dumbbell in each hand atop your thighs. The palms of your hands will be facing each other.",
      "Then, using your thighs to help push the dumbbells up, lift the dumbbells one at a time so that you can hold them at shoulder width.",
      "Once you have the dumbbells raised to shoulder width, rotate your wrists forward so that the palms of your hands are facing away from you. This will be your starting position.",
      "Be sure to keep full control of the dumbbells at all times. Then breathe out and push the dumbbells up with your chest.",
      "Lock your arms at the top, hold for a second, and then start slowly lowering the weight. Tip Ideally, lowering the weights should take about twice as long as raising them.",
      "Repeat the movement for the prescribed amount of repetitions.",
      "When you are done, place the dumbbells back on your thighs and then on the floor. This is the safest manner to release the dumbbells."
    ],
    "primaryMuscles": [
      "chest"
    ],
    "equipment": "dumbbell",
    "gist": "Incline dumbbell upper-chest press.",
    "steps": [
      "Dumbbells at shoulder width, palms forward",
      "Press up with your chest",
      "Lower slow"
    ],
    "cues": [
      "Lower slower than you press",
      "Stay in full control"
    ]
  },
  "lat_pulldown": {
    "freeDbId": "One_Arm_Lat_Pulldown",
    "confidence": "medium",
    "images": [
      "/exercise-refs/lat_pulldown/0.jpg",
      "/exercise-refs/lat_pulldown/1.jpg"
    ],
    "instructions": [
      "Select an appropriate weight and adjust the knee pad to help keep you down. Grasp the handle with a pronated grip. This will be your starting position.",
      "Pull the handle down, squeezing your elbow to your side as you flex the elbow.",
      "Pause at the bottom of the motion, and then slowly return the handle to the starting position.",
      "For multiple repetitions, avoid completely returning the weight to keep tension on the muscles being worked."
    ],
    "primaryMuscles": [
      "lats"
    ],
    "equipment": "cable",
    "gist": "One-arm lat pulldown.",
    "steps": [
      "Grip handle overhand",
      "Pull elbow to your side",
      "Return slow"
    ],
    "cues": [
      "Keep tension on the lats",
      "Drive the elbow down"
    ]
  },
  "leg_ext": {
    "freeDbId": "Single-Leg_Leg_Extension",
    "confidence": "high",
    "images": [
      "/exercise-refs/leg_ext/0.jpg",
      "/exercise-refs/leg_ext/1.jpg"
    ],
    "instructions": [
      "Seat yourself in the machine and adjust it so that you are positioned properly. The pad should be against the lower part of the shin but not in contact with the ankle. Adjust the seat so that the pivot point is in line with your knee. Select a weight appropriate for your abilities.",
      "Maintaining good posture, fully extend one leg, pausing at the top of the motion.",
      "Return to the starting position without letting the weight stop, keeping tension on the muscle.",
      "Repeat for the desired number of repetitions."
    ],
    "primaryMuscles": [
      "quadriceps"
    ],
    "equipment": "machine",
    "gist": "Single-leg quad extension.",
    "steps": [
      "Pad on lower shin",
      "Extend one leg fully",
      "Return without resting"
    ],
    "cues": [
      "Keep tension on the quad",
      "Pause at the top"
    ]
  },
  "leg_press": {
    "freeDbId": "Leg_Press",
    "confidence": "high",
    "images": [
      "/exercise-refs/leg_press/0.jpg",
      "/exercise-refs/leg_press/1.jpg"
    ],
    "instructions": [
      "Using a leg press machine, sit down on the machine and place your legs on the platform directly in front of you at a medium (shoulder width) foot stance. (Note: For the purposes of this discussion we will use the medium stance described above which targets overall development; however you can choose any of the three stances described in the foot positioning section).",
      "Lower the safety bars holding the weighted platform in place and press the platform all the way up until your legs are fully extended in front of you. Tip: Make sure that you do not lock your knees. Your torso and the legs should make a perfect 90-degree angle. This will be your starting position.",
      "As you inhale, slowly lower the platform until your upper and lower legs make a 90-degree angle.",
      "Pushing mainly with the heels of your feet and using the quadriceps go back to the starting position as you exhale.",
      "Repeat for the recommended amount of repetitions and ensure to lock the safety pins properly once you are done. You do not want that platform falling on you fully loaded."
    ],
    "primaryMuscles": [
      "quadriceps"
    ],
    "equipment": "machine",
    "gist": "Machine quad press.",
    "steps": [
      "Feet shoulder width on platform",
      "Lower to 90 degrees",
      "Push through your heels"
    ],
    "cues": [
      "Don't lock your knees",
      "Lock the pins when done"
    ]
  },
  "lying_leg_curl": {
    "freeDbId": "Ball_Leg_Curl",
    "confidence": "medium",
    "images": [
      "/exercise-refs/lying_leg_curl/0.jpg",
      "/exercise-refs/lying_leg_curl/1.jpg"
    ],
    "instructions": [
      "Begin on the floor laying on your back with your feet on top of the ball.",
      "Position the ball so that when your legs are extended your ankles are on top of the ball. This will be your starting position.",
      "Raise your hips off of the ground, keeping your weight on the shoulder blades and your feet.",
      "Flex the knees, pulling the ball as close to you as you can, contracting the hamstrings.",
      "After a brief pause, return to the starting position."
    ],
    "primaryMuscles": [
      "hamstrings"
    ],
    "equipment": "exercise ball",
    "gist": "Ball hamstring curl.",
    "steps": [
      "Heels on ball, hips up",
      "Curl ball toward you",
      "Return slow"
    ],
    "cues": [
      "Keep your hips lifted",
      "Squeeze hams at the top"
    ]
  },
  "machine_chest": {
    "freeDbId": "Machine_Bench_Press",
    "confidence": "high",
    "images": [
      "/exercise-refs/machine_chest/0.jpg",
      "/exercise-refs/machine_chest/1.jpg"
    ],
    "instructions": [
      "Sit down on the Chest Press Machine and select the weight.",
      "Step on the lever provided by the machine since it will help you to bring the handles forward so that you can grab the handles and fully extend the arms.",
      "Grab the handles with a palms-down grip and lift your elbows so that your upper arms are parallel to the floor to the sides of your torso. Tip: Your forearms will be pointing forward since you are grabbing the handles. Once you bring the handles forward and extend the arms you will be at the starting position.",
      "Now bring the handles back towards you as you breathe in.",
      "Push the handles away from you as you flex your pecs and you breathe out. Hold the contraction for a second before going back to the starting position.",
      "Repeat for the recommended amount of reps.",
      "When finished step on the lever again and slowly get the handles back to their original place."
    ],
    "primaryMuscles": [
      "chest"
    ],
    "equipment": "machine",
    "gist": "Machine chest press.",
    "steps": [
      "Upper arms parallel, palms down",
      "Press the handles out",
      "Return slow"
    ],
    "cues": [
      "Hold the squeeze a beat",
      "Back flat on the pad"
    ]
  },
  "machine_ohp": {
    "freeDbId": "Smith_Machine_Overhead_Shoulder_Press",
    "confidence": "high",
    "images": [
      "/exercise-refs/machine_ohp/0.jpg",
      "/exercise-refs/machine_ohp/1.jpg"
    ],
    "instructions": [
      "To begin, place a flat bench (or preferably one with back support) underneath a smith machine. Position the barbell at a height so that when seated on the flat bench, the arms must be almost fully extended to reach the barbell.",
      "Once you have the correct height, sit slightly in behind the barbell so that there is an imaginary straight line from the tip of your nose to the barbell. Your feet should be stationary. Grab the barbell with the palms facing forward, unlock it and lift it up so that your arms are fully extended. This is the starting position.",
      "Slowly begin to lower the barbell until it is level with your chin while inhaling.",
      "Then lift the barbell back to the starting position using your shoulders while exhaling.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "shoulders"
    ],
    "equipment": "machine",
    "gist": "Smith machine shoulder press.",
    "steps": [
      "Sit, bar lined up with your nose",
      "Lower to chin level",
      "Press back up"
    ],
    "cues": [
      "Feet planted",
      "Press straight overhead"
    ]
  },
  "oh_tri_ext": {
    "freeDbId": "Cable_Rope_Overhead_Triceps_Extension",
    "confidence": "high",
    "images": [
      "/exercise-refs/oh_tri_ext/0.jpg",
      "/exercise-refs/oh_tri_ext/1.jpg"
    ],
    "instructions": [
      "Attach a rope to the bottom pulley of the pulley machine.",
      "Grasping the rope with both hands, extend your arms with your hands directly above your head using a neutral grip (palms facing each other). Your elbows should be in close to your head and the arms should be perpendicular to the floor with the knuckles aimed at the ceiling. This will be your starting position.",
      "Slowly lower the rope behind your head as you hold the upper arms stationary. Inhale as you perform this movement and pause when your triceps are fully stretched.",
      "Return to the starting position by flexing your triceps as you breathe out.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "triceps"
    ],
    "equipment": "cable",
    "gist": "Overhead cable triceps extension.",
    "steps": [
      "Rope overhead, elbows in",
      "Lower behind your head",
      "Extend back up"
    ],
    "cues": [
      "Upper arms stay still",
      "Full stretch at the bottom"
    ]
  },
  "pec_deck": {
    "freeDbId": "Butterfly",
    "confidence": "high",
    "images": [
      "/exercise-refs/pec_deck/0.jpg",
      "/exercise-refs/pec_deck/1.jpg"
    ],
    "instructions": [
      "Sit on the machine with your back flat on the pad.",
      "Take hold of the handles. Tip: Your upper arms should be positioned parallel to the floor; adjust the machine accordingly. This will be your starting position.",
      "Push the handles together slowly as you squeeze your chest in the middle. Breathe out during this part of the motion and hold the contraction for a second.",
      "Return back to the starting position slowly as you inhale until your chest muscles are fully stretched.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "chest"
    ],
    "equipment": "machine",
    "gist": "Machine chest fly.",
    "steps": [
      "Back flat, grip handles",
      "Push together, squeeze chest",
      "Return for a stretch"
    ],
    "cues": [
      "Upper arms parallel to floor",
      "Squeeze in the middle"
    ]
  },
  "pendlay_row": {
    "freeDbId": "Bent_Over_Barbell_Row",
    "confidence": "high",
    "images": [
      "/exercise-refs/pendlay_row/0.jpg",
      "/exercise-refs/pendlay_row/1.jpg"
    ],
    "instructions": [
      "Holding a barbell with a pronated grip (palms facing down), bend your knees slightly and bring your torso forward, by bending at the waist, while keeping the back straight until it is almost parallel to the floor. Tip: Make sure that you keep the head up. The barbell should hang directly in front of you as your arms hang perpendicular to the floor and your torso. This is your starting position.",
      "Now, while keeping the torso stationary, breathe out and lift the barbell to you. Keep the elbows close to the body and only use the forearms to hold the weight. At the top contracted position, squeeze the back muscles and hold for a brief pause.",
      "Then inhale and slowly lower the barbell back to the starting position.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "middle back"
    ],
    "equipment": "barbell",
    "gist": "Bent-over barbell back row.",
    "steps": [
      "Bend to near parallel, grip overhand",
      "Row the bar to you",
      "Lower slow"
    ],
    "cues": [
      "Back straight, head up",
      "Keep the torso still"
    ]
  },
  "plank": {
    "freeDbId": "Plank",
    "confidence": "high",
    "images": [
      "/exercise-refs/plank/0.jpg",
      "/exercise-refs/plank/1.jpg"
    ],
    "instructions": [
      "Get into a prone position on the floor, supporting your weight on your toes and your forearms. Your arms are bent and directly below the shoulder.",
      "Keep your body straight at all times, and hold this position as long as possible. To increase difficulty, an arm or leg can be raised."
    ],
    "primaryMuscles": [
      "abdominals"
    ],
    "equipment": "body only",
    "gist": "Core stability hold.",
    "steps": [
      "Forearms and toes down",
      "Body in a straight line",
      "Hold as long as you can"
    ],
    "cues": [
      "No sagging hips",
      "Raise a limb to progress"
    ]
  },
  "preacher_curl": {
    "freeDbId": "Preacher_Curl",
    "confidence": "high",
    "images": [
      "/exercise-refs/preacher_curl/0.jpg",
      "/exercise-refs/preacher_curl/1.jpg"
    ],
    "instructions": [
      "To perform this movement you will need a preacher bench and an E-Z bar. Grab the E-Z curl bar at the close inner handle (either have someone hand you the bar which is preferable or grab the bar from the front bar rest provided by most preacher benches). The palm of your hands should be facing forward and they should be slightly tilted inwards due to the shape of the bar.",
      "With the upper arms positioned against the preacher bench pad and the chest against it, hold the E-Z Curl Bar at shoulder length. This will be your starting position.",
      "As you breathe in, slowly lower the bar until your upper arm is extended and the biceps is fully stretched.",
      "As you exhale, use the biceps to curl the weight up until your biceps is fully contracted and the bar is at shoulder height. Squeeze the biceps hard and hold this position for a second.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "biceps"
    ],
    "equipment": "barbell",
    "gist": "Preacher biceps curl.",
    "steps": [
      "Arms on the pad, bar up",
      "Lower to a full stretch",
      "Curl up and squeeze"
    ],
    "cues": [
      "Upper arms stay on pad",
      "Squeeze a beat at the top"
    ]
  },
  "pullup": {
    "freeDbId": "Weighted_Pull_Ups",
    "confidence": "medium",
    "images": [
      "/exercise-refs/pullup/0.jpg",
      "/exercise-refs/pullup/1.jpg"
    ],
    "instructions": [
      "Attach a weight to a dip belt and secure it around your waist. Grab the pull-up bar with the palms of your hands facing forward. For a medium grip, your hands should be spaced at shoulder width. Both arms should be extended in front of you holding the bar at the chosen grip.",
      "You'll want to bring your torso back about 30 degrees while creating a curvature in your lower back and sticking your chest out. This will be your starting position.",
      "Now, exhale and pull your torso up until your head is above your hands. Concentrate on squeezing yourshoulder blades back and down as you reach the top contracted position.",
      "After a brief moment at the top contracted position, inhale and slowly lower your torso back to the starting position with your arms extended and your lats fully stretched."
    ],
    "primaryMuscles": [
      "lats"
    ],
    "equipment": "other",
    "gist": "Bodyweight lat builder.",
    "steps": [
      "Grip overhand, shoulder width",
      "Pull chin above the bar",
      "Lower to a full hang"
    ],
    "cues": [
      "Drive blades down and back",
      "Full lat stretch at bottom"
    ]
  },
  "pullup_weighted": {
    "freeDbId": "Weighted_Pull_Ups",
    "confidence": "high",
    "images": [
      "/exercise-refs/pullup_weighted/0.jpg",
      "/exercise-refs/pullup_weighted/1.jpg"
    ],
    "instructions": [
      "Attach a weight to a dip belt and secure it around your waist. Grab the pull-up bar with the palms of your hands facing forward. For a medium grip, your hands should be spaced at shoulder width. Both arms should be extended in front of you holding the bar at the chosen grip.",
      "You'll want to bring your torso back about 30 degrees while creating a curvature in your lower back and sticking your chest out. This will be your starting position.",
      "Now, exhale and pull your torso up until your head is above your hands. Concentrate on squeezing yourshoulder blades back and down as you reach the top contracted position.",
      "After a brief moment at the top contracted position, inhale and slowly lower your torso back to the starting position with your arms extended and your lats fully stretched."
    ],
    "primaryMuscles": [
      "lats"
    ],
    "equipment": "other",
    "gist": "Weighted lat builder.",
    "steps": [
      "Weight on belt, overhand grip",
      "Pull chin above the bar",
      "Lower to a full hang"
    ],
    "cues": [
      "Drive blades down and back",
      "Full lat stretch at bottom"
    ]
  },
  "push_press": {
    "freeDbId": "Push_Press",
    "confidence": "high",
    "images": [
      "/exercise-refs/push_press/0.jpg",
      "/exercise-refs/push_press/1.jpg"
    ],
    "instructions": [],
    "primaryMuscles": [
      "shoulders"
    ],
    "equipment": "barbell",
    "gist": "Leg-driven overhead press.",
    "steps": [
      "Bar racked at shoulders",
      "Dip, then drive up",
      "Press overhead to lockout"
    ],
    "cues": [
      "Start the drive with legs",
      "Lock out over your head"
    ]
  },
  "rdl": {
    "freeDbId": "Romanian_Deadlift",
    "confidence": "high",
    "images": [
      "/exercise-refs/rdl/0.jpg",
      "/exercise-refs/rdl/1.jpg"
    ],
    "instructions": [
      "Put a barbell in front of you on the ground and grab it using a pronated (palms facing down) grip that a little wider than shoulder width. Tip: Depending on the weight used, you may need wrist wraps to perform the exercise and also a raised platform in order to allow for better range of motion.",
      "Bend the knees slightly and keep the shins vertical, hips back and back straight. This will be your starting position.",
      "Keeping your back and arms completely straight at all times, use your hips to lift the bar as you exhale. Tip: The movement should not be fast but steady and under control.",
      "Once you are standing completely straight up, lower the bar by pushing the hips back, only slightly bending the knees, unlike when squatting. Tip: Take a deep breath at the start of the movement and keep your chest up. Hold your breath as you lower and exhale as you complete the movement.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "hamstrings"
    ],
    "equipment": "barbell",
    "gist": "Romanian hamstring builder.",
    "steps": [
      "Grip bar, shins vertical",
      "Hinge hips back, bar close",
      "Drive hips to stand"
    ],
    "cues": [
      "Back and arms straight",
      "Chest up, move steady"
    ]
  },
  "rear_delt_fly": {
    "freeDbId": "Cable_Rear_Delt_Fly",
    "confidence": "high",
    "images": [
      "/exercise-refs/rear_delt_fly/0.jpg",
      "/exercise-refs/rear_delt_fly/1.jpg"
    ],
    "instructions": [
      "Adjust the pulleys to the appropriate height and adjust the weight. The pulleys should be above your head.",
      "Grab the left pulley with your right hand and the right pulley with your left hand, crossing them in front of you. This will be your starting position.",
      "Initiate the movement by moving your arms back and outward, keeping your arms straight as you execute the movement.",
      "Pause at the end of the motion before returning the handles to the start position."
    ],
    "primaryMuscles": [
      "shoulders"
    ],
    "equipment": "cable",
    "gist": "Cable rear-delt fly.",
    "steps": [
      "Cross grip, pulleys high",
      "Pull arms back and out",
      "Return slow"
    ],
    "cues": [
      "Keep arms straight",
      "Motion from the shoulders"
    ]
  },
  "reverse_pec": {
    "freeDbId": "Reverse_Machine_Flyes",
    "confidence": "high",
    "images": [
      "/exercise-refs/reverse_pec/0.jpg",
      "/exercise-refs/reverse_pec/1.jpg"
    ],
    "instructions": [
      "Adjust the handles so that they are fully to the rear. Make an appropriate weight selection and adjust the seat height so the handles are at shoulder level. Grasp the handles with your hands facing inwards. This will be your starting position.",
      "In a semicircular motion, pull your hands out to your side and back, contracting your rear delts.",
      "Keep your arms slightly bent throughout the movement, with all of the motion occurring at the shoulder joint.",
      "Pause at the rear of the movement, and slowly return the weight to the starting position."
    ],
    "primaryMuscles": [
      "shoulders"
    ],
    "equipment": "machine",
    "gist": "Machine rear-delt fly.",
    "steps": [
      "Handles at shoulder level",
      "Pull out and back",
      "Return slow"
    ],
    "cues": [
      "Motion at the shoulders",
      "Slight bend in arms"
    ]
  },
  "russian_twist": {
    "freeDbId": "Russian_Twist",
    "confidence": "high",
    "images": [
      "/exercise-refs/russian_twist/0.jpg",
      "/exercise-refs/russian_twist/1.jpg"
    ],
    "instructions": [
      "Lie down on the floor placing your feet either under something that will not move or by having a partner hold them. Your legs should be bent at the knees.",
      "Elevate your upper body so that it creates an imaginary V-shape with your thighs. Your arms should be fully extended in front of you perpendicular to your torso and with the hands clasped. This is the starting position.",
      "Twist your torso to the right side until your arms are parallel with the floor while breathing out.",
      "Hold the contraction for a second and move back to the starting position while breathing out. Now move to the opposite side performing the same techniques you applied to the right side.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "abdominals"
    ],
    "equipment": "body only",
    "gist": "Seated oblique twist.",
    "steps": [
      "Lean back, feet anchored",
      "Twist to one side",
      "Twist to the other"
    ],
    "cues": [
      "Hold each side a beat",
      "Keep your chest lifted"
    ]
  },
  "seated_cable_row": {
    "freeDbId": "Seated_Cable_Rows",
    "confidence": "medium",
    "images": [],
    "instructions": [
      "Sit at a low cable row with your feet on the platform and a slight bend in your knees. Grab the handle, sit tall with a flat back, and let your arms extend forward under tension. This is your starting position.",
      "Pull the handle to your midsection by driving your elbows back and squeezing your shoulder blades together. Keep your torso upright and still.",
      "Extend your arms slowly back to the start, keeping tension on the cable. Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "middle back"
    ],
    "equipment": "cable",
    "gist": "The cable back row.",
    "steps": [
      "Sit tall, flat back, arms extended",
      "Pull the handle to your midsection",
      "Return slow, keep tension"
    ],
    "cues": [
      "Drive your elbows back",
      "Squeeze your shoulder blades"
    ]
  },
  "seated_db_ohp": {
    "freeDbId": "Dumbbell_Shoulder_Press",
    "confidence": "high",
    "images": [
      "/exercise-refs/seated_db_ohp/0.jpg",
      "/exercise-refs/seated_db_ohp/1.jpg"
    ],
    "instructions": [
      "While holding a dumbbell in each hand, sit on a military press bench or utility bench that has back support. Place the dumbbells upright on top of your thighs.",
      "Now raise the dumbbells to shoulder height one at a time using your thighs to help propel them up into position.",
      "Make sure to rotate your wrists so that the palms of your hands are facing forward. This is your starting position.",
      "Now, exhale and push the dumbbells upward until they touch at the top.",
      "Then, after a brief pause at the top contracted position, slowly lower the weights back down to the starting position while inhaling.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "shoulders"
    ],
    "equipment": "dumbbell",
    "gist": "Seated dumbbell shoulder press.",
    "steps": [
      "Dumbbells at shoulders, palms forward",
      "Press up till they meet",
      "Lower slow"
    ],
    "cues": [
      "Use thighs to get them up",
      "Press straight overhead"
    ]
  },
  "seated_leg_curl": {
    "freeDbId": "Seated_Leg_Curl",
    "confidence": "high",
    "images": [
      "/exercise-refs/seated_leg_curl/0.jpg",
      "/exercise-refs/seated_leg_curl/1.jpg"
    ],
    "instructions": [
      "Adjust the machine lever to fit your height and sit on the machine with your back against the back support pad.",
      "Place the back of lower leg on top of padded lever (just a few inches under the calves) and secure the lap pad against your thighs, just above the knees. Then grasp the side handles on the machine as you point your toes straight (or you can also use any of the other two stances) and ensure that the legs are fully straight right in front of you. This will be your starting position.",
      "As you exhale, pull the machine lever as far as possible to the back of your thighs by flexing at the knees. Keep your torso stationary at all times. Hold the contracted position for a second.",
      "Slowly return to the starting position as you breathe in.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "hamstrings"
    ],
    "equipment": "machine",
    "gist": "Machine hamstring curl.",
    "steps": [
      "Legs over the lever, pad on thighs",
      "Curl down by bending knees",
      "Return slow"
    ],
    "cues": [
      "Keep your torso still",
      "Hold the bottom a beat"
    ]
  },
  "single_arm_row": {
    "freeDbId": "One-Arm_Dumbbell_Row",
    "confidence": "high",
    "images": [
      "/exercise-refs/single_arm_row/0.jpg",
      "/exercise-refs/single_arm_row/1.jpg"
    ],
    "instructions": [
      "Choose a flat bench and place a dumbbell on each side of it.",
      "Place the right leg on top of the end of the bench, bend your torso forward from the waist until your upper body is parallel to the floor, and place your right hand on the other end of the bench for support.",
      "Use the left hand to pick up the dumbbell on the floor and hold the weight while keeping your lower back straight. The palm of the hand should be facing your torso. This will be your starting position.",
      "Pull the resistance straight up to the side of your chest, keeping your upper arm close to your side and keeping the torso stationary. Breathe out as you perform this step. Tip: Concentrate on squeezing the back muscles once you reach the full contracted position. Also, make sure that the force is performed with the back muscles and not the arms. Finally, the upper torso should remain stationary and only the arms should move. The forearms should do no other work except for holding the dumbbell; therefore do not try to pull the dumbbell up using the forearms.",
      "Lower the resistance straight down to the starting position. Breathe in as you perform this step.",
      "Repeat the movement for the specified amount of repetitions.",
      "Switch sides and repeat again with the other arm."
    ],
    "primaryMuscles": [
      "middle back"
    ],
    "equipment": "dumbbell",
    "gist": "One-arm dumbbell back row.",
    "steps": [
      "Knee and hand on bench",
      "Row dumbbell to your chest",
      "Lower slow, then switch"
    ],
    "cues": [
      "Drive with your back",
      "Upper arm close, torso still"
    ]
  },
  "skullcrushers": {
    "freeDbId": "EZ-Bar_Skullcrusher",
    "confidence": "high",
    "images": [
      "/exercise-refs/skullcrushers/0.jpg",
      "/exercise-refs/skullcrushers/1.jpg"
    ],
    "instructions": [
      "Using a close grip, lift the EZ bar and hold it with your elbows in as you lie on the bench. Your arms should be perpendicular to the floor. This will be your starting position.",
      "Keeping the upper arms stationary, lower the bar by allowing the elbows to flex. Inhale as you perform this portion of the movement. Pause once the bar is directly above the forehead.",
      "Lift the bar back to the starting position by extending the elbow and exhaling.",
      "Repeat."
    ],
    "primaryMuscles": [
      "triceps"
    ],
    "equipment": "e-z curl bar",
    "gist": "EZ-bar triceps extension.",
    "steps": [
      "Lie down, arms vertical",
      "Lower bar to your forehead",
      "Extend back up"
    ],
    "cues": [
      "Upper arms stay still",
      "Move only at the elbows"
    ]
  },
  "standing_ohp": {
    "freeDbId": "Standing_Barbell_Press_Behind_Neck",
    "confidence": "high",
    "images": [
      "/exercise-refs/standing_ohp/0.jpg",
      "/exercise-refs/standing_ohp/1.jpg"
    ],
    "instructions": [
      "This exercise is best performed inside a squat rack for easier pick up of the bar. To begin, first set the bar on a rack that best matches your height. Once the correct height is chosen and the bar is loaded, step under the bar and place the back of your shoulders (slightly below the neck) across it.",
      "Hold on to the bar using both arms at each side and lift it off the rack by first pushing with your legs and at the same time straightening your torso.",
      "Step away from the rack and position your legs using a shoulder width medium stance with the toes slightly pointed out. Your back should be kept straight while performing this exercise. This will be your starting position.",
      "Elevate the barbell overhead by fully extending your arms while breathing out.",
      "Hold the contraction for a second and lower the barbell back down to the starting position by inhaling.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "shoulders"
    ],
    "equipment": "barbell",
    "gist": "Standing barbell shoulder press.",
    "steps": [
      "Bar on upper back, stand tall",
      "Press overhead to lockout",
      "Lower under control"
    ],
    "cues": [
      "Keep your back straight",
      "Full lockout overhead"
    ]
  },
  "t_bar_row": {
    "freeDbId": "Lying_T-Bar_Row",
    "confidence": "high",
    "images": [
      "/exercise-refs/t_bar_row/0.jpg",
      "/exercise-refs/t_bar_row/1.jpg"
    ],
    "instructions": [
      "Load up the T-bar Row Machine with the desired weight and adjust the leg height so that your upper chest is at the top of the pad. Tip: In some machines all you can do is stand on the appropriate step that allows you to be at a height that has the upper chest at the top of the pad.",
      "Lay face down on the pad and grab the handles. You can either use a palms down, palms up, or palms in position depending on what part of your back you want to emphasize.",
      "Lift the bar off the rack and extend your arms in front of you. This will be your starting position.",
      "As you exhale slowly pull the weight up and squeeze your back at the top of the movement. Tip: Keep the upper arms as close to the torso as possible throughout the movement in order to better engage the back muscles. Also, do not lift your body off of the pad at any time and refrain from using the biceps to lift the weight.",
      "After a second contraction at the top of the movement, as you inhale, slowly go back down to the starting position.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "middle back"
    ],
    "equipment": "machine",
    "gist": "Lying T-bar back row.",
    "steps": [
      "Face down on the pad",
      "Pull weight up, squeeze back",
      "Lower slow"
    ],
    "cues": [
      "Upper arms close to torso",
      "Stay on the pad"
    ]
  },
  "toes_to_bar": {
    "freeDbId": "Hanging_Pike",
    "confidence": "high",
    "images": [
      "/exercise-refs/toes_to_bar/0.jpg",
      "/exercise-refs/toes_to_bar/1.jpg"
    ],
    "instructions": [
      "Hang from a chin-up bar with your legs and feet together using an overhand grip (palms facing away from you) that is slightly wider than shoulder width. Tip: You may use wrist wraps in order to facilitate holding on to the bar.",
      "Now bend your knees at a 90 degree angle and bring the upper legs forward so that the calves are perpendicular to the floor while the thighs remain parallel to it. This will be your starting position.",
      "Pull your legs up as you exhale until you almost touch your shins with the bar above you. Tip: Try to straighten your legs as much as possible while at the top.",
      "Lower your legs as slowly as possible until you reach the starting position. Tip: Avoid swinging and using momentum at all times.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "abdominals"
    ],
    "equipment": "body only",
    "gist": "Hanging pike ab raise.",
    "steps": [
      "Hang, thighs up to parallel",
      "Pull shins toward the bar",
      "Lower as slow as you can"
    ],
    "cues": [
      "Straighten legs at the top",
      "No swinging"
    ]
  },
  "tri_pushdown": {
    "freeDbId": "Triceps_Pushdown_-_Rope_Attachment",
    "confidence": "high",
    "images": [
      "/exercise-refs/tri_pushdown/0.jpg",
      "/exercise-refs/tri_pushdown/1.jpg"
    ],
    "instructions": [
      "Attach a rope attachment to a high pulley and grab with a neutral grip (palms facing each other).",
      "Standing upright with the torso straight and a very small inclination forward, bring the upper arms close to your body and perpendicular to the floor. The forearms should be pointing up towards the pulley as they hold the rope with the palms facing each other. This is your starting position.",
      "Using the triceps, bring the rope down as you bring each side of the rope to the side of your thighs. At the end of the movement the arms are fully extended and perpendicular to the floor. The upper arms should always remain stationary next to your torso and only the forearms should move. Exhale as you perform this movement.",
      "After holding for a second, at the contracted position, bring the rope slowly up to the starting point. Breathe in as you perform this step.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "triceps"
    ],
    "equipment": "cable",
    "gist": "Rope triceps pushdown.",
    "steps": [
      "Rope at high pulley, elbows in",
      "Push down to your thighs",
      "Return slow"
    ],
    "cues": [
      "Upper arms by your sides",
      "Only the forearms move"
    ]
  },
  "walking_lunge": {
    "freeDbId": "Barbell_Walking_Lunge",
    "confidence": "high",
    "images": [
      "/exercise-refs/walking_lunge/0.jpg",
      "/exercise-refs/walking_lunge/1.jpg"
    ],
    "instructions": [
      "Begin standing with your feet shoulder width apart and a barbell across your upper back.",
      "Step forward with one leg, flexing the knees to drop your hips. Descend until your rear knee nearly touches the ground. Your posture should remain upright, and your front knee should stay above the front foot.",
      "Drive through the heel of your lead foot and extend both knees to raise yourself back up.",
      "Step forward with your rear foot, repeating the lunge on the opposite leg."
    ],
    "primaryMuscles": [
      "quadriceps"
    ],
    "equipment": "barbell",
    "gist": "Walking barbell quad lunge.",
    "steps": [
      "Bar on upper back",
      "Step forward, drop the knee",
      "Drive up and step through"
    ],
    "cues": [
      "Posture upright",
      "Front knee over front foot"
    ]
  },
  "weighted_situp": {
    "freeDbId": "Sit-Up",
    "confidence": "medium",
    "images": [
      "/exercise-refs/weighted_situp/0.jpg",
      "/exercise-refs/weighted_situp/1.jpg"
    ],
    "instructions": [
      "Lie down on the floor placing your feet either under something that will not move or by having a partner hold them. Your legs should be bent at the knees.",
      "Place your hands behind your head and lock them together by clasping your fingers. This is the starting position.",
      "Elevate your upper body so that it creates an imaginary V-shape with your thighs. Breathe out when performing this part of the exercise.",
      "Once you feel the contraction for a second, lower your upper body back down to the starting position while inhaling.",
      "Repeat for the recommended amount of repetitions."
    ],
    "primaryMuscles": [
      "abdominals"
    ],
    "equipment": "body only",
    "gist": "Weighted sit-up.",
    "steps": [
      "Feet anchored, knees bent",
      "Curl up toward thighs",
      "Lower slow"
    ],
    "cues": [
      "Hold the contraction a beat",
      "Control the way down"
    ]
  }
}
