import type { DbSupplement, WindowMeta, ConditionLabel } from './types'

/**
 * SUPPLEMENT DATABASE — drives the search autocomplete + the recommender.
 *
 * Per-row fields:
 *
 *   helps          — single-sentence answer to "what does this do for me"
 *   dose           — typical range
 *   window         — coarse time-of-day bucket
 *   bestTime       — finer timing nuance
 *   note           — extra usage tip (with food / cycle / interactions)
 *   brand          — a well-regarded mid-range pick. NOT an endorsement.
 *                    Show with a "starting at" caveat.
 *   priceUsdMonthly — rough US$/mo at the suggested dose, round numbers.
 *   baseScore      — default usefulness (1-10) for a generic adult.
 *   signalBoosts   — additive bumps when a personal signal applies. Final
 *                    score = clamp(baseScore + sum(active boosts), 1, 10).
 *
 * Numbers are conservative reads of common references. Not medical
 * advice — see "Talk to your doctor" rows where flagged.
 *
 * Brand picks lean toward established, third-party-tested labels
 * (Thorne, Nordic Naturals, NOW, etc.) where applicable. Where a
 * specific ingredient form is what matters (e.g. KSM-66 for ashwagandha,
 * MK-7 for K2), the brand string names the form rather than a label.
 */
export const SUPPLEMENT_DB: DbSupplement[] = [
  {
    id: 'creatine',
    name: 'Creatine monohydrate',
    icon: '🏋️',
    dose: '5 g',
    window: 'anytime',
    note: 'Daily. Consistency matters more than timing.',
    helps: 'Increases strength, power, and short-term work capacity. Mild cognitive benefit.',
    bestTime: 'Any time of day, every day. Skip the loading phase. It isn’t necessary.',
    aliases: ['creatine'],
    brand: 'Bulk Supplements (micronised) or Thorne',
    priceUsdMonthly: 10,
    baseScore: 8,
    signalBoosts: { 'heavy-training': 2, 'bulk-goal': 2, 'recomp-goal': 1, 'aging': 1, 'beginner-training': -1 },
  },
  {
    id: 'beta-alanine',
    name: 'Beta-alanine',
    icon: '🏋️',
    dose: '2-5 g',
    window: 'morning',
    note: 'Split doses if the tingles bother you.',
    helps: 'Buffers muscle acidity. Improves endurance on sets in the 1-4 min range.',
    bestTime: 'Daily. Effect is from saturation, not timing of the dose itself.',
    aliases: ['beta alanine'],
    brand: 'Bulk Supplements CarnoSyn',
    priceUsdMonthly: 20,
    baseScore: 5,
    signalBoosts: { 'heavy-training': 2, 'bulk-goal': 1 },
  },
  {
    id: 'l-citrulline',
    name: 'L-citrulline',
    icon: '🏋️',
    dose: '6-8 g',
    window: 'morning',
    note: 'Empty stomach for absorption.',
    helps: 'Boosts nitric oxide → better pumps and endurance.',
    bestTime: '30-45 min before training.',
    aliases: ['citrulline', 'citrulline malate'],
    brand: 'Bulk Supplements',
    priceUsdMonthly: 25,
    baseScore: 5,
    signalBoosts: { 'heavy-training': 2, 'bulk-goal': 1 },
  },
  {
    id: 'whey',
    name: 'Whey protein',
    icon: '🥤',
    dose: '25-40 g',
    window: 'anytime',
    note: 'Use to hit daily protein target.',
    helps: 'Fast-digesting protein for muscle repair + daily protein hitting.',
    bestTime: 'Post-workout or any meal where you’re short on protein.',
    aliases: ['whey', 'protein powder'],
    brand: 'Optimum Nutrition Gold Standard or Transparent Labs',
    priceUsdMonthly: 50,
    baseScore: 7,
    signalBoosts: { 'bulk-goal': 2, 'recomp-goal': 1, 'heavy-training': 1 },
  },
  {
    id: 'casein',
    name: 'Casein protein',
    icon: '🥤',
    dose: '25-40 g',
    window: 'evening',
    note: 'Slow-release. Good before bed.',
    helps: 'Slow-digesting protein. Sustained amino release overnight.',
    bestTime: '30-60 min before bed.',
    aliases: ['casein'],
    brand: 'Optimum Nutrition Gold Standard Casein',
    priceUsdMonthly: 45,
    baseScore: 5,
    signalBoosts: { 'bulk-goal': 2, 'heavy-training': 1 },
  },
  {
    id: 'l-carnitine',
    name: 'L-carnitine',
    icon: '🏋️',
    dose: '1-2 g',
    window: 'morning',
    note: 'Take with carbs for uptake.',
    helps: 'Helps shuttle fat into mitochondria. Modest endurance + recovery effect.',
    bestTime: 'With a carb-containing meal, ideally pre-workout.',
    aliases: ['carnitine'],
    brand: 'NOW Foods L-Carnitine',
    priceUsdMonthly: 20,
    baseScore: 4,
    signalBoosts: { 'cut-goal': 1, 'heavy-training': 1 },
  },
  {
    id: 'alcar',
    name: 'Acetyl-L-carnitine',
    icon: '🧠',
    dose: '500 mg - 2 g',
    window: 'morning',
    note: 'Crosses blood-brain barrier. Cognitive variant.',
    helps: 'Cognitive + mood support; may sharpen focus.',
    bestTime: 'AM, on an empty stomach if you can tolerate it.',
    aliases: ['alcar', 'acetyl carnitine'],
    brand: 'Doctor’s Best Acetyl-L-Carnitine',
    priceUsdMonthly: 25,
    baseScore: 5,
    signalBoosts: { 'aging': 1, 'general-health-goal': 1, 'has-stims': 1 },
  },
  {
    id: 'vit-d3',
    name: 'Vitamin D3',
    icon: '☀️',
    dose: '2,000-5,000 IU',
    window: 'lunch',
    note: 'Fat-soluble. Pair with your biggest meal.',
    helps: 'Immune, bone, and mood support. Most people are deficient.',
    bestTime: 'Daily, with whatever meal has the most fat.',
    aliases: ['vit d', 'vitamin d', 'd3', 'cholecalciferol'],
    brand: 'Thorne Vitamin D-5,000 or NOW Foods',
    priceUsdMonthly: 10,
    baseScore: 8,
    signalBoosts: { 'general-health-goal': 1, 'aging': 1, 'senior': 2 },
  },
  {
    id: 'vit-k2',
    name: 'Vitamin K2 (MK-7)',
    icon: '💊',
    dose: '100-200 mcg',
    window: 'lunch',
    note: 'Pair with D3 for calcium routing.',
    helps: 'Directs calcium to bones, away from arteries. Synergistic with D3.',
    bestTime: 'Same meal as your D3.',
    aliases: ['vit k', 'vitamin k', 'k2', 'mk7'],
    brand: 'Life Extension Super K with MK-7',
    priceUsdMonthly: 20,
    baseScore: 5,
    signalBoosts: { 'aging': 1, 'senior': 2 },
  },
  {
    id: 'vit-c',
    name: 'Vitamin C',
    icon: '🍊',
    dose: '500-1,000 mg',
    window: 'morning',
    note: 'Water-soluble. Split doses if above 500 mg.',
    helps: 'Antioxidant + collagen synthesis cofactor. Mild immune support.',
    bestTime: 'AM, with food. Split larger doses across the day.',
    aliases: ['vit c', 'ascorbic acid'],
    brand: 'NOW Foods Vitamin C',
    priceUsdMonthly: 12,
    baseScore: 5,
    signalBoosts: { 'has-nicotine': 1, 'general-health-goal': 1 },
  },
  {
    id: 'b12',
    name: 'Vitamin B12',
    icon: '⚡',
    dose: '500-1,000 mcg',
    window: 'morning',
    note: 'Methylcobalamin form is best absorbed.',
    helps: 'Energy, nerve function, red blood cell production.',
    bestTime: 'AM. Can be stimulating for some.',
    aliases: ['b12', 'methylcobalamin'],
    brand: 'Jarrow Methyl-B12 (sublingual)',
    priceUsdMonthly: 12,
    baseScore: 5,
    signalBoosts: { 'aging': 1, 'senior': 1 },
  },
  {
    id: 'b-complex',
    name: 'B-complex',
    icon: '⚡',
    dose: '1 cap',
    window: 'morning',
    note: 'All B vitamins together. Energy support.',
    helps: 'Broad energy + nervous system cofactors. Useful if diet is thin.',
    bestTime: 'AM with food. Can be stimulating.',
    aliases: ['b complex', 'b vitamins'],
    brand: 'Thorne Basic B Complex',
    priceUsdMonthly: 18,
    baseScore: 5,
    signalBoosts: { 'general-health-goal': 1, 'has-stims': 1 },
  },
  {
    id: 'multivitamin',
    name: 'Multivitamin',
    icon: '💊',
    dose: '1 serving',
    window: 'lunch',
    note: 'Take with food for absorption.',
    helps: 'Backstop for the micronutrients your diet misses.',
    bestTime: 'With the biggest meal of the day.',
    aliases: ['multi', 'multivitamin'],
    brand: 'Thorne Basic Nutrients 2/Day',
    priceUsdMonthly: 30,
    baseScore: 6,
    signalBoosts: { 'general-health-goal': 2, 'beginner-training': 1 },
  },
  {
    id: 'mag-glycinate',
    name: 'Magnesium glycinate',
    icon: '🌙',
    dose: '200-400 mg',
    window: 'evening',
    note: 'Sleep helper. 30-60 min before bed.',
    helps: 'Relaxes muscles + nervous system. Improves sleep quality.',
    bestTime: '30-60 min before bed.',
    aliases: ['magnesium', 'mag glycinate', 'bisglycinate'],
    brand: 'Doctor’s Best High Absorption or Thorne',
    priceUsdMonthly: 20,
    baseScore: 8,
    signalBoosts: { 'has-stims': 2, 'poor-sleep': 2, 'low-recovery': 2, 'high-caffeine': 1, 'aging': 1 },
  },
  {
    id: 'mag-threonate',
    name: 'Magnesium L-threonate',
    icon: '🧠',
    dose: '144 mg elemental',
    window: 'evening',
    note: 'Crosses the blood-brain barrier.',
    helps: 'Cognitive variant of magnesium. Sleep + memory support.',
    bestTime: '60-90 min before bed.',
    aliases: ['magtein', 'threonate'],
    brand: 'Magtein (Life Extension Neuro-Mag)',
    priceUsdMonthly: 35,
    baseScore: 6,
    signalBoosts: { 'aging': 1, 'poor-sleep': 1, 'has-stims': 1 },
  },
  {
    id: 'zinc',
    name: 'Zinc',
    icon: '💊',
    dose: '15-30 mg',
    window: 'evening',
    note: 'Don’t pair with calcium or iron.',
    helps: 'Immune + hormonal support. Don’t megadose long-term.',
    bestTime: 'With dinner, away from calcium/iron.',
    aliases: ['zinc'],
    brand: 'Thorne Zinc Picolinate',
    priceUsdMonthly: 10,
    baseScore: 5,
    signalBoosts: { 'male': 1, 'heavy-training': 1 },
  },
  {
    id: 'iron',
    name: 'Iron',
    icon: '💊',
    dose: '18-65 mg',
    window: 'morning',
    note: 'Only supplement if labs confirm deficiency.',
    helps: 'Treats iron-deficiency anemia. Only supplement if labs confirm low.',
    bestTime: 'AM on empty stomach with a vit C source (orange juice).',
    aliases: ['iron'],
    brand: 'Thorne Iron Bisglycinate',
    priceUsdMonthly: 15,
    baseScore: 3,
    signalBoosts: { 'female': 2 },
  },
  {
    id: 'omega-3',
    name: 'Omega-3 (Fish oil)',
    icon: '🐟',
    dose: '2-3 g EPA + DHA',
    window: 'lunch',
    note: 'Take with the fattiest meal of the day.',
    helps: 'Anti-inflammatory, brain + cardiovascular support.',
    bestTime: 'With the meal that has the most fat.',
    aliases: ['omega 3', 'omega3', 'fish oil', 'epa', 'dha'],
    brand: 'Nordic Naturals Ultimate Omega or Carlson',
    priceUsdMonthly: 30,
    baseScore: 7,
    signalBoosts: { 'aging': 2, 'senior': 2, 'general-health-goal': 1, 'heavy-training': 1 },
  },
  {
    id: 'l-theanine',
    name: 'L-theanine',
    icon: '🧠',
    dose: '100-200 mg',
    window: 'morning',
    note: 'Stack with caffeine 2:1 for cleaner focus.',
    helps: 'Calm, focused alertness. Takes the edge off caffeine.',
    bestTime: 'With your morning coffee.',
    aliases: ['theanine'],
    brand: 'NOW Foods Suntheanine',
    priceUsdMonthly: 15,
    baseScore: 5,
    signalBoosts: { 'high-caffeine': 3, 'very-high-caffeine': 4, 'has-stims': 2 },
  },
  {
    id: 'rhodiola',
    name: 'Rhodiola rosea',
    icon: '🌿',
    dose: '200-400 mg',
    window: 'morning',
    note: 'Adaptogen. Stress + energy.',
    helps: 'Reduces stress-related fatigue. Mild stimulant feel.',
    bestTime: 'AM on empty stomach.',
    aliases: ['rhodiola'],
    brand: 'NOW Foods Rhodiola',
    priceUsdMonthly: 22,
    baseScore: 4,
    signalBoosts: { 'cut-goal': 1, 'general-health-goal': 1 },
  },
  {
    id: 'lions-mane',
    name: 'Lion’s mane',
    icon: '🍄',
    dose: '500-1,000 mg',
    window: 'morning',
    note: 'Daily for cognitive support.',
    helps: 'Supports nerve growth factor. Long-term cognitive benefit.',
    bestTime: 'AM with breakfast.',
    aliases: ['lions mane', 'hericium'],
    brand: 'Host Defense or Real Mushrooms',
    priceUsdMonthly: 30,
    baseScore: 5,
    signalBoosts: { 'general-health-goal': 1, 'aging': 1 },
  },
  {
    id: 'alpha-gpc',
    name: 'Alpha-GPC',
    icon: '🧠',
    dose: '300-600 mg',
    window: 'morning',
    note: 'Choline source. Focus.',
    helps: 'Boosts acetylcholine. Sharper focus and learning.',
    bestTime: '30 min before deep work or training.',
    aliases: ['alpha gpc'],
    brand: 'Double Wood Alpha-GPC',
    priceUsdMonthly: 25,
    baseScore: 5,
    signalBoosts: { 'heavy-training': 1, 'has-stims': 1 },
  },
  {
    id: 'nac',
    name: 'NAC',
    icon: '💊',
    dose: '600-1,800 mg',
    window: 'morning',
    note: 'Glutathione precursor. Split doses.',
    helps: 'Antioxidant + liver support. Useful for heavy training loads.',
    bestTime: 'AM on empty stomach.',
    aliases: ['nac', 'n-acetyl cysteine'],
    brand: 'NOW Foods NAC or Jarrow',
    priceUsdMonthly: 20,
    baseScore: 5,
    signalBoosts: { 'has-stims': 1, 'has-nicotine': 2, 'has-alcohol': 2, 'heavy-training': 1 },
  },
  {
    id: 'melatonin',
    name: 'Melatonin',
    icon: '🌙',
    dose: '0.3-3 mg',
    window: 'evening',
    note: 'Lowest effective dose. More isn’t better.',
    helps: 'Shifts circadian rhythm. Useful for jet lag or chronotype shifts.',
    bestTime: '30-60 min before target bedtime.',
    aliases: ['melatonin'],
    brand: 'NOW Foods (look for 0.5-1 mg tabs)',
    priceUsdMonthly: 8,
    baseScore: 5,
    signalBoosts: { 'poor-sleep': 2 },
  },
  {
    id: 'glycine',
    name: 'Glycine',
    icon: '🌙',
    dose: '3 g',
    window: 'evening',
    note: 'Sleep onset. Drops body temp slightly.',
    helps: 'Lowers core body temperature → faster sleep onset.',
    bestTime: 'Right before bed.',
    aliases: ['glycine'],
    brand: 'NOW Foods Glycine Powder',
    priceUsdMonthly: 12,
    baseScore: 5,
    signalBoosts: { 'poor-sleep': 2 },
  },
  {
    id: 'ashwagandha',
    name: 'Ashwagandha',
    icon: '🌿',
    dose: '300-600 mg',
    window: 'evening',
    note: 'KSM-66 is the most-studied form.',
    helps: 'Lowers cortisol + stress. Modest sleep + recovery benefit.',
    bestTime: 'With dinner. Calming effect.',
    aliases: ['ashwagandha', 'ksm-66'],
    brand: 'NutriRise KSM-66 (the specific extract matters)',
    priceUsdMonthly: 25,
    baseScore: 5,
    signalBoosts: { 'low-recovery': 3, 'poor-sleep': 2, 'has-stims': 1, 'heavy-training': 1 },
  },
  {
    id: 'tryptophan',
    name: 'L-tryptophan',
    icon: '🌙',
    dose: '500 mg - 1 g',
    window: 'evening',
    note: 'Serotonin precursor.',
    helps: 'Supports serotonin → melatonin pathway for sleep onset.',
    bestTime: '60 min before bed, away from protein meals.',
    aliases: ['tryptophan'],
    brand: 'NOW Foods L-Tryptophan',
    priceUsdMonthly: 18,
    baseScore: 4,
    signalBoosts: { 'poor-sleep': 1 },
  },
  {
    id: 'apigenin',
    name: 'Apigenin',
    icon: '🌙',
    dose: '50 mg',
    window: 'evening',
    note: 'Chamomile-derived calming compound.',
    helps: 'Mild GABA-ergic relaxation. Pairs with magnesium.',
    bestTime: '30 min before bed.',
    aliases: ['apigenin'],
    brand: 'Double Wood Apigenin',
    priceUsdMonthly: 25,
    baseScore: 4,
    signalBoosts: { 'poor-sleep': 1, 'has-stims': 1 },
  },
  {
    id: 'caffeine',
    name: 'Caffeine',
    icon: '☕',
    dose: '100-200 mg',
    window: 'morning',
    note: 'Stack with L-theanine for cleaner focus.',
    helps: 'Wakefulness + endurance. Half-life is ~5 h, so careful past noon.',
    bestTime: '90 min after waking. Lets cortisol peak first.',
    aliases: ['caffeine'],
    brand: 'Nutricost Caffeine 100 mg',
    priceUsdMonthly: 5,
    baseScore: 3,
    signalBoosts: { 'cut-goal': 1 },
  },
  {
    id: 'probiotics',
    name: 'Probiotics',
    icon: '🦠',
    dose: '10-50 billion CFU',
    window: 'morning',
    note: 'Empty stomach or with light meal.',
    helps: 'Gut flora support. Quality + strain matter more than CFU count.',
    bestTime: 'AM on empty stomach.',
    aliases: ['probiotic'],
    brand: 'Seed DS-01 or Garden of Life Raw',
    priceUsdMonthly: 35,
    baseScore: 5,
    signalBoosts: { 'general-health-goal': 1 },
  },
  {
    id: 'curcumin',
    name: 'Curcumin',
    icon: '🌿',
    dose: '500-1,000 mg',
    window: 'lunch',
    note: 'With black pepper + fat for absorption.',
    helps: 'Anti-inflammatory. Joint + recovery support.',
    bestTime: 'With a fatty meal.',
    aliases: ['curcumin', 'turmeric'],
    brand: 'Thorne Curcumin Phytosome (Meriva)',
    priceUsdMonthly: 25,
    baseScore: 5,
    signalBoosts: { 'heavy-training': 1, 'aging': 1, 'low-recovery': 1 },
  },
  {
    id: 'coq10',
    name: 'CoQ10 / Ubiquinol',
    icon: '💊',
    dose: '100-200 mg',
    window: 'lunch',
    note: 'Fat-soluble. With biggest meal.',
    helps: 'Mitochondrial support. Worth it if you’re on a statin.',
    bestTime: 'With the fattiest meal of the day.',
    aliases: ['coq10', 'ubiquinol'],
    brand: 'Qunol Mega CoQ10 or Thorne Q-Best 100',
    priceUsdMonthly: 35,
    baseScore: 5,
    signalBoosts: { 'senior': 2, 'aging': 1 },
  },
  {
    id: 'berberine',
    name: 'Berberine',
    icon: '💊',
    dose: '500 mg',
    window: 'lunch',
    note: 'Take just before carb-heavy meals.',
    helps: 'Improves glucose handling. Comparable to metformin in some studies.',
    bestTime: '15 min before meals. Split across the day.',
    aliases: ['berberine'],
    brand: 'Thorne Berberine-500',
    priceUsdMonthly: 25,
    baseScore: 5,
    signalBoosts: { 'cut-goal': 1, 'aging': 1 },
  },
  {
    id: 'collagen',
    name: 'Collagen peptides',
    icon: '💅',
    dose: '10-20 g',
    window: 'anytime',
    note: 'With vitamin C for synthesis.',
    helps: 'Connective tissue + skin support. Most useful 30-60 min pre-load.',
    bestTime: 'Anytime. Many take it pre-workout for joints.',
    aliases: ['collagen'],
    brand: 'Vital Proteins Collagen Peptides',
    priceUsdMonthly: 30,
    baseScore: 5,
    signalBoosts: { 'aging': 1, 'senior': 1, 'heavy-training': 1 },
  },
  {
    id: 'tongkat',
    name: 'Tongkat ali',
    icon: '🌿',
    dose: '200-400 mg',
    window: 'morning',
    note: 'Cycle 8 weeks on, 2-4 off.',
    helps: 'May support endogenous testosterone. Mild energy + libido lift.',
    bestTime: 'AM on empty stomach.',
    aliases: ['tongkat', 'longjack'],
    brand: 'Nutricost Tongkat Ali 200 mg',
    priceUsdMonthly: 40,
    baseScore: 4,
    signalBoosts: { 'male': 1, 'aging': 1 },
  },
  {
    id: 'fadogia',
    name: 'Fadogia agrestis',
    icon: '🌿',
    dose: '600 mg',
    window: 'morning',
    note: 'Cycle 8 weeks on / off.',
    helps: 'Often stacked with tongkat for hormonal support.',
    bestTime: 'AM, alongside tongkat if stacking.',
    aliases: ['fadogia'],
    brand: 'Double Wood Fadogia Agrestis',
    priceUsdMonthly: 30,
    baseScore: 3,
    signalBoosts: { 'male': 1 },
  },
  {
    id: 'reishi',
    name: 'Reishi',
    icon: '🍄',
    dose: '1-2 g',
    window: 'evening',
    note: 'Calming adaptogen.',
    helps: 'Immune + sleep support. Subtle calming effect.',
    bestTime: 'With dinner or before bed.',
    aliases: ['reishi', 'ganoderma'],
    brand: 'Host Defense Reishi',
    priceUsdMonthly: 25,
    baseScore: 4,
    signalBoosts: { 'poor-sleep': 1, 'low-recovery': 1 },
  },
  {
    id: 'cordyceps',
    name: 'Cordyceps',
    icon: '🍄',
    dose: '1-3 g',
    window: 'morning',
    note: 'Energy + endurance support.',
    helps: 'Modest endurance + oxygen utilization boost.',
    bestTime: 'AM, pre-workout if training in the morning.',
    aliases: ['cordyceps'],
    brand: 'Real Mushrooms Cordyceps-M',
    priceUsdMonthly: 25,
    baseScore: 4,
    signalBoosts: { 'heavy-training': 1, 'cut-goal': 1 },
  },
// --- expanded library ---
  {
    id: 'taurine',
    name: 'Taurine',
    icon: '💪',
    dose: '1-3 g',
    window: 'anytime',
    note: 'Take with or without food. Often stacked pre-workout.',
    helps: 'Supports endurance, hydration, and exercise output.',
    bestTime: '30-60 min before training.',
    aliases: ['taurine'],
    brand: 'Bulk Supplements',
    priceUsdMonthly: 8,
    baseScore: 5,
    signalBoosts: { 'heavy-training': 1, 'high-caffeine': 1 },
  },
  {
    id: 'betaine-tmg',
    name: 'Betaine (TMG)',
    icon: '💪',
    dose: '2.5 g',
    window: 'anytime',
    note: 'Split with meals. Supports methylation and power output.',
    helps: 'May improve strength, power, and homocysteine balance.',
    bestTime: 'With breakfast or pre-workout.',
    aliases: ['betaine', 'tmg', 'trimethylglycine'],
    brand: 'NutraBio',
    priceUsdMonthly: 10,
    baseScore: 5,
    signalBoosts: { 'heavy-training': 1, 'recomp-goal': 1, 'aging': 1 },
  },
  {
    id: 'hmb',
    name: 'HMB',
    icon: '💪',
    dose: '3 g',
    window: 'anytime',
    note: 'Split into 1 g doses with meals. Best in a calorie deficit.',
    helps: 'Helps preserve muscle during dieting or intense training.',
    bestTime: 'With meals across the day.',
    aliases: ['hmb', 'beta-hydroxy beta-methylbutyrate'],
    brand: 'NOW Foods',
    priceUsdMonthly: 18,
    baseScore: 4,
    signalBoosts: { 'cut-goal': 2, 'heavy-training': 1, 'senior': 1 },
  },
  {
    id: 'eaa',
    name: 'Essential amino acids (EAA)',
    icon: '💪',
    dose: '10-15 g',
    window: 'anytime',
    note: 'Sip around training. Useful when protein intake is low.',
    helps: 'Provides the full set of building blocks for muscle protein synthesis.',
    bestTime: 'During or right after a workout.',
    aliases: ['eaa', 'essential amino acids', 'amino acids'],
    brand: 'Transparent Labs',
    priceUsdMonthly: 30,
    baseScore: 4,
    signalBoosts: { 'heavy-training': 1, 'bulk-goal': 1, 'cut-goal': 1 },
  },
  {
    id: 'electrolytes',
    name: 'Electrolytes',
    icon: '💪',
    dose: '1 serving',
    window: 'anytime',
    note: 'Use on hot days, long sessions, or low-carb diets.',
    helps: 'Replaces sodium, potassium, and magnesium lost in sweat.',
    bestTime: 'Before or during exercise.',
    aliases: ['electrolytes', 'lmnt', 'salts', 'hydration'],
    brand: 'LMNT',
    priceUsdMonthly: 30,
    baseScore: 5,
    signalBoosts: { 'heavy-training': 2, 'cut-goal': 1 },
  },
  {
    id: 'sodium-bicarbonate',
    name: 'Sodium bicarbonate',
    icon: '💪',
    dose: '0.2-0.3 g/kg',
    window: 'anytime',
    note: 'Take 60-90 min pre-workout. Can cause GI upset; start low.',
    helps: 'Buffers acid buildup to extend high-intensity performance.',
    bestTime: '60-90 min before training.',
    aliases: ['sodium bicarbonate', 'baking soda', 'bicarb'],
    brand: 'Bulk Supplements',
    priceUsdMonthly: 5,
    baseScore: 3,
    signalBoosts: { 'heavy-training': 2 },
  },
  {
    id: 'beetroot',
    name: 'Beetroot extract',
    icon: '🌿',
    dose: '300-600 mg nitrate',
    window: 'anytime',
    note: 'Take 2-3 hours pre-exercise for nitric oxide effect.',
    helps: 'Boosts blood flow and endurance via dietary nitrate.',
    bestTime: '2-3 hours before training.',
    aliases: ['beetroot', 'beet', 'nitrate', 'beet juice'],
    brand: 'HumanN SuperBeets',
    priceUsdMonthly: 30,
    baseScore: 5,
    signalBoosts: { 'heavy-training': 1, 'general-health-goal': 1, 'aging': 1 },
  },
  {
    id: 'egg-protein',
    name: 'Egg white protein',
    icon: '💪',
    dose: '25-30 g',
    window: 'anytime',
    note: 'Dairy-free protein option. Mix well to avoid clumping.',
    helps: 'Delivers high-quality complete protein without lactose.',
    bestTime: 'Post-workout or between meals.',
    aliases: ['egg protein', 'egg white protein'],
    brand: 'NOW Foods',
    priceUsdMonthly: 35,
    baseScore: 5,
    signalBoosts: { 'bulk-goal': 1, 'heavy-training': 1 },
  },
  {
    id: 'pea-protein',
    name: 'Pea protein',
    icon: '🌿',
    dose: '25-30 g',
    window: 'anytime',
    note: 'Plant-based and allergen-friendly. Pair sources for full profile.',
    helps: 'Provides a vegan protein source to hit daily targets.',
    bestTime: 'Post-workout or between meals.',
    aliases: ['pea protein', 'vegan protein', 'plant protein'],
    brand: 'NOW Foods',
    priceUsdMonthly: 30,
    baseScore: 5,
    signalBoosts: { 'bulk-goal': 1, 'heavy-training': 1 },
  },
  {
    id: 'folate',
    name: 'Folate',
    icon: '💊',
    dose: '400 mcg',
    window: 'anytime',
    note: 'Use methylfolate form. Important before and during pregnancy.',
    helps: 'Supports red blood cell formation and DNA synthesis.',
    bestTime: 'With breakfast.',
    aliases: ['folate', 'folic acid', 'methylfolate', 'vitamin b9'],
    brand: 'Thorne',
    priceUsdMonthly: 10,
    baseScore: 4,
    signalBoosts: { 'female': 2, 'general-health-goal': 1 },
  },
  {
    id: 'vit-b6',
    name: 'Vitamin B6',
    icon: '💊',
    dose: '1.3-2 mg',
    window: 'anytime',
    note: 'Use P-5-P form. Avoid chronic high doses (nerve risk).',
    helps: 'Supports energy metabolism and neurotransmitter production.',
    bestTime: 'With breakfast.',
    aliases: ['vitamin b6', 'b6', 'pyridoxine', 'p5p'],
    brand: 'Thorne',
    priceUsdMonthly: 8,
    baseScore: 3,
    signalBoosts: { 'female': 1, 'general-health-goal': 1 },
  },
  {
    id: 'vit-b1',
    name: 'Vitamin B1 (Thiamine)',
    icon: '💊',
    dose: '1.1-1.2 mg',
    window: 'anytime',
    note: 'Water-soluble; safe across a wide range.',
    helps: 'Supports energy metabolism and nerve function.',
    bestTime: 'With breakfast.',
    aliases: ['vitamin b1', 'b1', 'thiamine', 'thiamin'],
    brand: 'NOW Foods',
    priceUsdMonthly: 6,
    baseScore: 3,
    signalBoosts: { 'has-alcohol': 1, 'general-health-goal': 1 },
  },
  {
    id: 'calcium',
    name: 'Calcium',
    icon: '🦴',
    dose: '500-600 mg',
    window: 'anytime',
    note: 'Split doses; take with food. Pair with vitamin D and K2.',
    helps: 'Supports bone density and muscle function.',
    bestTime: 'With meals, away from iron.',
    aliases: ['calcium', 'calcium citrate'],
    brand: 'Citracal',
    priceUsdMonthly: 10,
    baseScore: 4,
    signalBoosts: { 'senior': 2, 'aging': 1, 'female': 1 },
  },
  {
    id: 'selenium',
    name: 'Selenium',
    icon: '💊',
    dose: '55-100 mcg',
    window: 'anytime',
    note: 'Do not exceed 400 mcg/day. Selenomethionine is well absorbed.',
    helps: 'Supports thyroid function and antioxidant defense.',
    bestTime: 'With a meal.',
    aliases: ['selenium', 'selenomethionine'],
    brand: 'NOW Foods',
    priceUsdMonthly: 6,
    baseScore: 3,
    signalBoosts: { 'general-health-goal': 1, 'aging': 1 },
  },
  {
    id: 'chromium',
    name: 'Chromium',
    icon: '💊',
    dose: '200 mcg',
    window: 'anytime',
    note: 'Take with meals. Chromium picolinate is the common form.',
    helps: 'May support blood sugar handling and insulin sensitivity.',
    bestTime: 'With a carbohydrate-containing meal.',
    aliases: ['chromium', 'chromium picolinate'],
    brand: 'NOW Foods',
    priceUsdMonthly: 6,
    baseScore: 3,
    signalBoosts: { 'general-health-goal': 1, 'cut-goal': 1 },
  },
  {
    id: 'boron',
    name: 'Boron',
    icon: '💊',
    dose: '3-6 mg',
    window: 'anytime',
    note: 'Take with food. Cycle rather than dose indefinitely.',
    helps: 'May support free testosterone, bone health, and hormone balance.',
    bestTime: 'With breakfast.',
    aliases: ['boron'],
    brand: 'NOW Foods',
    priceUsdMonthly: 6,
    baseScore: 3,
    signalBoosts: { 'male': 1, 'aging': 1 },
  },
  {
    id: 'krill-oil',
    name: 'Krill oil',
    icon: '❤️',
    dose: '1-3 g',
    window: 'anytime',
    note: 'Take with food. Phospholipid-bound omega-3 with astaxanthin.',
    helps: 'Delivers EPA and DHA in a well-absorbed form.',
    bestTime: 'With a meal containing fat.',
    aliases: ['krill oil', 'krill'],
    brand: 'Sports Research',
    priceUsdMonthly: 25,
    baseScore: 5,
    signalBoosts: { 'aging': 1, 'general-health-goal': 1, 'low-recovery': 1 },
  },
  {
    id: 'evening-primrose',
    name: 'Evening primrose oil',
    icon: '🌿',
    dose: '500-1300 mg',
    window: 'anytime',
    note: 'GLA source; take with food. Often used for cycle symptoms.',
    helps: 'May ease PMS symptoms and support skin health.',
    bestTime: 'With a meal.',
    aliases: ['evening primrose', 'epo', 'gla'],
    brand: 'NOW Foods',
    priceUsdMonthly: 10,
    baseScore: 3,
    signalBoosts: { 'female': 2 },
  },
  {
    id: 'valerian',
    name: 'Valerian root',
    icon: '😴',
    dose: '300-600 mg',
    window: 'evening',
    note: 'Can take a couple weeks for full effect. Mild sedation.',
    helps: 'Supports falling asleep and easing nighttime anxiety.',
    bestTime: '30-60 min before bed.',
    aliases: ['valerian', 'valerian root'],
    brand: 'Nature\'s Way',
    priceUsdMonthly: 8,
    baseScore: 4,
    signalBoosts: { 'poor-sleep': 2 },
  },
  {
    id: 'tart-cherry',
    name: 'Tart cherry',
    icon: '😴',
    dose: '480 mg extract',
    window: 'evening',
    note: 'Natural melatonin source; good for recovery and sleep.',
    helps: 'Aids sleep quality and post-exercise muscle recovery.',
    bestTime: 'In the evening.',
    aliases: ['tart cherry', 'montmorency cherry', 'cherry'],
    brand: 'Cherry Bay Orchards',
    priceUsdMonthly: 18,
    baseScore: 4,
    signalBoosts: { 'poor-sleep': 1, 'low-recovery': 2, 'heavy-training': 1 },
  },
  {
    id: '5-htp',
    name: '5-HTP',
    icon: '😴',
    dose: '50-100 mg',
    window: 'evening',
    note: 'Do not combine with SSRIs or other serotonergic meds.',
    helps: 'A serotonin precursor that may support mood and sleep.',
    bestTime: 'Evening, away from protein.',
    aliases: ['5-htp', '5 htp', '5-hydroxytryptophan'],
    brand: 'NOW Foods',
    priceUsdMonthly: 10,
    baseScore: 3,
    signalBoosts: { 'poor-sleep': 1 },
  },
  {
    id: 'l-tyrosine',
    name: 'L-Tyrosine',
    icon: '🧠',
    dose: '500-2000 mg',
    window: 'morning',
    note: 'Take on an empty stomach. Useful under stress or sleep loss.',
    helps: 'Supports focus and dopamine under stressful conditions.',
    bestTime: 'Morning, away from protein.',
    aliases: ['tyrosine', 'l-tyrosine'],
    brand: 'NOW Foods',
    priceUsdMonthly: 9,
    baseScore: 4,
    signalBoosts: { 'poor-sleep': 1, 'high-caffeine': 1, 'has-stims': 1 },
  },
  {
    id: 'lavender-silexan',
    name: 'Lavender (Silexan)',
    icon: '😴',
    dose: '80 mg',
    window: 'evening',
    note: 'Standardized oral lavender oil; take with water.',
    helps: 'Eases anxiety and supports calm before sleep.',
    bestTime: 'Evening with a meal.',
    aliases: ['lavender', 'silexan', 'lavender oil'],
    brand: 'Calm Aid',
    priceUsdMonthly: 18,
    baseScore: 4,
    signalBoosts: { 'poor-sleep': 1 },
  },
  {
    id: 'bacopa',
    name: 'Bacopa monnieri',
    icon: '🧠',
    dose: '300 mg',
    window: 'anytime',
    note: 'Take with food. Effects build over 8-12 weeks.',
    helps: 'Supports memory and learning over consistent use.',
    bestTime: 'With a meal.',
    aliases: ['bacopa', 'brahmi', 'bacopa monnieri'],
    brand: 'Himalaya',
    priceUsdMonthly: 12,
    baseScore: 4,
    signalBoosts: { 'aging': 1, 'general-health-goal': 1 },
  },
  {
    id: 'citicoline',
    name: 'Citicoline (CDP-choline)',
    icon: '🧠',
    dose: '250-500 mg',
    window: 'morning',
    note: 'Take earlier in the day. Stacks with caffeine for focus.',
    helps: 'Supports focus, attention, and brain cell membranes.',
    bestTime: 'Morning with breakfast.',
    aliases: ['citicoline', 'cdp-choline', 'cdp choline', 'cognizin'],
    brand: 'Jarrow Formulas',
    priceUsdMonthly: 22,
    baseScore: 5,
    signalBoosts: { 'aging': 1, 'high-caffeine': 1 },
  },
  {
    id: 'phosphatidylserine',
    name: 'Phosphatidylserine',
    icon: '🧠',
    dose: '100-300 mg',
    window: 'anytime',
    note: 'Take with food. May blunt cortisol when taken pre-stress.',
    helps: 'Supports memory and helps manage stress hormones.',
    bestTime: 'With meals; some take it evening.',
    aliases: ['phosphatidylserine', 'ps'],
    brand: 'Jarrow Formulas',
    priceUsdMonthly: 20,
    baseScore: 4,
    signalBoosts: { 'aging': 1, 'low-recovery': 1, 'senior': 1 },
  },
  {
    id: 'ginkgo',
    name: 'Ginkgo biloba',
    icon: '🧠',
    dose: '120-240 mg',
    window: 'anytime',
    note: 'Avoid with blood thinners. Effects build over weeks.',
    helps: 'May support circulation and mental sharpness.',
    bestTime: 'With a meal.',
    aliases: ['ginkgo', 'ginkgo biloba'],
    brand: 'Nature\'s Way',
    priceUsdMonthly: 10,
    baseScore: 3,
    signalBoosts: { 'aging': 1, 'senior': 1 },
  },
  {
    id: 'panax-ginseng',
    name: 'Panax ginseng',
    icon: '🌿',
    dose: '200-400 mg',
    window: 'morning',
    note: 'Stimulating; take earlier. Cycle to keep effects.',
    helps: 'Supports energy, focus, and stress resilience.',
    bestTime: 'Morning with food.',
    aliases: ['panax ginseng', 'ginseng', 'korean ginseng'],
    brand: 'Auragin',
    priceUsdMonthly: 18,
    baseScore: 4,
    signalBoosts: { 'aging': 1, 'low-recovery': 1, 'male': 1 },
  },
  {
    id: 'psyllium',
    name: 'Psyllium husk',
    icon: '🌿',
    dose: '5-10 g',
    window: 'anytime',
    note: 'Drink with plenty of water; take away from meds.',
    helps: 'Adds soluble fiber for regularity and cholesterol.',
    bestTime: 'With a large glass of water.',
    aliases: ['psyllium', 'psyllium husk', 'fiber'],
    brand: 'Metamucil',
    priceUsdMonthly: 10,
    baseScore: 5,
    signalBoosts: { 'general-health-goal': 1, 'cut-goal': 1, 'aging': 1 },
  },
  {
    id: 'digestive-enzymes',
    name: 'Digestive enzymes',
    icon: '🌿',
    dose: '1 capsule',
    window: 'anytime',
    note: 'Take with meals; helpful for heavy or rich foods.',
    helps: 'Aids breakdown of fats, carbs, and proteins.',
    bestTime: 'At the start of a meal.',
    aliases: ['digestive enzymes', 'enzymes', 'protease', 'lipase'],
    brand: 'NOW Foods Super Enzymes',
    priceUsdMonthly: 14,
    baseScore: 3,
    signalBoosts: { 'general-health-goal': 1, 'aging': 1 },
  },
  {
    id: 'glucosamine',
    name: 'Glucosamine',
    icon: '🦴',
    dose: '1500 mg',
    window: 'anytime',
    note: 'Take with food; effects build over weeks.',
    helps: 'May ease joint discomfort and support cartilage.',
    bestTime: 'With meals.',
    aliases: ['glucosamine', 'glucosamine sulfate'],
    brand: 'Doctor\'s Best',
    priceUsdMonthly: 14,
    baseScore: 4,
    signalBoosts: { 'aging': 2, 'senior': 1, 'heavy-training': 1 },
  },
  {
    id: 'chondroitin',
    name: 'Chondroitin',
    icon: '🦴',
    dose: '800-1200 mg',
    window: 'anytime',
    note: 'Often paired with glucosamine for joint support.',
    helps: 'Supports cartilage cushioning and joint comfort.',
    bestTime: 'With meals.',
    aliases: ['chondroitin', 'chondroitin sulfate'],
    brand: 'Doctor\'s Best',
    priceUsdMonthly: 16,
    baseScore: 3,
    signalBoosts: { 'aging': 2, 'senior': 1 },
  },
  {
    id: 'msm',
    name: 'MSM',
    icon: '🦴',
    dose: '1-3 g',
    window: 'anytime',
    note: 'Take with food; pairs with glucosamine for joints.',
    helps: 'May reduce joint pain and exercise-related soreness.',
    bestTime: 'With meals.',
    aliases: ['msm', 'methylsulfonylmethane'],
    brand: 'NOW Foods',
    priceUsdMonthly: 10,
    baseScore: 3,
    signalBoosts: { 'aging': 1, 'heavy-training': 1, 'low-recovery': 1 },
  },
  {
    id: 'boswellia',
    name: 'Boswellia',
    icon: '🦴',
    dose: '300-500 mg',
    window: 'anytime',
    note: 'Standardized to boswellic acids; take with food.',
    helps: 'Helps calm joint inflammation and stiffness.',
    bestTime: 'With meals.',
    aliases: ['boswellia', 'frankincense', 'indian frankincense'],
    brand: 'Life Extension',
    priceUsdMonthly: 16,
    baseScore: 4,
    signalBoosts: { 'aging': 1, 'senior': 1 },
  },
  {
    id: 'hyaluronic-acid',
    name: 'Hyaluronic acid',
    icon: '🦴',
    dose: '120-240 mg',
    window: 'anytime',
    note: 'Take with water; supports joints and skin hydration.',
    helps: 'Supports joint lubrication and skin moisture.',
    bestTime: 'With a meal.',
    aliases: ['hyaluronic acid', 'ha'],
    brand: 'Doctor\'s Best',
    priceUsdMonthly: 16,
    baseScore: 3,
    signalBoosts: { 'aging': 1, 'female': 1 },
  },
  {
    id: 'ubiquinol',
    name: 'Ubiquinol',
    icon: '❤️',
    dose: '100-200 mg',
    window: 'anytime',
    note: 'Reduced form of CoQ10; take with fat. Good for statin users.',
    helps: 'Supports heart energy and acts as an antioxidant.',
    bestTime: 'With a meal containing fat.',
    aliases: ['ubiquinol', 'reduced coq10'],
    brand: 'Qunol',
    priceUsdMonthly: 28,
    baseScore: 4,
    signalBoosts: { 'aging': 2, 'senior': 1 },
  },
  {
    id: 'garlic',
    name: 'Aged garlic extract',
    icon: '❤️',
    dose: '600-1200 mg',
    window: 'anytime',
    note: 'Take with food; odor-controlled extract is easiest.',
    helps: 'May support healthy blood pressure and cholesterol.',
    bestTime: 'With meals.',
    aliases: ['garlic', 'aged garlic', 'allicin', 'kyolic'],
    brand: 'Kyolic',
    priceUsdMonthly: 14,
    baseScore: 4,
    signalBoosts: { 'aging': 1, 'general-health-goal': 1 },
  },
  {
    id: 'nattokinase',
    name: 'Nattokinase',
    icon: '❤️',
    dose: '100-200 mg (2000 FU)',
    window: 'anytime',
    note: 'Avoid with blood thinners; check with a doctor first.',
    helps: 'May support healthy circulation and blood flow.',
    bestTime: 'On an empty stomach.',
    aliases: ['nattokinase', 'natto'],
    brand: 'Doctor\'s Best',
    priceUsdMonthly: 20,
    baseScore: 3,
    signalBoosts: { 'aging': 1, 'senior': 1 },
  },
  {
    id: 'citrus-bergamot',
    name: 'Citrus bergamot',
    icon: '❤️',
    dose: '500-1000 mg',
    window: 'anytime',
    note: 'Take before meals; supports lipid profile.',
    helps: 'May improve cholesterol and metabolic markers.',
    bestTime: 'Before meals.',
    aliases: ['citrus bergamot', 'bergamot'],
    brand: 'Jarrow Formulas',
    priceUsdMonthly: 22,
    baseScore: 4,
    signalBoosts: { 'aging': 1, 'general-health-goal': 1 },
  },
  {
    id: 'alpha-lipoic-acid',
    name: 'Alpha-lipoic acid',
    icon: '❤️',
    dose: '300-600 mg',
    window: 'anytime',
    note: 'Take on an empty stomach; R-form is better absorbed.',
    helps: 'An antioxidant that supports blood sugar and nerves.',
    bestTime: 'Before a meal.',
    aliases: ['alpha lipoic acid', 'ala lipoic', 'lipoic acid'],
    brand: 'Doctor\'s Best',
    priceUsdMonthly: 16,
    baseScore: 4,
    signalBoosts: { 'aging': 1, 'general-health-goal': 1 },
  },
  {
    id: 'cinnamon',
    name: 'Cinnamon extract',
    icon: '🌿',
    dose: '500-1000 mg',
    window: 'anytime',
    note: 'Use Ceylon to limit coumarin; take with carb-heavy meals.',
    helps: 'May modestly support blood sugar control.',
    bestTime: 'With carb-containing meals.',
    aliases: ['cinnamon', 'ceylon cinnamon'],
    brand: 'NOW Foods',
    priceUsdMonthly: 9,
    baseScore: 3,
    signalBoosts: { 'general-health-goal': 1, 'cut-goal': 1 },
  },
  {
    id: 'plant-sterols',
    name: 'Plant sterols',
    icon: '❤️',
    dose: '2 g',
    window: 'anytime',
    note: 'Take with the largest meal of the day.',
    helps: 'Helps lower LDL cholesterol absorption.',
    bestTime: 'With meals.',
    aliases: ['plant sterols', 'phytosterols', 'beta-sitosterol'],
    brand: 'NOW Foods',
    priceUsdMonthly: 14,
    baseScore: 4,
    signalBoosts: { 'aging': 1, 'general-health-goal': 1 },
  },
  {
    id: 'elderberry',
    name: 'Elderberry',
    icon: '🌿',
    dose: '300-600 mg',
    window: 'anytime',
    note: 'Use at first sign of a cold; take with or without food.',
    helps: 'May shorten and ease common cold symptoms.',
    bestTime: 'Anytime during illness.',
    aliases: ['elderberry', 'sambucus'],
    brand: 'Sambucol',
    priceUsdMonthly: 14,
    baseScore: 4,
    signalBoosts: { 'general-health-goal': 1 },
  },
  {
    id: 'quercetin',
    name: 'Quercetin',
    icon: '🌿',
    dose: '500-1000 mg',
    window: 'anytime',
    note: 'Pair with vitamin C for absorption; take with food.',
    helps: 'An antioxidant that supports immune and allergy response.',
    bestTime: 'With meals.',
    aliases: ['quercetin'],
    brand: 'Thorne',
    priceUsdMonthly: 16,
    baseScore: 4,
    signalBoosts: { 'general-health-goal': 1, 'aging': 1 },
  },
  {
    id: 'liposomal-vitamin-c',
    name: 'Liposomal vitamin C',
    icon: '🌿',
    dose: '500-1000 mg',
    window: 'anytime',
    note: 'Liposomal form for gentler absorption than ascorbic acid.',
    helps: 'Delivers antioxidant vitamin C with less GI upset.',
    bestTime: 'Anytime, with or without food.',
    aliases: ['liposomal vitamin c', 'liposomal c', 'lypo-c'],
    brand: 'LivOn Labs',
    priceUsdMonthly: 30,
    baseScore: 4,
    signalBoosts: { 'general-health-goal': 1, 'aging': 1 },
  },
  {
    id: 'nmn',
    name: 'NMN',
    icon: '🌿',
    dose: '250-500 mg',
    window: 'morning',
    note: 'NAD+ precursor; take in the morning. Evidence still emerging.',
    helps: 'May support cellular energy and healthy aging.',
    bestTime: 'Morning, empty stomach.',
    aliases: ['nmn', 'nicotinamide mononucleotide'],
    brand: 'ProHealth',
    priceUsdMonthly: 45,
    baseScore: 3,
    signalBoosts: { 'aging': 2, 'senior': 1 },
  },
  {
    id: 'nr',
    name: 'Nicotinamide riboside',
    icon: '🌿',
    dose: '300 mg',
    window: 'morning',
    note: 'NAD+ precursor; take with breakfast.',
    helps: 'May support NAD+ levels and cellular energy.',
    bestTime: 'Morning with food.',
    aliases: ['nr', 'nicotinamide riboside', 'niagen'],
    brand: 'Tru Niagen',
    priceUsdMonthly: 40,
    baseScore: 3,
    signalBoosts: { 'aging': 2, 'senior': 1 },
  },
  {
    id: 'resveratrol',
    name: 'Resveratrol',
    icon: '🌿',
    dose: '150-500 mg',
    window: 'anytime',
    note: 'Take with fat for absorption; often paired with NAD+ boosters.',
    helps: 'An antioxidant studied for heart and longevity support.',
    bestTime: 'With a meal containing fat.',
    aliases: ['resveratrol', 'trans-resveratrol'],
    brand: 'Thorne',
    priceUsdMonthly: 25,
    baseScore: 3,
    signalBoosts: { 'aging': 1, 'general-health-goal': 1 },
  },
  {
    id: 'pqq',
    name: 'PQQ',
    icon: '🌿',
    dose: '10-20 mg',
    window: 'morning',
    note: 'Often paired with CoQ10; take in the morning.',
    helps: 'May support mitochondrial growth and energy.',
    bestTime: 'Morning with food.',
    aliases: ['pqq', 'pyrroloquinoline quinone'],
    brand: 'Life Extension',
    priceUsdMonthly: 24,
    baseScore: 3,
    signalBoosts: { 'aging': 1, 'low-recovery': 1 },
  },
  {
    id: 'astaxanthin',
    name: 'Astaxanthin',
    icon: '🌿',
    dose: '4-12 mg',
    window: 'anytime',
    note: 'Fat-soluble; take with a meal containing fat.',
    helps: 'A potent antioxidant for skin, eyes, and recovery.',
    bestTime: 'With a meal containing fat.',
    aliases: ['astaxanthin'],
    brand: 'Sports Research',
    priceUsdMonthly: 18,
    baseScore: 4,
    signalBoosts: { 'aging': 1, 'low-recovery': 1, 'general-health-goal': 1 },
  },
  {
    id: 'sulforaphane',
    name: 'Sulforaphane',
    icon: '🌿',
    dose: '10-30 mg',
    window: 'anytime',
    note: 'From broccoli sprout extract; take with food.',
    helps: 'Activates detox pathways and antioxidant defenses.',
    bestTime: 'With a meal.',
    aliases: ['sulforaphane', 'broccoli sprout', 'broccoli extract'],
    brand: 'Jarrow Formulas',
    priceUsdMonthly: 28,
    baseScore: 3,
    signalBoosts: { 'aging': 1, 'general-health-goal': 1 },
  },
  {
    id: 'urolithin-a',
    name: 'Urolithin A',
    icon: '🌿',
    dose: '500 mg',
    window: 'anytime',
    note: 'Take with food; supports mitochondrial quality.',
    helps: 'May improve muscle endurance and cellular renewal.',
    bestTime: 'With a meal.',
    aliases: ['urolithin a', 'urolithin', 'mitopure'],
    brand: 'Timeline Mitopure',
    priceUsdMonthly: 60,
    baseScore: 3,
    signalBoosts: { 'aging': 2, 'senior': 1, 'low-recovery': 1 },
  },
  {
    id: 'maca',
    name: 'Maca root',
    icon: '🌿',
    dose: '1.5-3 g',
    window: 'anytime',
    note: 'Take with food; effects build over weeks.',
    helps: 'May support energy, libido, and mood.',
    bestTime: 'With breakfast.',
    aliases: ['maca', 'maca root'],
    brand: 'Gaia Herbs',
    priceUsdMonthly: 12,
    baseScore: 3,
    signalBoosts: { 'male': 1, 'female': 1, 'low-recovery': 1 },
  },
  {
    id: 'holy-basil',
    name: 'Holy basil (Tulsi)',
    icon: '🌿',
    dose: '300-600 mg',
    window: 'anytime',
    note: 'Adaptogen; take with food. Calming over time.',
    helps: 'Helps the body adapt to stress and supports calm.',
    bestTime: 'With meals or evening.',
    aliases: ['holy basil', 'tulsi', 'ocimum sanctum'],
    brand: 'Organic India',
    priceUsdMonthly: 12,
    baseScore: 3,
    signalBoosts: { 'low-recovery': 1, 'poor-sleep': 1 },
  },
  {
    id: 'eleuthero',
    name: 'Eleuthero',
    icon: '🌿',
    dose: '300-1200 mg',
    window: 'morning',
    note: 'Siberian ginseng adaptogen; take earlier in the day.',
    helps: 'May support stamina and resilience to fatigue.',
    bestTime: 'Morning with food.',
    aliases: ['eleuthero', 'siberian ginseng', 'eleutherococcus'],
    brand: 'Gaia Herbs',
    priceUsdMonthly: 12,
    baseScore: 3,
    signalBoosts: { 'low-recovery': 1, 'heavy-training': 1 },
  },
  {
    id: 'shilajit',
    name: 'Shilajit',
    icon: '🌿',
    dose: '250-500 mg',
    window: 'anytime',
    note: 'Use purified, lab-tested product to avoid heavy metals.',
    helps: 'May support energy, testosterone, and mineral status.',
    bestTime: 'With a meal.',
    aliases: ['shilajit', 'fulvic acid'],
    brand: 'Cymbiotika',
    priceUsdMonthly: 30,
    baseScore: 3,
    signalBoosts: { 'male': 1, 'low-recovery': 1, 'aging': 1 },
  },
  {
    id: 'greens-powder',
    name: 'Greens powder',
    icon: '🌿',
    dose: '1 scoop',
    window: 'anytime',
    note: 'A convenience supplement, not a replacement for vegetables.',
    helps: 'Adds a blend of vegetable and antioxidant nutrients.',
    bestTime: 'Morning in water.',
    aliases: ['greens', 'greens powder', 'super greens', 'ag1'],
    brand: 'AG1',
    priceUsdMonthly: 79,
    baseScore: 4,
    signalBoosts: { 'general-health-goal': 1 },
  },
  {
    id: 'spirulina',
    name: 'Spirulina',
    icon: '🌿',
    dose: '3-5 g',
    window: 'anytime',
    note: 'Use a tested source; take with food.',
    helps: 'A nutrient-dense algae rich in protein and antioxidants.',
    bestTime: 'With a meal.',
    aliases: ['spirulina', 'blue-green algae'],
    brand: 'NOW Foods',
    priceUsdMonthly: 12,
    baseScore: 3,
    signalBoosts: { 'general-health-goal': 1 },
  },
  {
    id: 'dim',
    name: 'DIM',
    icon: '💊',
    dose: '100-200 mg',
    window: 'anytime',
    note: 'Take with food; supports healthy estrogen metabolism.',
    helps: 'May help balance estrogen metabolism.',
    bestTime: 'With a meal.',
    aliases: ['dim', 'diindolylmethane'],
    brand: 'Thorne',
    priceUsdMonthly: 18,
    baseScore: 3,
    signalBoosts: { 'male': 1, 'female': 1, 'aging': 1 },
  },
  {
    id: 'saw-palmetto',
    name: 'Saw palmetto',
    icon: '💊',
    dose: '320 mg',
    window: 'anytime',
    note: 'Take with food; used for prostate and hair concerns.',
    helps: 'May support prostate health and urinary flow.',
    bestTime: 'With a meal.',
    aliases: ['saw palmetto', 'serenoa'],
    brand: 'NOW Foods',
    priceUsdMonthly: 12,
    baseScore: 4,
    signalBoosts: { 'male': 2, 'aging': 1, 'senior': 1 },
  },
  {
    id: 'fenugreek',
    name: 'Fenugreek',
    icon: '🌿',
    dose: '500-600 mg',
    window: 'anytime',
    note: 'Take with food; may add a maple-like body odor.',
    helps: 'May support libido and healthy testosterone.',
    bestTime: 'With a meal.',
    aliases: ['fenugreek', 'testofen'],
    brand: 'NOW Foods',
    priceUsdMonthly: 12,
    baseScore: 3,
    signalBoosts: { 'male': 1, 'heavy-training': 1 },
  },
  {
    id: 'myo-inositol',
    name: 'Myo-inositol',
    icon: '💊',
    dose: '2-4 g',
    window: 'anytime',
    note: 'Often used 40:1 with D-chiro for cycle and insulin support.',
    helps: 'Supports insulin sensitivity and ovulatory health.',
    bestTime: 'Split morning and evening.',
    aliases: ['myo-inositol', 'inositol', 'myo inositol'],
    brand: 'Wholesome Story',
    priceUsdMonthly: 20,
    baseScore: 4,
    signalBoosts: { 'female': 2, 'general-health-goal': 1 },
  },
  {
    id: 'cranberry',
    name: 'Cranberry extract',
    icon: '🌿',
    dose: '500 mg (36 mg PAC)',
    window: 'anytime',
    note: 'Standardized to PACs; take with water.',
    helps: 'May reduce recurrence of urinary tract infections.',
    bestTime: 'With a meal.',
    aliases: ['cranberry', 'cranberry extract', 'pacran'],
    brand: 'Theralogix',
    priceUsdMonthly: 18,
    baseScore: 4,
    signalBoosts: { 'female': 2 },
  },
  {
    id: 'dhea',
    name: 'DHEA',
    icon: '💊',
    dose: '25-50 mg',
    window: 'morning',
    note: 'A hormone precursor; use only with medical guidance.',
    helps: 'May support hormone levels that decline with age.',
    bestTime: 'Morning with food.',
    aliases: ['dhea', 'dehydroepiandrosterone'],
    brand: 'Life Extension',
    priceUsdMonthly: 10,
    baseScore: 3,
    signalBoosts: { 'aging': 1, 'senior': 2 },
  },
  {
    id: 'sam-e',
    name: 'SAM-e',
    icon: '🧠',
    dose: '400-800 mg',
    window: 'morning',
    note: 'Take on an empty stomach. Avoid with SSRIs; can be activating.',
    helps: 'May support mood and joint comfort.',
    bestTime: 'Morning before food.',
    aliases: ['sam-e', 'same', 's-adenosylmethionine'],
    brand: 'Jarrow Formulas',
    priceUsdMonthly: 30,
    baseScore: 4,
    signalBoosts: { 'aging': 1 },
  },
  {
    id: 'saffron',
    name: 'Saffron extract',
    icon: '🧠',
    dose: '28-30 mg',
    window: 'anytime',
    note: 'Standardized extract; take with food. Builds over weeks.',
    helps: 'May support mood and emotional balance.',
    bestTime: 'With a meal.',
    aliases: ['saffron', 'saffron extract', 'affron'],
    brand: 'Life Extension',
    priceUsdMonthly: 22,
    baseScore: 4,
    signalBoosts: { 'poor-sleep': 1 },
  },
  {
    id: 'ginger',
    name: 'Ginger extract',
    icon: '🌿',
    dose: '500-1000 mg',
    window: 'anytime',
    note: 'Take with food; helpful for nausea and digestion.',
    helps: 'Eases nausea and supports digestion and recovery.',
    bestTime: 'With meals.',
    aliases: ['ginger', 'ginger extract'],
    brand: 'NOW Foods',
    priceUsdMonthly: 9,
    baseScore: 3,
    signalBoosts: { 'general-health-goal': 1, 'low-recovery': 1 },
  },
  {
    id: 'green-tea-egcg',
    name: 'Green tea extract (EGCG)',
    icon: '🌿',
    dose: '300-500 mg',
    window: 'morning',
    note: 'Take with food to protect the liver; contains some caffeine.',
    helps: 'An antioxidant that may modestly support fat metabolism.',
    bestTime: 'Morning with food.',
    aliases: ['green tea', 'egcg', 'green tea extract'],
    brand: 'NOW Foods',
    priceUsdMonthly: 12,
    baseScore: 3,
    signalBoosts: { 'cut-goal': 1, 'general-health-goal': 1 },
  },
]

export const WINDOWS: WindowMeta[] = [
  { key: 'morning', icon: '🌅', title: 'Morning', time: '7-10 AM', cutoffHour: 10 },
  { key: 'lunch',   icon: '🍽️', title: 'Midday',  time: '12-2 PM', cutoffHour: 14 },
  { key: 'evening', icon: '🌙', title: 'Evening', time: '6-9 PM',  cutoffHour: 21 },
  { key: 'bed',     icon: '🛏️', title: 'Before bed', time: '10 PM', cutoffHour: null },
  { key: 'anytime', icon: '⏱️', title: 'Anytime', time: 'No fixed window', cutoffHour: null },
]

/**
 * Intake-condition labels — the small "how to take it" library. Color-coded by
 * tone: food (amber), empty/away (carb blue), timing (iris), water (mint).
 * Attached per stack item; surfaced as quiet reminders on the day rail.
 */
export const CONDITIONS: ConditionLabel[] = [
  { id: 'with-food',       label: 'With food',         tone: 'food',   icon: 'eaten' },
  { id: 'with-meal',       label: 'With a meal',       tone: 'food',   icon: 'eaten' },
  { id: 'with-fat',        label: 'With fat',          tone: 'food',   icon: 'eaten' },
  { id: 'after-meal',      label: 'After a meal',      tone: 'food',   icon: 'eaten' },
  { id: 'empty-stomach',   label: 'Empty stomach',     tone: 'empty',  icon: 'plate' },
  { id: 'away-caffeine',   label: 'Away from caffeine', tone: 'empty', icon: 'clock' },
  { id: 'away-minerals',   label: 'Away from iron/calcium', tone: 'empty', icon: 'clock' },
  { id: 'before-bed',      label: 'Before bed',        tone: 'timing', icon: 'bed' },
  { id: 'before-training', label: 'Before training',   tone: 'timing', icon: 'dumbbell' },
  { id: 'after-training',  label: 'After training',    tone: 'timing', icon: 'dumbbell' },
  { id: 'morning-light',   label: 'With morning light', tone: 'timing', icon: 'sun' },
  { id: 'plenty-water',    label: 'Plenty of water',   tone: 'water',  icon: 'drop' },
  { id: 'with-caffeine',   label: 'Pairs with caffeine', tone: 'timing', icon: 'coffee' },
  { id: 'consistent',      label: 'Be consistent',     tone: 'habit',  icon: 'calendar' },
]

export const CONDITION_BY_ID: Record<string, ConditionLabel> =
  Object.fromEntries(CONDITIONS.map((c) => [c.id, c]))

/**
 * Important condition reminders carried over from the library when a user adds
 * a supplement from search. Keyed by DB id; only the ones where it genuinely
 * matters. Everything else starts with no condition (the user can add their own).
 */
export const DB_CONDITION_HINTS: Record<string, string[]> = {
  'creatine': [],
  'beta-alanine': [],
  'l-citrulline': ['before-training'],
  'whey': ['after-training'],
  'casein': ['before-bed'],
  'l-carnitine': ['with-meal'],
  'alcar': ['empty-stomach'],
  'vit-d3': ['with-food', 'with-fat'],
  'vit-k2': ['with-food', 'with-fat'],
  'vit-c': [],
  'b12': ['morning-light'],
  'b-complex': ['morning-light'],
  'multivitamin': ['with-food'],
  'mag-glycinate': ['before-bed'],
  'mag-threonate': ['before-bed'],
  'zinc': ['with-food', 'away-minerals'],
  'iron': ['empty-stomach', 'away-minerals'],
  'omega-3': ['with-food', 'with-fat'],
  'l-theanine': ['with-caffeine'],
  'rhodiola': ['morning-light'],
  'lions-mane': [],
  'alpha-gpc': ['before-training'],
  'nac': ['empty-stomach'],
  'melatonin': ['before-bed'],
  'glycine': ['before-bed'],
  'ashwagandha': [],
  'tryptophan': ['before-bed'],
  'apigenin': ['before-bed'],
  'caffeine': ['before-training'],
  'probiotics': [],
  'curcumin': ['with-food', 'with-fat'],
  'coq10': ['with-food', 'with-fat'],
  'berberine': ['with-meal'],
  'collagen': [],
  'tongkat': ['morning-light'],
  'fadogia': [],
  'reishi': ['before-bed'],
  'cordyceps': ['morning-light'],
  'taurine': [],
  'betaine-tmg': [],
  'hmb': [],
  'eaa': ['after-training'],
  'electrolytes': [],
  'sodium-bicarbonate': ['before-training'],
  'beetroot': ['before-training'],
  'egg-protein': ['after-training'],
  'pea-protein': ['after-training'],
  'folate': [],
  'vit-b6': ['morning-light'],
  'vit-b1': ['morning-light'],
  'calcium': ['with-food'],
  'selenium': [],
  'chromium': ['with-food'],
  'boron': [],
  'krill-oil': ['with-food', 'with-fat'],
  'evening-primrose': ['with-food', 'with-fat'],
  'valerian': ['before-bed'],
  'tart-cherry': ['before-bed'],
  '5-htp': ['before-bed'],
  'l-tyrosine': ['empty-stomach'],
  'lavender-silexan': ['before-bed'],
  'bacopa': ['with-food'],
  'citicoline': [],
  'phosphatidylserine': ['with-food'],
  'ginkgo': [],
  'panax-ginseng': ['morning-light'],
  'psyllium': ['plenty-water'],
  'digestive-enzymes': ['with-meal'],
  'glucosamine': [],
  'chondroitin': [],
  'msm': [],
  'boswellia': ['with-food', 'with-fat'],
  'hyaluronic-acid': [],
  'ubiquinol': ['with-food', 'with-fat'],
  'garlic': ['with-food'],
  'nattokinase': ['empty-stomach'],
  'citrus-bergamot': ['with-meal'],
  'alpha-lipoic-acid': ['empty-stomach'],
  'cinnamon': ['with-meal'],
  'plant-sterols': ['with-meal'],
  'elderberry': [],
  'quercetin': ['with-food'],
  'liposomal-vitamin-c': [],
  'nmn': [],
  'nr': [],
  'resveratrol': ['with-food', 'with-fat'],
  'pqq': [],
  'astaxanthin': ['with-food', 'with-fat'],
  'sulforaphane': [],
  'urolithin-a': ['with-food'],
  'maca': [],
  'holy-basil': [],
  'eleuthero': ['morning-light'],
  'shilajit': [],
  'greens-powder': [],
  'spirulina': [],
  'dim': ['with-food', 'with-fat'],
  'saw-palmetto': ['with-food', 'with-fat'],
  'fenugreek': ['with-food'],
  'myo-inositol': [],
  'cranberry': [],
  'dhea': ['morning-light'],
  'sam-e': ['empty-stomach'],
  'saffron': [],
  'ginger': ['with-food'],
  'green-tea-egcg': ['with-food'],
}

/**
 * Supplements whose benefit builds from cumulative, daily use (saturation,
 * tissue levels, adaptogen/nootropic adaptation) rather than an acute per-dose
 * effect. These get the "be consistent" recommendation up front. Acute /
 * per-dose / situational supplements (caffeine, pre-workout, melatonin, immune
 * boosters, proteins) are intentionally excluded — there the tag is noise.
 */
export const CONSISTENCY_IDS = new Set<string>([
  'creatine', 'beta-alanine', 'l-carnitine', 'alcar', 'vit-d3', 'vit-k2', 'b12',
  'b-complex', 'multivitamin', 'mag-glycinate', 'mag-threonate', 'zinc', 'iron', 'omega-3',
  'rhodiola', 'lions-mane', 'nac', 'ashwagandha', 'probiotics', 'curcumin', 'coq10',
  'berberine', 'collagen', 'tongkat', 'fadogia', 'reishi', 'cordyceps', 'betaine-tmg',
  'hmb', 'folate', 'vit-b6', 'vit-b1', 'calcium', 'selenium', 'chromium',
  'boron', 'krill-oil', 'evening-primrose', 'lavender-silexan', 'bacopa', 'citicoline', 'phosphatidylserine',
  'ginkgo', 'panax-ginseng', 'glucosamine', 'chondroitin', 'msm', 'boswellia', 'hyaluronic-acid',
  'ubiquinol', 'garlic', 'nattokinase', 'citrus-bergamot', 'alpha-lipoic-acid', 'cinnamon', 'plant-sterols',
  'quercetin', 'nmn', 'nr', 'resveratrol', 'pqq', 'astaxanthin', 'sulforaphane',
  'urolithin-a', 'maca', 'holy-basil', 'eleuthero', 'shilajit', 'greens-powder', 'spirulina',
  'dim', 'saw-palmetto', 'fenugreek', 'myo-inositol', 'dhea', 'sam-e', 'saffron',
  'green-tea-egcg',
])

/** The conditions Vitality recommends for a library supplement: consistency
 *  first (for cumulative ones), then its intake conditions. */
export function recommendedFor(sourceId: string | null): string[] {
  if (!sourceId) return []
  const base = DB_CONDITION_HINTS[sourceId] ?? []
  return CONSISTENCY_IDS.has(sourceId) ? ['consistent', ...base] : base
}
